module.exports = {
  name: "Cry Havoc",

  roles: [
    { id: "Humans", name: "Humans", },
    { id: "Machines", name: "Machines", },
    { id: "Pilgrims", name: "Pilgrims", },
    { id: "Trogs", name: "Trogs", },
  ],

  objects: [
    {id: "Map", front: "cry_havoc/board_large.jpg", locked:true, x: 70, y: 170, width: 990, height: 661, snapZones: [{x: 884, y: 12, width: 88, height: 600, cellWidth: 44, cellHeight: 24}, {x: 756, y: 93, width: 104, height: 26, cellWidth: 26}, {x: 756, y: 154, width: 104, height: 26, cellWidth: 26}, {x: 799, y: 489, width: 47, height: 162, cellHeight: 54} ] },
    {id: "Terrain", front: "cry_havoc/tactics_decks.jpg", locked:true, x: 89, y: 184, width: 140, height: 214, snapZones: [{x: 14, y: 29, width: 50, height: 70}, {x: 77, y: 29, width: 50, height: 70}, {x: 14, y: 128, width: 50, height: 70}, {x: 77, y: 128, width: 50, height: 70} ]},
    {id: "Battle", front: "cry_havoc/battle-board.jpg", immobile:true, x: 90, y: 609, width: 99, height: 203},
    /*{id: "Region Control", front: "cry_havoc/battle1.jpg", immobile:true, x: 743, y: 290, width: 99, height: 66},
    {id: "Capture Prisoners", front: "cry_havoc/battle2.jpg", immobile:true, x: 743, y: 356, width: 99, height: 68},
    {id: "Attrition", front: "cry_havoc/battle3.jpg", immobile:true, x: 743, y: 424, width: 99, height: 69},*/

    {id: "Action Marker", width: 47, height: 54, front: "cry_havoc/action.png", x: 869, y: 659},

    {id: "c", prototype: true, width: 25, height: 25, front: "cry_havoc/crystal.png", hasLabel: true, labelColor: ["#2d6341"]},

    {id: "Crystal 1", prototypes: ["c"], x: 1070, y: 170},
    {id: "Crystal 2", prototypes: ["c"], x: 1070, y: 190},
    {id: "Crystal 3", prototypes: ["c"], x: 1070, y: 210},
    {id: "Crystal 4", prototypes: ["c"], x: 1070, y: 230},
    {id: "Crystal 5", prototypes: ["c"], x: 1070, y: 250},
    {id: "Crystal 6", prototypes: ["c"], x: 1070, y: 270},
    {id: "Crystal 7", prototypes: ["c"], x: 1070, y: 290},
    {id: "Crystal 8", prototypes: ["c"], x: 1090, y: 170},
    {id: "Crystal 9", prototypes: ["c"], x: 1090, y: 190},
    {id: "Crystal 10", prototypes: ["c"], x: 1090, y: 210},
    {id: "Crystal 11", prototypes: ["c"], x: 1090, y: 230},
    {id: "Crystal 12", prototypes: ["c"], x: 1090, y: 250},
    {id: "Crystal 13", prototypes: ["c"], x: 1090, y: 270},
    {id: "Crystal 14", prototypes: ["c"], x: 503, y: 416, label: 5},
    {id: "Crystal 15", prototypes: ["c"], x: 589, y: 386, label: 2},
    {id: "Crystal 16", prototypes: ["c"], x: 363, y: 460, label: 2},
    {id: "Crystal 17", prototypes: ["c"], x: 578, y: 595, label: 2},

    {id: "b", prototype: true, width: 25, height: 25},

    {id: "Battle 1", prototypes: ["b"], x: 1070, y: 325, front: "cry_havoc/token/battle_1.png"},
    {id: "Battle 2", prototypes: ["b"], x: 1070, y: 350, front: "cry_havoc/token/battle_2.png"},
    {id: "Battle 3", prototypes: ["b"], x: 1070, y: 375, front: "cry_havoc/token/battle_3.png"},
    {id: "Battle 4", prototypes: ["b"], x: 1070, y: 400, front: "cry_havoc/token/battle_4.png"},
    {id: "Battle 5", prototypes: ["b"], x: 1070, y: 425, front: "cry_havoc/token/battle_5.png"},
    {id: "Battle 6", prototypes: ["b"], x: 1070, y: 450, front: "cry_havoc/token/battle_6.png"},
    {id: "Battle 7", prototypes: ["b"], x: 1070, y: 475, front: "cry_havoc/token/battle_7.png"},
    {id: "Battle 8", prototypes: ["b"], x: 1070, y: 500, front: "cry_havoc/token/battle_8.png"},

    {id: "Final Scoring", front: "cry_havoc/final_scoring.png", width: 33, height: 33, x: 959, y: 790},

    {id: "tactics", prototype: true, width: 50, height: 70, back: "cry_havoc/tactics/tactics.jpg"},

    {id: "handScreen", prototype: true, locked: true, width: 400, height: 70, hideFaces: ["front"], snapZones: [{}], },

    {id: "jt", prototype: true, prototypes: ["tactics"], x:103, y: 213},
    {id: "dt", prototype: true, prototypes: ["tactics"], x:166, y: 213},
    {id: "mt", prototype: true, prototypes: ["tactics"], x:103, y: 312},
    {id: "ot", prototype: true, prototypes: ["tactics"], x:166, y: 312},

    {id: "ht", prototype: true, prototypes: ["tactics"], x:10, y: 90},
    {id: "pt", prototype: true, prototypes: ["tactics"], x:600, y: 90},
    {id: "mat", prototype: true, prototypes: ["tactics"], x:10, y: 915},
    {id: "tt", prototype: true, prototypes: ["tactics"], x:600, y: 915},

    {id: "Human Reference", immobile: true, front: "cry_havoc/human/reference.jpg", x: 10, y: 10, width: 206, height: 70},
    {id: "Pilgrim Reference", immobile: true, front: "cry_havoc/pilgrim/reference.jpg", x: 600, y: 10, width: 206, height: 70},
    {id: "Machines Reference", immobile: true, front: "cry_havoc/machine/reference.jpg", x: 10, y: 835, width: 312, height: 70},
    {id: "Trog Reference", immobile: true, front: "cry_havoc/trog/reference.jpg", x: 600, y: 835, width: 206, height: 70},

    {id: "holder", prototype: true, front: "cry_havoc/deck_holder.png", locked: true, width: 110, height: 70, snapZones: [{x: 0, y:0, width: 50, height: 70}, {x: 60, y:0, width: 50, height: 70}]},
    {prototypes: ["holder"], x: 10, y: 90},
    {prototypes: ["holder"], x: 600, y: 90},
    {prototypes: ["holder"], x: 10, y: 915},
    {prototypes: ["holder"], x: 600, y: 915},

    {id: "hs", prototype: true, width: 43, height: 70, back: "cry_havoc/human/skill.jpg", x: 70, y: 90},
    {id: "ps", prototype: true, prototypes: ["hs"], back: "cry_havoc/pilgrim/skill.jpg", x: 660, y: 90},
    {id: "ms", prototype: true, prototypes: ["hs"], back: "cry_havoc/machine/skill.jpg", x: 70, y: 915},
    {id: "ts", prototype: true, prototypes: ["hs"], back: "cry_havoc/trog/skill.jpg", x: 660, y: 915},

    {id: "Human Scoring", front: "cry_havoc/human/scoring.png", width: 33, height: 33, x: 226, y: 10},

    {id: "Human Control 1", front: "cry_havoc/human/control.png", width: 25, height: 25, x: 226, y: 53},
    {id: "Human Control 2", prototypes: ["Human Control 1"], x: 229},
    {id: "Human Control 3", prototypes: ["Human Control 1"], x: 232},
    {id: "Human Control 4", prototypes: ["Human Control 1"], x: 235},
    {id: "Human Control 5", prototypes: ["Human Control 1"], x: 238},
    {id: "Human Control 6", prototypes: ["Human Control 1"], x: 241},
    {id: "Human Control 7", prototypes: ["Human Control 1"], x: 244},
    {id: "Human Control 8", prototypes: ["Human Control 1"], x: 247},

    {id: "Watchtower Token", front: "cry_havoc/human/mark_watchtower.png", x: 269, y: 10, width: 18, height: 18},
    {id: "Watchtower Token ", prototypes: ["Watchtower Token"], x: 272},
    {id: "Watchtower Token  ", prototypes: ["Watchtower Token"], x: 275},
    {id: "Artillery Token", front: "cry_havoc/human/mark_artillery.png", x: 269, y: 33, width: 18, height: 18},
    {id: "Artillery Token ", prototypes: ["Artillery Token"], x: 272},
    {id: "Artillery Token  ", prototypes: ["Artillery Token"], x: 275},

    {id: "Pilgrim Scoring", front: "cry_havoc/pilgrim/scoring.png", width: 33, height: 33, x: 816, y: 10},

    {id: "Pilgrim Control 1", front: "cry_havoc/pilgrim/control.png", width: 23, height: 25, x: 816, y: 53},
    {id: "Pilgrim Control 2", prototypes: ["Pilgrim Control 1"], x: 819},
    {id: "Pilgrim Control 3", prototypes: ["Pilgrim Control 1"], x: 822},
    {id: "Pilgrim Control 4", prototypes: ["Pilgrim Control 1"], x: 825},
    {id: "Pilgrim Control 5", prototypes: ["Pilgrim Control 1"], x: 828},
    {id: "Pilgrim Control 6", prototypes: ["Pilgrim Control 1"], x: 831},
    {id: "Pilgrim Control 7", prototypes: ["Pilgrim Control 1"], x: 834},
    {id: "Pilgrim Control 8", prototypes: ["Pilgrim Control 1"], x: 837},
    
    {id: "Machine Scoring", front: "cry_havoc/machine/scoring.png", width: 33, height: 33, x: 332, y: 835},

    {id: "Machine Control 1", front: "cry_havoc/machine/control.png", width: 25, height: 25, x: 332, y: 878},
    {id: "Machine Control 2", prototypes: ["Machine Control 1"], x: 335},
    {id: "Machine Control 3", prototypes: ["Machine Control 1"], x: 338},
    {id: "Machine Control 4", prototypes: ["Machine Control 1"], x: 341},
    {id: "Machine Control 5", prototypes: ["Machine Control 1"], x: 344},
    {id: "Machine Control 6", prototypes: ["Machine Control 1"], x: 347},
    {id: "Machine Control 7", prototypes: ["Machine Control 1"], x: 350},
    {id: "Machine Control 8", prototypes: ["Machine Control 1"], x: 353},

    {id: "Trog Scoring", front: "cry_havoc/trog/scoring.png", width: 33, height: 33, x: 816, y: 835},

    {id: "Trog Control 1", front: "cry_havoc/trog/control.png", width: 25, height: 25, x: 816, y: 878},
    {id: "Trog Control 2", prototypes: ["Trog Control 1"], x: 819},
    {id: "Trog Control 3", prototypes: ["Trog Control 1"], x: 822},
    {id: "Trog Control 4", prototypes: ["Trog Control 1"], x: 825},
    {id: "Trog Control 5", prototypes: ["Trog Control 1"], x: 828},
    {id: "Trog Control 6", prototypes: ["Trog Control 1"], x: 831},
    {id: "Trog Control 7", prototypes: ["Trog Control 1"], x: 834},
    {id: "Trog Control 8", prototypes: ["Trog Control 1"], x: 837},

    {id: "Seek and Destroy Marker", front: "cry_havoc/human/mark_seek_and_destroy.png", width: 22, height: 25, x: 297, y: 10},
    {id: "Veteran Forces Marker", front: "cry_havoc/human/mark_veteran_forces.png", width: 22, height: 25, x: 297, y: 45},

    {id: "Power Extraction Marker", front: "cry_havoc/pilgrim/mark_power_extraction.png", width: 22, height: 25, x: 872, y: 10},

    {id: "Firepower Marker", front: "cry_havoc/machine/mark_firepower.png", width: 22, height: 25, x: 388, y: 835},
    {id: "Terrain Advantage Marker", front: "cry_havoc/machine/mark_terrain_advantage.png", width: 22, height: 25, x: 388, y: 870},

    {id: "Native Forces Marker", front: "cry_havoc/trog/mark_native_forces.png", width: 22, height: 25, x: 872, y: 835},

    {id: "Human HQ", front: "cry_havoc/human/hq.png", x: 426, y: 10, width: 40, height: 40},
    {id: "Pilgrim HQ", front: "cry_havoc/pilgrim/hq.png", x: 1016, y: 10, width: 40, height: 40},
    {id: "Machine HQ", front: "cry_havoc/machine/hq.png", x: 426, y: 835, width: 40, height: 40},
    {id: "Trog HQ", front: "cry_havoc/trog/hq.png", x: 998, y: 835, width: 40, height: 40},
    
    {prototypes: ["handScreen"], x: 130, y: 90, visionWhitelist: ["Humans"], backgroundColor: "rgba(254,221,1,alpha)", labelPlayerName: "Humans", },
    {prototypes: ["handScreen"], x: 720, y: 90, visionWhitelist: ["Pilgrims"], backgroundColor: "rgba(0,169,230,alpha)", labelPlayerName: "Pilgrims", },
    {prototypes: ["handScreen"], x: 130, y: 915, visionWhitelist: ["Machines"], backgroundColor: "rgba(212,19,20,alpha)", labelPlayerName: "Machines", },
    {prototypes: ["handScreen"], x: 720, y: 915, visionWhitelist: ["Trogs"], backgroundColor: "rgba(95,159,54,alpha)", labelPlayerName: "Trogs", },

    {id: "Human Score", front: "cry_havoc/human/score.png", back: "cry_havoc/human/score50.png", x: 998, y: 182, width: 24, height: 24},
    {id: "Pilgrim Score", front: "cry_havoc/pilgrim/score.png", back: "cry_havoc/pilgrim/score50.png", x: 1004, y: 182, width: 24, height: 24},
    {id: "Machine Score", front: "cry_havoc/machine/score.png", back: "cry_havoc/machine/score50.png", x: 1010, y: 182, width: 24, height: 24},
    {id: "Trog Score", front: "cry_havoc/trog/score.png", back: "cry_havoc/trog/score50.png", x: 1016, y: 182, width: 24, height: 24},

    {id: "Human Initiative", front: "cry_havoc/human/score.png", x: 826, y: 263, width: 26, height: 26},
    {id: "Pilgrim Initiative", front: "cry_havoc/pilgrim/score.png", x: 852, y: 263, width: 26, height: 26},
    {id: "Machine Initiative", front: "cry_havoc/machine/score.png", x: 878, y: 263, width: 26, height: 26},
    {id: "Trog Initiative", front: "cry_havoc/trog/score.png", x: 904, y: 263, width: 26, height: 26},

    {id: "Human Initiative ", prototypes: ["Human Initiative"], y: 324},
    {id: "Pilgrim Initiative ", prototypes: ["Pilgrim Initiative"], y: 324},
    {id: "Machine Initiative ", prototypes: ["Machine Initiative"], y: 324},
    {id: "Trog Initiative ", prototypes: ["Trog Initiative"], y: 324},

    {id: "b", prototype: true, width: 25, height: 25},

    {id: "Airfield", front: "cry_havoc/human/airfield.jpg", prototypes: ["b"], x: 74, y: 21},
    {id: "Airfield ", prototypes: ["Airfield"], x: 82},
    {id: "Airfield  ", prototypes: ["Airfield"], x: 90},
    {id: "Watchtower", front: "cry_havoc/human/watchtower.jpg", prototypes: ["b"], x: 125, y: 21},
    {id: "Watchtower ", prototypes: ["Watchtower"], x: 133},
    {id: "Watchtower  ", prototypes: ["Watchtower"], x: 141},
    {id: "Artillery", front: "cry_havoc/human/artillery.jpg", prototypes: ["b"], x: 176, y: 21},
    {id: "Artillery ", prototypes: ["Artillery"], x: 184},
    {id: "Artillery  ", prototypes: ["Artillery"], x: 192},

    {id: "Harvester", front: "cry_havoc/pilgrim/harvester.jpg", prototypes: ["b"], x: 664, y: 21},
    {id: "Harvester ", prototypes: ["Harvester"], x: 672},
    {id: "Harvester  ", prototypes: ["Harvester"], x: 680},
    {id: "Power Orb", front: "cry_havoc/pilgrim/power_orb.jpg", prototypes: ["b"], x: 715, y: 21},
    {id: "Power Orb ", prototypes: ["Power Orb"], x: 723},
    {id: "Power Orb  ", prototypes: ["Power Orb"], x: 731},
    {id: "Extractor", front: "cry_havoc/pilgrim/extractor.jpg", prototypes: ["b"], x: 766, y: 21},
    {id: "Extractor ", prototypes: ["Extractor"], x: 774},
    {id: "Extractor  ", prototypes: ["Extractor"], x: 782},

    {id: "Orbital Sniper", front: "cry_havoc/machine/orbital_sniper.jpg", prototypes: ["b"], x: 74, y: 846},
    {id: "Orbital Sniper ", prototypes: ["Orbital Sniper"], x: 82},
    {id: "Orbital Sniper  ", prototypes: ["Orbital Sniper"], x: 90},
    {id: "Bunker", front: "cry_havoc/machine/bunker.jpg", prototypes: ["b"], x: 125, y: 846},
    {id: "Bunker ", prototypes: ["Bunker"], x: 133},
    {id: "Bunker  ", prototypes: ["Bunker"], x: 141},
    {id: "Shred Drones", front: "cry_havoc/machine/shred_drones.jpg", prototypes: ["b"], x: 176, y: 846},
    {id: "Shred Drones ", prototypes: ["Shred Drones"], x: 184},
    {id: "Shred Drones  ", prototypes: ["Shred Drones"], x: 192},
    {id: "Matrix", front: "cry_havoc/machine/matrix.jpg", prototypes: ["b"], x: 227, y: 846},
    {id: "Matrix ", prototypes: ["Matrix"], x: 235},
    {id: "Matrix  ", prototypes: ["Matrix"], x: 243},
    {id: "Factory", front: "cry_havoc/machine/factory.jpg", prototypes: ["b"], x: 278, y: 846},
    {id: "Factory ", prototypes: ["Factory"], x: 286},
    {id: "Factory  ", prototypes: ["Factory"], x: 294},

    {id: "Tunnels", front: "cry_havoc/trog/tunnels.jpg", prototypes: ["b"], x: 664, y: 846},
    {id: "Tunnels ", prototypes: ["Tunnels"], x: 672},
    {id: "Tunnels  ", prototypes: ["Tunnels"], x: 680},
    {id: "Tunnels   ", prototypes: ["Tunnels"], x: 207, y: 489},
    {id: "Tunnels    ", prototypes: ["Tunnels"], x: 611, y: 736},
    {id: "Tunnels     ", prototypes: ["Tunnels"], x: 618, y: 217},
    {id: "Tunnels      ", prototypes: ["Tunnels"], x: 431, y: 469},
    {id: "Brooding Pool", front: "cry_havoc/trog/brooding_pool.jpg", prototypes: ["b"], x: 715, y: 846},
    {id: "Brooding Pool ", prototypes: ["Brooding Pool"], x: 723},
    {id: "Brooding Pool  ", prototypes: ["Brooding Pool"], x: 731},
    {id: "Trap", front: "cry_havoc/trog/trap.jpg", prototypes: ["b"], x: 766, y: 846},
    {id: "Trap ", prototypes: ["Trap"], x: 774},
    {id: "Trap  ", prototypes: ["Trap"], x: 782},

    {id: "Human Soldier 1", front: "cry_havoc/human/soldier.png", x: 476, y: 9, width: 18, height: 18},
    {id: "Human Soldier 2", prototypes: ["Human Soldier 1"], y: 27},
    {id: "Human Soldier 3", prototypes: ["Human Soldier 1"], y: 45},
    {id: "Human Soldier 4", prototypes: ["Human Soldier 1"], y: 63},
    {id: "Human Soldier 5", prototypes: ["Human Soldier 1"], x: 494},
    {id: "Human Soldier 6", prototypes: ["Human Soldier 2"], x: 494},
    {id: "Human Soldier 7", prototypes: ["Human Soldier 3"], x: 494},
    {id: "Human Soldier 8", prototypes: ["Human Soldier 4"], x: 494},
    {id: "Human Soldier 9", prototypes: ["Human Soldier 1"], x: 512},
    {id: "Human Soldier 10", prototypes: ["Human Soldier 2"], x: 512},
    {id: "Human Soldier 11", prototypes: ["Human Soldier 3"], x: 512},
    {id: "Human Soldier 12", prototypes: ["Human Soldier 4"], x: 512},

    {id: "Pilgrim Soldier 1", front: "cry_havoc/pilgrim/soldier.png", x: 1066, y: 9, width: 18, height: 18},
    {id: "Pilgrim Soldier 2", prototypes: ["Pilgrim Soldier 1"], y: 27},
    {id: "Pilgrim Soldier 3", prototypes: ["Pilgrim Soldier 1"], y: 45},
    {id: "Pilgrim Soldier 4", prototypes: ["Pilgrim Soldier 1"], y: 63},
    {id: "Pilgrim Soldier 5", prototypes: ["Pilgrim Soldier 1"], x: 1084},
    {id: "Pilgrim Soldier 6", prototypes: ["Pilgrim Soldier 2"], x: 1084},
    {id: "Pilgrim Soldier 7", prototypes: ["Pilgrim Soldier 3"], x: 1084},
    {id: "Pilgrim Soldier 8", prototypes: ["Pilgrim Soldier 4"], x: 1084},
    {id: "Pilgrim Soldier 9", prototypes: ["Pilgrim Soldier 1"], x: 1102},
    {id: "Pilgrim Soldier 10", prototypes: ["Pilgrim Soldier 2"], x: 1102},
    {id: "Pilgrim Soldier 11", prototypes: ["Pilgrim Soldier 3"], x: 1102},
    {id: "Pilgrim Soldier 12", prototypes: ["Pilgrim Soldier 4"], x: 1102},

    {id: "Machine Soldier 1", front: "cry_havoc/machine/soldier.png", x: 476, y: 834, width: 18, height: 18},
    {id: "Machine Soldier 2", prototypes: ["Machine Soldier 1"], y: 852},
    {id: "Machine Soldier 3", prototypes: ["Machine Soldier 1"], y: 870},
    {id: "Machine Soldier 4", prototypes: ["Machine Soldier 1"], y: 888},
    {id: "Machine Soldier 5", prototypes: ["Machine Soldier 1"], x: 494},
    {id: "Machine Soldier 6", prototypes: ["Machine Soldier 2"], x: 494},
    {id: "Machine Soldier 7", prototypes: ["Machine Soldier 3"], x: 494},
    {id: "Machine Soldier 8", prototypes: ["Machine Soldier 4"], x: 494},
    {id: "Machine Soldier 9", prototypes: ["Machine Soldier 1"], x: 512},
    {id: "Machine Soldier 10", prototypes: ["Machine Soldier 2"], x: 512},
    {id: "Machine Soldier 11", prototypes: ["Machine Soldier 3"], x: 512},
    {id: "Machine Soldier 12", prototypes: ["Machine Soldier 4"], x: 512},

    {id: "Trog Soldier 1", front: "cry_havoc/trog/soldier.png", x: 1048, y: 834, width: 18, height: 18},
    {id: "Trog Soldier 2", prototypes: ["Trog Soldier 1"], y: 852},
    {id: "Trog Soldier 3", prototypes: ["Trog Soldier 1"], y: 870},
    {id: "Trog Soldier 4", prototypes: ["Trog Soldier 1"], y: 888},
    {id: "Trog Soldier 5", prototypes: ["Trog Soldier 1"], x: 1066},
    {id: "Trog Soldier 6", prototypes: ["Trog Soldier 2"], x: 1066},
    {id: "Trog Soldier 7", prototypes: ["Trog Soldier 3"], x: 1066},
    {id: "Trog Soldier 8", prototypes: ["Trog Soldier 4"], x: 1066},
    {id: "Trog Soldier 9", prototypes: ["Trog Soldier 1"], x: 1084},
    {id: "Trog Soldier 10", prototypes: ["Trog Soldier 2"], x: 1084},
    {id: "Trog Soldier 11", prototypes: ["Trog Soldier 3"], x: 1084},
    {id: "Trog Soldier 12", prototypes: ["Trog Soldier 4"], x: 1084},
    {id: "Trog Soldier 13", prototypes: ["Trog Soldier 1"], x: 1102},
    {id: "Trog Soldier 14", prototypes: ["Trog Soldier 2"], x: 1102},
    {id: "Trog Soldier 15", prototypes: ["Trog Soldier 3"], x: 1102},
    {id: "Trog Soldier 16", prototypes: ["Trog Soldier 4"], x: 1102},

    {id: "Jungle Air Support", prototypes: ["jt"], front: "cry_havoc/tactics/j_air_support.jpg"},
    {id: "Jungle Air Support ", prototypes: ["Jungle Air Support"]},
    {id: "Jungle Distraction", prototypes: ["jt"], front: "cry_havoc/tactics/j_distraction.jpg"},
    {id: "Jungle Outflank", prototypes: ["jt"], front: "cry_havoc/tactics/j_outflank.jpg"},
    {id: "Jungle Outflank ", prototypes: ["Jungle Outflank"]},
    {id: "Jungle Regroup", prototypes: ["jt"], front: "cry_havoc/tactics/j_regroup.jpg"},
    {id: "Jungle Regroup ", prototypes: ["Jungle Regroup"]},
    {id: "Jungle Shifted Priorities", prototypes: ["jt"], front: "cry_havoc/tactics/j_shifted_priorities.jpg"},

    {id: "Desert Air Support", prototypes: ["dt"], front: "cry_havoc/tactics/d_air_support.jpg"},
    {id: "Desert Air Support ", prototypes: ["Desert Air Support"]},
    {id: "Desert Distraction", prototypes: ["dt"], front: "cry_havoc/tactics/d_distraction.jpg"},
    {id: "Desert Outflank", prototypes: ["dt"], front: "cry_havoc/tactics/d_outflank.jpg"},
    {id: "Desert Outflank ", prototypes: ["Desert Outflank"]},
    {id: "Desert Regroup", prototypes: ["dt"], front: "cry_havoc/tactics/d_regroup.jpg"},
    {id: "Desert Regroup ", prototypes: ["Desert Regroup"]},
    {id: "Desert Shifted Priorities", prototypes: ["dt"], front: "cry_havoc/tactics/d_shifted_priorities.jpg"},

    {id: "Mountain Air Support", prototypes: ["mt"], front: "cry_havoc/tactics/m_air_support.jpg"},
    {id: "Mountain Air Support ", prototypes: ["Mountain Air Support"]},
    {id: "Mountain Distraction", prototypes: ["mt"], front: "cry_havoc/tactics/m_distraction.jpg"},
    {id: "Mountain Outflank", prototypes: ["mt"], front: "cry_havoc/tactics/m_outflank.jpg"},
    {id: "Mountain Outflank ", prototypes: ["Mountain Outflank"]},
    {id: "Mountain Regroup", prototypes: ["mt"], front: "cry_havoc/tactics/m_regroup.jpg"},
    {id: "Mountain Regroup ", prototypes: ["Mountain Regroup"]},
    {id: "Mountain Shifted Priorities", prototypes: ["mt"], front: "cry_havoc/tactics/m_shifted_priorities.jpg"},

    {id: "Ocean Air Support", prototypes: ["ot"], front: "cry_havoc/tactics/o_air_support.jpg"},
    {id: "Ocean Air Support ", prototypes: ["Ocean Air Support"]},
    {id: "Ocean Distraction", prototypes: ["ot"], front: "cry_havoc/tactics/o_distraction.jpg"},
    {id: "Ocean Outflank", prototypes: ["ot"], front: "cry_havoc/tactics/o_outflank.jpg"},
    {id: "Ocean Outflank ", prototypes: ["Ocean Outflank"]},
    {id: "Ocean Regroup", prototypes: ["ot"], front: "cry_havoc/tactics/o_regroup.jpg"},
    {id: "Ocean Regroup ", prototypes: ["Ocean Regroup"]},
    {id: "Ocean Shifted Priorities", prototypes: ["ot"], front: "cry_havoc/tactics/o_shifted_priorities.jpg"},

    {id: "Air Cavalry", prototypes: ["ht"], front: "cry_havoc/human/air_cavalry.jpg"},
    {id: "Air Cavalry ", prototypes: ["Air Cavalry"]},
    {id: "Drop Troopers", prototypes: ["ht"], front: "cry_havoc/human/drop_troopers.jpg"},
    {id: "Drop Troopers ", prototypes: ["Drop Troopers"]},
    {id: "Drop Troopers  ", prototypes: ["Drop Troopers"]},
    {id: "Engineering Team", prototypes: ["ht"], front: "cry_havoc/human/engineering_team.jpg"},
    {id: "Expeditionary Force", prototypes: ["ht"], front: "cry_havoc/human/expeditionary_force.jpg"},
    {id: "Recon Team", prototypes: ["ht"], front: "cry_havoc/human/recon_team.jpg"},

    {id: "Constructor", prototypes: ["mat"], front: "cry_havoc/machine/constructor.jpg"},
    {id: "Constructor ", prototypes: ["Constructor"]},
    {id: "Extractors", prototypes: ["mat"], front: "cry_havoc/machine/extractors.jpg"},
    {id: "Fortified Factory", prototypes: ["mat"], front: "cry_havoc/machine/fortified_factory.jpg"},
    {id: "Observers", prototypes: ["mat"], front: "cry_havoc/machine/observers.jpg"},
    {id: "Pneumatic Tube", prototypes: ["mat"], front: "cry_havoc/machine/pneumatic_tube.jpg"},
    {id: "Pneumatic Tube ", prototypes: ["Pneumatic Tube"]},
    {id: "Pneumatic Tube  ", prototypes: ["Pneumatic Tube"]},

    {id: "Deploy Holos", prototypes: ["pt"], front: "cry_havoc/pilgrim/deploy_holos.jpg"},
    {id: "Deploy Holos ", prototypes: ["Deploy Holos"]},
    {id: "Deploy Holos  ", prototypes: ["Deploy Holos"]},
    {id: "Phase Shift", prototypes: ["pt"], front: "cry_havoc/pilgrim/phase_shift.jpg"},
    {id: "Pulse Wave", prototypes: ["pt"], front: "cry_havoc/pilgrim/pulse_wave.jpg"},
    {id: "Telepathic Link", prototypes: ["pt"], front: "cry_havoc/pilgrim/telepathic_link.jpg"},
    {id: "Telepathic Link ", prototypes: ["Telepathic Link"]},
    {id: "Temple", prototypes: ["pt"], front: "cry_havoc/pilgrim/temple.jpg"},

    {id: "Ancient Caves", prototypes: ["tt"], front: "cry_havoc/trog/ancient_caves.jpg"},
    {id: "Ancient Caves ", prototypes: ["Ancient Caves"]},
    {id: "Ancient Caves  ", prototypes: ["Ancient Caves"]},
    {id: "Breeding Tower", prototypes: ["tt"], front: "cry_havoc/trog/breeding_tower.jpg"},
    {id: "Breeding Tower ", prototypes: ["Breeding Tower"]},
    {id: "Ripper Squad", prototypes: ["tt"], front: "cry_havoc/trog/ripper_squad.jpg"},
    {id: "Scouts", prototypes: ["tt"], front: "cry_havoc/trog/scouts.jpg"},
    {id: "Warrior Clan", prototypes: ["tt"], front: "cry_havoc/trog/warrior_clan.jpg"},

    {id: "Occupation", prototypes: ["hs"], front: "cry_havoc/human/occupation.jpg"},
    {id: "Recon Forces", prototypes: ["hs"], front: "cry_havoc/human/recon_forces.jpg"},
    {id: "Scouting", prototypes: ["hs"], front: "cry_havoc/human/scouting.jpg"},
    {id: "Seek and Destroy", prototypes: ["hs"], front: "cry_havoc/human/seek_and_destroy.jpg"},
    {id: "Veteran Forces", prototypes: ["hs"], front: "cry_havoc/human/veteran_forces.jpg"},
  
    {id: "Examination", prototypes: ["ps"], front: "cry_havoc/pilgrim/examination.jpg"},
    {id: "Data Extraction", prototypes: ["ps"], front: "cry_havoc/pilgrim/data_extraction.jpg"},
    {id: "Power Extraction", prototypes: ["ps"], front: "cry_havoc/pilgrim/power_extraction.jpg"},
    {id: "Sow the Seeds", prototypes: ["ps"], front: "cry_havoc/pilgrim/sow_the_seeds.jpg"},
    {id: "Teleportation", prototypes: ["ps"], front: "cry_havoc/pilgrim/teleportation.jpg"},

    {id: "Moving City", prototypes: ["ms"], front: "cry_havoc/machine/moving_city.jpg"},
    {id: "Firepower", prototypes: ["ms"], front: "cry_havoc/machine/firepower.jpg"},
    {id: "Software Update", prototypes: ["ms"], front: "cry_havoc/machine/software_update.jpg"},
    {id: "Terrain Advantage", prototypes: ["ms"], front: "cry_havoc/machine/terrain_advantage.jpg"},
    {id: "Transform", prototypes: ["ms"], front: "cry_havoc/machine/transform.jpg"},

    {id: "Disappear", prototypes: ["ts"], front: "cry_havoc/trog/disappear.jpg"},
    {id: "Adaptation", prototypes: ["ts"], front: "cry_havoc/trog/adaptation.jpg"},
    {id: "Battle Cry", prototypes: ["ts"], front: "cry_havoc/trog/battle_cry.jpg"},
    {id: "Native Forces", prototypes: ["ts"], front: "cry_havoc/trog/native_forces.jpg"},
    {id: "Shadows", prototypes: ["ts"], front: "cry_havoc/trog/shadows.jpg"},

    {id: "ev", prototype: true, back: "cry_havoc/token/event.jpg", x: 1070, y: 694, width: 41, height: 34},
    {id: "exp", prototype: true, back: "cry_havoc/token/explore.jpg", x: 1070, y: 736, width: 25, height: 25},
    {id: "wp", prototype: true, back: "cry_havoc/token/party.jpg", x: 1070, y: 771, width: 25, height: 25},
    {id: "nest", prototype: true, back: "cry_havoc/token/nest.jpg", x: 1070, y: 806, width: 25, height: 25},

    //{id: "Exploration Cards", prototypes: ["exp"], front: "cry_havoc/token/explore_cards.jpg"},
    {id: "Exploration Crystals", prototypes: ["exp"], front: "cry_havoc/token/explore_crystals.jpg"},
    {id: "Exploration Crystals ", prototypes: ["Exploration Crystals"], x: 1071},
    {id: "Exploration Crystals  ", prototypes: ["Exploration Crystals"], x: 1072},
    {id: "Exploration Crystals   ", prototypes: ["Exploration Crystals"], x: 1073},
    {id: "Exploration Soldiers", prototypes: ["exp"], front: "cry_havoc/token/explore_soldiers.jpg", x: 1074},
    {id: "Exploration Soldiers ", prototypes: ["Exploration Soldiers"], x: 1075},
    {id: "Exploration Soldiers  ", prototypes: ["Exploration Soldiers"], x: 1076},
    {id: "Exploration Terrain", prototypes: ["exp"], front: "cry_havoc/token/explore_terrain.jpg", x: 1077},
    {id: "Exploration Terrain ", prototypes: ["Exploration Terrain"], x: 1078},
    {id: "Exploration Terrain  ", prototypes: ["Exploration Terrain"], x: 1079},
    {id: "Exploration Terrain   ", prototypes: ["Exploration Terrain"], x: 1080},
    {id: "Exploration Terrain    ", prototypes: ["Exploration Terrain"], x: 1081},

    {id: "War Party 1", prototypes: ["wp"], front: "cry_havoc/token/party_1.jpg"},
    {id: "War Party 1 ", prototypes: ["War Party 1"], x: 1071},
    {id: "War Party 1  ", prototypes: ["War Party 1"], x: 1072},
    {id: "War Party 1   ", prototypes: ["War Party 1"], x: 1073},
    {id: "War Party 2", prototypes: ["wp"], front: "cry_havoc/token/party_2.jpg", x: 1074},
    {id: "War Party 2 ", prototypes: ["War Party 2"], x: 1075},
    {id: "War Party 2  ", prototypes: ["War Party 2"], x: 1076},
    {id: "War Party 2   ", prototypes: ["War Party 2"], x: 1077},
    {id: "War Party 2    ", prototypes: ["War Party 2"], x: 1078},
    {id: "War Party 2     ", prototypes: ["War Party 2"], x: 1079},
    {id: "War Party 2      ", prototypes: ["War Party 2"], x: 1080},
    {id: "War Party 2       ", prototypes: ["War Party 2"], x: 1081},
    {id: "War Party 2        ", prototypes: ["War Party 2"], x: 1082},
    {id: "War Party 2         ", prototypes: ["War Party 2"], x: 1083},
    {id: "War Party 3", prototypes: ["wp"], front: "cry_havoc/token/party_3.jpg", x: 1084},
    {id: "War Party 3 ", prototypes: ["War Party 3"], x: 1085},
    {id: "War Party 3  ", prototypes: ["War Party 3"], x: 1086},
    {id: "War Party 3   ", prototypes: ["War Party 3"], x: 1087},

    {id: "Nest 2", prototypes: ["nest"], front: "cry_havoc/token/nest_2.jpg"},
    {id: "Nest 2 ", prototypes: ["Nest 2"], x: 1071},
    {id: "Nest 2  ", prototypes: ["Nest 2"], x: 1072},
    {id: "Nest 2   ", prototypes: ["Nest 2"], x: 1073},
    {id: "Nest 3", prototypes: ["nest"], front: "cry_havoc/token/nest_3.jpg", x: 1074},
    {id: "Nest 3 ", prototypes: ["Nest 3"], x: 1075},
    {id: "Nest 3  ", prototypes: ["Nest 3"], x: 1076},
    {id: "Nest 3   ", prototypes: ["Nest 3"], x: 1077},
    {id: "Nest 3    ", prototypes: ["Nest 3"], x: 1078},
    {id: "Nest 3     ", prototypes: ["Nest 3"], x: 1079},
    {id: "Nest 4", prototypes: ["nest"], front: "cry_havoc/token/nest_4.jpg", x: 1080},
    {id: "Nest 4 ", prototypes: ["Nest 4"], x: 1081},

    {id: "Event Card", prototypes: ["ev"], front: "cry_havoc/token/event_card.jpg"},
    {id: "Event Crystal", prototypes: ["ev"], front: "cry_havoc/token/event_crystal.jpg", x: 1071},
    {id: "Event -Soldier", prototypes: ["ev"], front: "cry_havoc/token/event_lose_soldier.jpg", x: 1072},
    {id: "Event -Crystals", prototypes: ["ev"], front: "cry_havoc/token/event_remove_crystals.jpg", x: 1073},
    {id: "Event Soldier", prototypes: ["ev"], front: "cry_havoc/token/event_soldier.jpg", x: 1074},
    {id: "Event Terrain", prototypes: ["ev"], front: "cry_havoc/token/event_terrain.jpg", x: 1075},
  ],
};
