module.exports = {
  name: "Forbidden Stars",

  roles: [
    { id: "Chaos", name: "Chaos", },
    { id: "Eldar", name: "Eldar", },
    { id: "Orks", name: "Orks", },
    { id: "Space Marines", name: "Space Marines", },
  ],
  objects: [

    {id: "Map", backgroundColor: "#00a000", locked:true, x: 213, y: 214, width: 800, height: 600, snapZones: [{cellWidth:200, cellHeight:200}], },

    {id: "card", prototype: true, width: 70, height: 98,},

    {id: "handScreen", prototype: true, locked: true, width: 450, height: 98, hideFaces: ["front"], snapZones: [{}], },

    {id: "obj-chaos", prototype: true, width: 28, height: 22, front: "forbidden_stars/token/obj-chaos.jpg", },
    {id: "obj-eldar", prototype: true, width: 28, height: 22, front: "forbidden_stars/token/obj-eldar.jpg", },
    {id: "obj-orks", prototype: true, width: 28, height: 22, front: "forbidden_stars/token/obj-orks.jpg", },
    {id: "obj-sm", prototype: true, width: 28, height: 22, front: "forbidden_stars/token/obj-sm.jpg", },

    {id: "player area", prototype: true, width: 600, height: 201, locked: true, front: "forbidden_stars/player_area.png", snapZones: [{x: 0, y: 0, width: 70, height: 98}, {x: 75, y: 0, width: 70, height: 98}, {x: 150, y: 0, width: 70, height: 98}, {x: 455, y: 103, width: 70, height: 98}, {x: 530, y: 103, width: 70, height: 98}], },

    {prototypes: ["player area"], x: 8, y: 8, },
    {prototypes: ["player area"], x: 658, y: 8, },
    {prototypes: ["player area"], x: 8, y: 826, },
    {prototypes: ["player area"], x: 658, y: 826, },

    // Chaos

    { id: "Blight of Nurgle", prototypes: ["card"], x: 8, y: 8, front: "forbidden_stars/event/chaos_blight_of_nurgle.jpg", back: "forbidden_stars/event/chaos_back.jpg",},
    { id: "Incantation of Tzeentch", prototypes: ["Blight of Nurgle"], front: "forbidden_stars/event/chaos_incantation_of_tzeentch.jpg", },
    { id: "Prayer to the Dark Gods", prototypes: ["Blight of Nurgle"], front: "forbidden_stars/event/chaos_prayer_to_the_dark_gods.jpg", },
    { id: "Prophets and Signs", prototypes: ["Blight of Nurgle"], front: "forbidden_stars/event/chaos_prophets_and_signs.jpg", },
    { id: "Seduced By Chaos", prototypes: ["Blight of Nurgle"], front: "forbidden_stars/event/chaos_seduced_by_chaos.jpg", },
    { id: "Spoils of War", prototypes: ["Blight of Nurgle"], front: "forbidden_stars/event/chaos_spoils_of_war.jpg", },
    { id: "Through the Warp", prototypes: ["Blight of Nurgle"], front: "forbidden_stars/event/chaos_through_the_warp.jpg", },
    { id: "Touched by the Warp", prototypes: ["Blight of Nurgle"], front: "forbidden_stars/event/chaos_touched_by_the_warp.jpg", },

    { id: "Complete Destruction", prototypes: ["card"], x: 83, y: 8, front: "forbidden_stars/upgrade/chaos_complete_destruction.jpg", },
    { id: "Dread Ritual", prototypes: ["Complete Destruction"], front: "forbidden_stars/upgrade/chaos_dread_ritual.jpg", },
    { id: "Favour of the Dark Gods", prototypes: ["Complete Destruction"], front: "forbidden_stars/upgrade/chaos_favour_of_the_dark_gods.jpg", },
    { id: "Fear from Above", prototypes: ["Complete Destruction"], front: "forbidden_stars/upgrade/chaos_fear_from_above.jpg", },
    { id: "From the Warp", prototypes: ["Complete Destruction"], front: "forbidden_stars/upgrade/chaos_from_the_warp.jpg", },

    { id: "Chaos United", prototypes: ["card"], x: 158, y: 8, front: "forbidden_stars/combat/chaos_chaos_united.jpg", back: "forbidden_stars/combat/chaos_back.jpg",},
    { id: "Chaos United ", prototypes: ["Chaos United"], },
    { id: "Chaos Victorious", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_chaos_victorious.jpg", },
    { id: "Chaos Victorious ", prototypes: ["Chaos Victorious"], },
    { id: "Daemonic Resilience", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_daemonic_resilience.jpg", },
    { id: "Daemonic Resilience ", prototypes: ["Daemonic Resilience"], },
    { id: "Death and Despair", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_death_and_despair.jpg", },
    { id: "Death and Despair ", prototypes: ["Death and Despair"], },
    { id: "Inhuman Strength", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_inhuman_strength.jpg", },
    { id: "Inhuman Strength ", prototypes: ["Inhuman Strength"], },
    { id: "Mark of Khorne", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_mark_of_khorne.jpg", },
    { id: "Mark of Khorne ", prototypes: ["Mark of Khorne"], },
    { id: "Mark of Nurgle", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_mark_of_nurgle.jpg", },
    { id: "Mark of Nurgle ", prototypes: ["Mark of Nurgle"], },
    { id: "Mark of Slaanesh", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_mark_of_slaanesh.jpg", },
    { id: "Mark of Slaanesh ", prototypes: ["Mark of Slaanesh"], },
    { id: "Mark of Tzeentch", prototypes: ["Chaos United"], front: "forbidden_stars/combat/chaos_mark_of_tzeentch.jpg", },
    { id: "Mark of Tzeentch ", prototypes: ["Mark of Tzeentch"], },

    {id: "Chaos Reference", x: 233, y: 8, width: 70, height: 100, immobile: true, front: "forbidden_stars/chaos-ref.jpg", },
    {id: "Chaos Materiel", x: 234, y: 9, width: 32, height: 32, immobile: true, front: "forbidden_stars/chaos-mat.png", hasLabel: true, label: 6, labelColor: ["#36b450"], },

    { prototypes: ["handScreen"], x: 8, y: 111, visionWhitelist: ["Chaos"], backgroundColor: "rgba(153,18,8,alpha)", labelPlayerName: "Chaos", },

    { id: "Dark Faith", prototypes: ["card"], x: 463, y: 111, front: "forbidden_stars/combat/chaos_dark_faith.jpg", back: "forbidden_stars/combat/chaos_back.jpg", },
    { id: "Dark Faith ", prototypes: ["Dark Faith"], },
    { id: "Foul Worship", prototypes: ["Dark Faith"], front: "forbidden_stars/combat/chaos_foul_worship.jpg", },
    { id: "Foul Worship ", prototypes: ["Foul Worship"], },
    { id: "Impure Zeal", prototypes: ["Dark Faith"], front: "forbidden_stars/combat/chaos_impure_zeal.jpg", },
    { id: "Impure Zeal ", prototypes: ["Impure Zeal"], },
    { id: "Khorne's Rage", prototypes: ["Dark Faith"], front: "forbidden_stars/combat/chaos_khornes_rage.jpg", },
    { id: "Khorne's Rage ", prototypes: ["Khorne's Rage"], },
    { id: "Lure of Chaos", prototypes: ["Dark Faith"], front: "forbidden_stars/combat/chaos_lure_of_chaos.jpg", },
    { id: "Lure of Chaos ", prototypes: ["Lure of Chaos"], },

    {id: "Cultist 1", x: 308, y: 8, width: 14, height: 14, front: "forbidden_stars/unit/chaos-1.png", back: "forbidden_stars/unit/chaos-1r.png", },
    {id: "Cultist 2", prototypes: ["Cultist 1"], x: 311, },
    {id: "Cultist 3", prototypes: ["Cultist 1"], x: 314, },
    {id: "Cultist 4", prototypes: ["Cultist 1"], x: 317, },
    {id: "Cultist 5", prototypes: ["Cultist 1"], x: 320, },
    {id: "Cultist 6", prototypes: ["Cultist 1"], x: 323, },
    {id: "Cultist 7", prototypes: ["Cultist 1"], x: 326, },
    {id: "Cultist 8", prototypes: ["Cultist 1"], x: 582, },
    {id: "Cultist 9", prototypes: ["Cultist 1"], x: 585, },
    {id: "Iconoclast 1", x: 308, y: 27, width: 24, height: 20, front: "forbidden_stars/unit/chaos-2.png", back: "forbidden_stars/unit/chaos-2r.png", },
    {id: "Iconoclast 2", prototypes: ["Iconoclast 1"], x: 311, },
    {id: "Iconoclast 3", prototypes: ["Iconoclast 1"], x: 575, },
    {id: "Chaos Space Marine 1", x: 308, y: 52, width: 21, height: 21, front: "forbidden_stars/unit/chaos-3.png", back: "forbidden_stars/unit/chaos-3r.png", },
    {id: "Chaos Space Marine 2", prototypes: ["Chaos Space Marine 1"], x: 311, },
    {id: "Chaos Space Marine 3", prototypes: ["Chaos Space Marine 1"], x: 314, },
    {id: "Chaos Space Marine 4", prototypes: ["Chaos Space Marine 1"], x: 317, },
    {id: "Chaos Space Marine 5", prototypes: ["Chaos Space Marine 1"], x: 575, },
    {id: "Chaos Space Marine 6", prototypes: ["Chaos Space Marine 1"], x: 578, },
    {id: "Helbrute 1", x: 308, y: 78, width: 29, height: 29, front: "forbidden_stars/unit/chaos-4.png", back: "forbidden_stars/unit/chaos-4r.png", },
    {id: "Helbrute 2", prototypes: ["Helbrute 1"], x: 311, },
    {id: "Helbrute 3", prototypes: ["Helbrute 1"], x: 314, },
    {id: "Grand Cruiser 1", x: 343, y: 8, width: 40, height: 32, front: "forbidden_stars/unit/chaos-5.png", back: "forbidden_stars/unit/chaos-5r.png", },
    {id: "Grand Cruiser 2", prototypes: ["Grand Cruiser 1"], x: 346, },
    {id: "Grand Cruiser 3", prototypes: ["Grand Cruiser 1"], x: 349, },
    {id: "Chaos Titan 1", x: 343, y: 45, width: 38, height: 38, front: "forbidden_stars/unit/chaos-6.png", back: "forbidden_stars/unit/chaos-6r.png", },
    {id: "Chaos Titan 2", prototypes: ["Chaos Titan 1"], x: 346, },
    {id: "Chaos Titan 3", prototypes: ["Chaos Titan 1"], x: 349, },

    {id: "Chaos Advance", x: 400, y: 111, width: 38, height: 33, front: "forbidden_stars/order/advance.png", back: "forbidden_stars/order/chaos.png", },
    {id: "Chaos Advance ", prototypes: ["Chaos Advance"], x: 420, },
    {id: "Chaos Deploy", x: 400, y: 132, width: 38, height: 33, front: "forbidden_stars/order/deploy.png", back: "forbidden_stars/order/chaos.png", },
    {id: "Chaos Deploy ", prototypes: ["Chaos Deploy"], x: 420, },
    {id: "Chaos Dominate", x: 400, y: 153, width: 38, height: 33, front: "forbidden_stars/order/dominate.png", back: "forbidden_stars/order/chaos.png", },
    {id: "Chaos Dominate ", prototypes: ["Chaos Dominate"], x: 420, },
    {id: "Chaos Strategize", x: 400, y: 174, width: 38, height: 33, front: "forbidden_stars/order/strategize.png", back: "forbidden_stars/order/chaos.png", },
    {id: "Chaos Strategize ", prototypes: ["Chaos Strategize"], x: 420, },

    {id: "Eldar Objective 1", prototypes: ["obj-eldar"], x: 500, y: 12, },
    {id: "Eldar Objective 2", prototypes: ["obj-eldar"], x: 533, y: 12, },

    {id: "Orks Objective 1", prototypes: ["obj-orks"], x: 500, y: 46, },
    {id: "Orks Objective 2", prototypes: ["obj-orks"], x: 533, y: 46, },

    {id: "Space Marines Objective 1", prototypes: ["obj-sm"], x: 500, y: 80, },
    {id: "Space Marines Objective 2", prototypes: ["obj-sm"], x: 533, y: 80, },

    // Eldar

    { id: "Exodite Colony", prototypes: ["card"], x: 658, y: 8, front: "forbidden_stars/event/eldar_exodite_colony.jpg", back: "forbidden_stars/event/eldar_back.jpg", },
    { id: "Farsight", prototypes: ["Exodite Colony"], front: "forbidden_stars/event/eldar_farsight.jpg", },
    { id: "Legacy of Vaul", prototypes: ["Exodite Colony"], front: "forbidden_stars/event/eldar_legacy_of_vaul.jpg", },
    { id: "Outcasts Returned", prototypes: ["Exodite Colony"], front: "forbidden_stars/event/eldar_outcasts_returned.jpg", },
    { id: "Outmanoeuvre", prototypes: ["Exodite Colony"], front: "forbidden_stars/event/eldar_outmanoeuvre.jpg", },
    { id: "Path of the Warrior", prototypes: ["Exodite Colony"], front: "forbidden_stars/event/eldar_path_of_the_warrior.jpg", },
    { id: "Vicious Raids", prototypes: ["Exodite Colony"], front: "forbidden_stars/event/eldar_vicious_raids.jpg", },
    { id: "Warp Gate", prototypes: ["Exodite Colony"], front: "forbidden_stars/event/eldar_warp_gate.jpg", },

    { id: "Corsair Raid", prototypes: ["card"], x: 733, y: 8, front: "forbidden_stars/upgrade/eldar_corsair_raid.jpg", },
    { id: "Farseers", prototypes: ["Corsair Raid"], front: "forbidden_stars/upgrade/eldar_farseers.jpg", },
    { id: "Strafing Run", prototypes: ["Corsair Raid"], front: "forbidden_stars/upgrade/eldar_strafing_run.jpg", },
    { id: "Tactical Strikes", prototypes: ["Corsair Raid"], front: "forbidden_stars/upgrade/eldar_tactical_strikes.jpg", },
    { id: "Wraithbone Singers", prototypes: ["Corsair Raid"], front: "forbidden_stars/upgrade/eldar_wraithbone_singers.jpg", },

    { id: "Fire Dragon's Vengeance", prototypes: ["card"], x: 808, y: 8, front: "forbidden_stars/combat/eldar_fire_dragons_vengeance.jpg", back: "forbidden_stars/combat/eldar_back.jpg", },
    { id: "Fire Dragon's Vengeance ", prototypes: ["Fire Dragon's Vengeance"], },
    { id: "Fire Prism", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_fire_prism.jpg", },
    { id: "Fire Prism ", prototypes: ["Fire Prism"], },
    { id: "Holofield Emitter", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_holofield_emitter.jpg", },
    { id: "Holofield Emitter ", prototypes: ["Holofield Emitter"], },
    { id: "Psychic Lance", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_psychic_lance.jpg", },
    { id: "Psychic Lance ", prototypes: ["Psychic Lance"], },
    { id: "Spiritseer's Guidance", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_spiritseers_guidance.jpg", },
    { id: "Spiritseer's Guidance ", prototypes: ["Spiritseer's Guidance"], },
    { id: "Swooping Hawks", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_swooping_hawks.jpg", },
    { id: "Swooping Hawks ", prototypes: ["Swooping Hawks"], },
    { id: "Wave Serpent", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_wave_serpent.jpg", },
    { id: "Wave Serpent ", prototypes: ["Wave Serpent"], },
    { id: "Wraithguard Advance", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_wraithguard_advance.jpg", },
    { id: "Wraithguard Advance ", prototypes: ["Wraithguard Advance"], },
    { id: "Wraithguard Support", prototypes: ["Fire Dragon's Vengeance"], front: "forbidden_stars/combat/eldar_wraithguard_support.jpg", },
    { id: "Wraithguard Support ", prototypes: ["Wraithguard Support"], },

    {id: "Eldar Reference", x: 883, y: 8, width: 70, height: 100, immobile: true, front: "forbidden_stars/eldar-ref.jpg", },
    {id: "Eldar Materiel", x: 884, y: 9, width: 32, height: 32, immobile: true, front: "forbidden_stars/eldar-mat.png", hasLabel: true, label: 6, labelColor: ["#36b450"], },

    { prototypes: ["handScreen"], x: 658, y: 111, visionWhitelist: ["Eldar"], backgroundColor: "rgba(222,194,15,alpha)", labelPlayerName: "Eldar", },

    { id: "Command of the Autarch", prototypes: ["card"], x: 1113, y: 111, front: "forbidden_stars/combat/eldar_command_of_the_autarch.jpg", back: "forbidden_stars/combat/eldar_back.jpg", },
    { id: "Command of the Autarch ", prototypes: ["Command of the Autarch"], },
    { id: "Hit and Run", prototypes: ["Command of the Autarch"], front: "forbidden_stars/combat/eldar_hit_and_run.jpg", },
    { id: "Hit and Run ", prototypes: ["Hit and Run"], },
    { id: "Howling Banshees", prototypes: ["Command of the Autarch"], front: "forbidden_stars/combat/eldar_howling_banshees.jpg", },
    { id: "Howling Banshees ", prototypes: ["Howling Banshees"], },
    { id: "Ranger Support", prototypes: ["Command of the Autarch"], front: "forbidden_stars/combat/eldar_ranger_support.jpg", },
    { id: "Ranger Support ", prototypes: ["Ranger Support"], },
    { id: "Striking Scorpions", prototypes: ["Command of the Autarch"], front: "forbidden_stars/combat/eldar_striking_scorpions.jpg", },
    { id: "Striking Scorpions ", prototypes: ["Striking Scorpions"], },

    {id: "Aspect Warrior 1", x: 958, y: 8, width: 14, height: 14, front: "forbidden_stars/unit/eldar-1.png", back: "forbidden_stars/unit/eldar-1r.png", },
    {id: "Aspect Warrior 2", prototypes: ["Aspect Warrior 1"], x: 961, },
    {id: "Aspect Warrior 3", prototypes: ["Aspect Warrior 1"], x: 964, },
    {id: "Aspect Warrior 4", prototypes: ["Aspect Warrior 1"], x: 1229, },
    {id: "Aspect Warrior 5", prototypes: ["Aspect Warrior 1"], x: 1232, },
    {id: "Aspect Warrior 6", prototypes: ["Aspect Warrior 1"], x: 1235, },
    {id: "Frigate 1", x: 958, y: 27, width: 24, height: 20, front: "forbidden_stars/unit/eldar-2.png", back: "forbidden_stars/unit/eldar-2r.png", },
    {id: "Frigate 2", prototypes: ["Frigate 1"], x: 961, },
    {id: "Frigate 3", prototypes: ["Frigate 1"], x: 964, },
    {id: "Frigate 4", prototypes: ["Frigate 1"], x: 967, },
    {id: "Frigate 5", prototypes: ["Frigate 1"], x: 1222, },
    {id: "Frigate 6", prototypes: ["Frigate 1"], x: 1225, },
    {id: "Wraithguard 1", x: 958, y: 52, width: 21, height: 21, front: "forbidden_stars/unit/eldar-3.png", back: "forbidden_stars/unit/eldar-3r.png", },
    {id: "Wraithguard 2", prototypes: ["Wraithguard 1"], x: 961, },
    {id: "Wraithguard 3", prototypes: ["Wraithguard 1"], x: 1228, },
    {id: "Falcon 1", x: 958, y: 78, width: 29, height: 29, front: "forbidden_stars/unit/eldar-4.png", back: "forbidden_stars/unit/eldar-4r.png", },
    {id: "Falcon 2", prototypes: ["Falcon 1"], x: 961, },
    {id: "Falcon 3", prototypes: ["Falcon 1"], x: 964, },
    {id: "Void Stalker 1", x: 993, y: 8, width: 40, height: 32, front: "forbidden_stars/unit/eldar-5.png", back: "forbidden_stars/unit/eldar-5r.png", },
    {id: "Void Stalker 2", prototypes: ["Void Stalker 1"], x: 996, },
    {id: "Void Stalker 3", prototypes: ["Void Stalker 1"], x: 999, },
    {id: "Warlock Titan 1", x: 993, y: 45, width: 38, height: 38, front: "forbidden_stars/unit/eldar-6.png", back: "forbidden_stars/unit/eldar-6r.png", },
    {id: "Warlock Titan 2", prototypes: ["Warlock Titan 1"], x: 996, },
    {id: "Warlock Titan 3", prototypes: ["Warlock Titan 1"], x: 999, },

    {id: "Eldar Advance", x: 1050, y: 111, width: 38, height: 33, front: "forbidden_stars/order/advance.png", back: "forbidden_stars/order/eldar.png", },
    {id: "Eldar Advance ", prototypes: ["Eldar Advance"], x: 1070, },
    {id: "Eldar Deploy", x: 1050, y: 132, width: 38, height: 33, front: "forbidden_stars/order/deploy.png", back: "forbidden_stars/order/eldar.png", },
    {id: "Eldar Deploy ", prototypes: ["Eldar Deploy"], x: 1070, },
    {id: "Eldar Dominate", x: 1050, y: 153, width: 38, height: 33, front: "forbidden_stars/order/dominate.png", back: "forbidden_stars/order/eldar.png", },
    {id: "Eldar Dominate ", prototypes: ["Eldar Dominate"], x: 1070, },
    {id: "Eldar Strategize", x: 1050, y: 174, width: 38, height: 33, front: "forbidden_stars/order/strategize.png", back: "forbidden_stars/order/eldar.png", },
    {id: "Eldar Strategize ", prototypes: ["Eldar Strategize"], x: 1070, },

    {id: "Chaos Objective 1", prototypes: ["obj-chaos"], x: 1150, y: 12, },
    {id: "Chaos Objective 2", prototypes: ["obj-chaos"], x: 1183, y: 12, },

    {id: "Orks Objective 3", prototypes: ["obj-orks"], x: 1150, y: 46, },
    {id: "Orks Objective 4", prototypes: ["obj-orks"], x: 1183, y: 46, },

    {id: "Space Marines Objective 3", prototypes: ["obj-sm"], x: 1150, y: 80, },
    {id: "Space Marines Objective 4", prototypes: ["obj-sm"], x: 1183, y: 80, },

    // Orks

    { id: "Gitz Dem!", prototypes: ["card"], x: 8, y: 826, front: "forbidden_stars/event/orks_gitz_dem.jpg", back: "forbidden_stars/event/orks_back.jpg", },
    { id: "How We Getz Here?", prototypes: ["Gitz Dem!"], front: "forbidden_stars/event/orks_how_we_getz_here.jpg", },
    { id: "Letz Get Fightin'", prototypes: ["Gitz Dem!"], front: "forbidden_stars/event/orks_letz_get_fightin.jpg", },
    { id: "Lootin' 'n Stealin'", prototypes: ["Gitz Dem!"], front: "forbidden_stars/event/orks_lootin_n_stealin.jpg", },
    { id: "Moar Boyz!", prototypes: ["Gitz Dem!"], front: "forbidden_stars/event/orks_moar_boyz.jpg", },
    { id: "Mob Up!", prototypes: ["Gitz Dem!"], front: "forbidden_stars/event/orks_mob_up.jpg", },
    { id: "Teer It Down!", prototypes: ["Gitz Dem!"], front: "forbidden_stars/event/orks_teer_it_down.jpg", },
    { id: "Warboss", prototypes: ["Gitz Dem!"], front: "forbidden_stars/event/orks_warboss.jpg", },

    { id: "Lootin", prototypes: ["card"], x: 83, y: 826, front: "forbidden_stars/upgrade/orks_lootin.jpg", },
    { id: "Ork Roks", prototypes: ["Lootin"], front: "forbidden_stars/upgrade/orks_ork_roks.jpg", },
    { id: "Stealin", prototypes: ["Lootin"], front: "forbidden_stars/upgrade/orks_stealin.jpg", },
    { id: "The Green Tide", prototypes: ["Lootin"], front: "forbidden_stars/upgrade/orks_the_green_tide.jpg", },
    { id: "Werk Fasta!", prototypes: ["Lootin"], front: "forbidden_stars/upgrade/orks_werk_fasta.jpg", },

    { id: "Biker Nobz", prototypes: ["card"], x: 158, y: 826, front: "forbidden_stars/combat/orks_biker_nobz.jpg", back: "forbidden_stars/combat/orks_back.jpg", },
    { id: "Biker Nobz ", prototypes: ["Biker Nobz"], },
    { id: "Mega Nobz", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_mega_nobz.jpg", },
    { id: "Mega Nobz ", prototypes: ["Mega Nobz"], },
    { id: "Party Wagon", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_party_wagon.jpg", },
    { id: "Party Wagon ", prototypes: ["Party Wagon"], },
    { id: "Rokkit Wagon", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_rokkit_wagon.jpg", },
    { id: "Rokkit Wagon ", prototypes: ["Rokkit Wagon"], },
    { id: "Sea of Green", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_sea_of_green.jpg", },
    { id: "Sea of Green ", prototypes: ["Sea of Green"], },
    { id: "Smasher Gargant", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_smasher_gargant.jpg", },
    { id: "Smasher Gargant ", prototypes: ["Smasher Gargant"], },
    { id: "Snapper Gargant", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_snapper_gargant.jpg", },
    { id: "Snapper Gargant ", prototypes: ["Snapper Gargant"], },
    { id: "Waaagh!!!!", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_waaagh.jpg", },
    { id: "Waaagh!!!! ", prototypes: ["Waaagh!!!!"], },
    { id: "Weirdboyz", prototypes: ["Biker Nobz"], front: "forbidden_stars/combat/orks_weirdboyz.jpg", },
    { id: "Weirdboyz ", prototypes: ["Weirdboyz"], },

    {id: "Orks Reference", x: 233, y: 826, width: 70, height: 100, immobile: true, front: "forbidden_stars/orks-ref.jpg", },
    {id: "Orks Materiel", x: 234, y: 827, width: 32, height: 32, immobile: true, front: "forbidden_stars/orks-mat.png", hasLabel: true, label: 6, labelColor: ["#36b450"], },

    { prototypes: ["handScreen"], x: 8, y: 929, visionWhitelist: ["Orks"], backgroundColor: "rgba(40,104,33,alpha)", labelPlayerName: "Orks", },

    { id: "'Ard Boyz", prototypes: ["card"], x: 463, y: 929, front: "forbidden_stars/combat/orks_ard_boyz.jpg", back: "forbidden_stars/combat/orks_back.jpg", },
    { id: "'Ard Boyz ", prototypes: ["'Ard Boyz"], },
    { id: "Gretchin", prototypes: ["'Ard Boyz"], front: "forbidden_stars/combat/orks_gretchin.jpg", },
    { id: "Gretchin ", prototypes: ["Gretchin"], },
    { id: "Mek Boyz", prototypes: ["'Ard Boyz"], front: "forbidden_stars/combat/orks_mek_boyz.jpg", },
    { id: "Mek Boyz ", prototypes: ["Mek Boyz"], },
    { id: "Shoota Boyz", prototypes: ["'Ard Boyz"], front: "forbidden_stars/combat/orks_shoota_boyz.jpg", },
    { id: "Shoota Boyz ", prototypes: ["Shoota Boyz"], },
    { id: "Slugga Boyz", prototypes: ["'Ard Boyz"], front: "forbidden_stars/combat/orks_slugga_boyz.jpg", },
    { id: "Slugga Boyz ", prototypes: ["Slugga Boyz"], },

    {id: "Ork Boyz 1", x: 308, y: 826, width: 14, height: 14, front: "forbidden_stars/unit/orks-1.png", back: "forbidden_stars/unit/orks-1r.png", },
    {id: "Ork Boyz 2", prototypes: ["Ork Boyz 1"], x: 311, },
    {id: "Ork Boyz 3", prototypes: ["Ork Boyz 1"], x: 314, },
    {id: "Ork Boyz 4", prototypes: ["Ork Boyz 1"], x: 317, },
    {id: "Ork Boyz 5", prototypes: ["Ork Boyz 1"], x: 320, },
    {id: "Ork Boyz 6", prototypes: ["Ork Boyz 1"], x: 576, },
    {id: "Ork Boyz 7", prototypes: ["Ork Boyz 1"], x: 579, },
    {id: "Ork Boyz 8", prototypes: ["Ork Boyz 1"], x: 582, },
    {id: "Ork Boyz 9", prototypes: ["Ork Boyz 1"], x: 585, },
    {id: "Onslaught 1", x: 308, y: 845, width: 24, height: 20, front: "forbidden_stars/unit/orks-2.png", back: "forbidden_stars/unit/orks-2r.png", },
    {id: "Onslaught 2", prototypes: ["Onslaught 1"], x: 311, },
    {id: "Onslaught 3", prototypes: ["Onslaught 1"], x: 314, },
    {id: "Nob 1", x: 308, y: 870, width: 21, height: 21, front: "forbidden_stars/unit/orks-3.png", back: "forbidden_stars/unit/orks-3r.png", },
    {id: "Nob 2", prototypes: ["Nob 1"], x: 311, },
    {id: "Nob 3", prototypes: ["Nob 1"], x: 314, },
    {id: "Nob 4", prototypes: ["Nob 1"], x: 317, },
    {id: "Nob 5", prototypes: ["Nob 1"], x: 320, },
    {id: "Nob 6", prototypes: ["Nob 1"], x: 578, },
    {id: "Battlewagon 1", x: 308, y: 896, width: 29, height: 29, front: "forbidden_stars/unit/orks-4.png", back: "forbidden_stars/unit/orks-4r.png", },
    {id: "Battlewagon 2", prototypes: ["Battlewagon 1"], x: 311, },
    {id: "Battlewagon 3", prototypes: ["Battlewagon 1"], x: 314, },
    {id: "Kill Kroozer 1", x: 343, y: 826, width: 40, height: 32, front: "forbidden_stars/unit/orks-5.png", back: "forbidden_stars/unit/orks-5r.png", },
    {id: "Kill Kroozer 2", prototypes: ["Kill Kroozer 1"], x: 346, },
    {id: "Kill Kroozer 3", prototypes: ["Kill Kroozer 1"], x: 349, },
    {id: "Gargant 1", x: 343, y: 863, width: 38, height: 38, front: "forbidden_stars/unit/orks-6.png", back: "forbidden_stars/unit/orks-6r.png", },
    {id: "Gargant 2", prototypes: ["Gargant 1"], x: 346, },
    {id: "Gargant 3", prototypes: ["Gargant 1"], x: 349, },

    {id: "Orks Advance", x: 400, y: 929, width: 38, height: 33, front: "forbidden_stars/order/advance.png", back: "forbidden_stars/order/orks.png", },
    {id: "Orks Advance ", prototypes: ["Orks Advance"], x: 420, },
    {id: "Orks Deploy", x: 400, y: 950, width: 38, height: 33, front: "forbidden_stars/order/deploy.png", back: "forbidden_stars/order/orks.png", },
    {id: "Orks Deploy ", prototypes: ["Orks Deploy"], x: 420, },
    {id: "Orks Dominate", x: 400, y: 971, width: 38, height: 33, front: "forbidden_stars/order/dominate.png", back: "forbidden_stars/order/orks.png", },
    {id: "Orks Dominate ", prototypes: ["Orks Dominate"], x: 420, },
    {id: "Orks Strategize", x: 400, y: 992, width: 38, height: 33, front: "forbidden_stars/order/strategize.png", back: "forbidden_stars/order/orks.png", },
    {id: "Orks Strategize ", prototypes: ["Orks Strategize"], x: 420, },

    {id: "Chaos Objective 3", prototypes: ["obj-chaos"], x: 500, y: 830, },
    {id: "Chaos Objective 4", prototypes: ["obj-chaos"], x: 533, y: 830, },

    {id: "Eldar Objective 3", prototypes: ["obj-eldar"], x: 500, y: 864, },
    {id: "Eldar Objective 4", prototypes: ["obj-eldar"], x: 533, y: 864, },

    {id: "Space Marines Objective 5", prototypes: ["obj-sm"], x: 500, y: 898, },
    {id: "Space Marines Objective 6", prototypes: ["obj-sm"], x: 533, y: 898, },

    // Space Marines

    { id: "Adeptus Mechanicus", prototypes: ["card"], x: 658, y: 826, front: "forbidden_stars/event/sm_adeptus_mechanicus.jpg", back: "forbidden_stars/event/sm_back.jpg", },
    { id: "Emperor's Champion", prototypes: ["Adeptus Mechanicus"], front: "forbidden_stars/event/sm_emperors_champion.jpg", },
    { id: "Exterminatus", prototypes: ["Adeptus Mechanicus"], front: "forbidden_stars/event/sm_exterminatus.jpg", },
    { id: "Heroic Intervention", prototypes: ["Adeptus Mechanicus"], front: "forbidden_stars/event/sm_heroic_intervention.jpg", },
    { id: "Rites of Battle", prototypes: ["Adeptus Mechanicus"], front: "forbidden_stars/event/sm_rites_of_battle.jpg", },
    { id: "The Emperor Protects", prototypes: ["Adeptus Mechanicus"], front: "forbidden_stars/event/sm_the_emperor_protects.jpg", },
    { id: "Unwavering Resolve", prototypes: ["Adeptus Mechanicus"], front: "forbidden_stars/event/sm_unwavering_resolve.jpg", },
    { id: "Work of the Righteous", prototypes: ["Adeptus Mechanicus"], front: "forbidden_stars/event/sm_work_of_the_righteous.jpg", },

    { id: "Crusade", prototypes: ["card"], x: 733, y: 826, front: "forbidden_stars/upgrade/sm_crusade.jpg", back: "forbidden_stars/upgrade/sm_crusade.jpg", },
    { id: "Direct the Faithful", prototypes: ["Crusade"], front: "forbidden_stars/upgrade/sm_direct_the_faithful.jpg", },
    { id: "Drop Pods", prototypes: ["Crusade"], front: "forbidden_stars/upgrade/sm_drop_pods.jpg", },
    { id: "Rain of Fire", prototypes: ["Crusade"], front: "forbidden_stars/upgrade/sm_rain_of_fire.jpg", },
    { id: "Recruitment Worlds", prototypes: ["Crusade"], front: "forbidden_stars/upgrade/sm_recruitment_worlds.jpg", },

    { id: "Armoured Advance", prototypes: ["card"], x: 808, y: 826, front: "forbidden_stars/combat/sm_armoured_advance.jpg", back: "forbidden_stars/combat/sm_back.jpg", },
    { id: "Armoured Advance ", prototypes: ["Armoured Advance"], },
    { id: "Break the Line", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_break_the_line.jpg", },
    { id: "Break the Line ", prototypes: ["Break the Line"], },
    { id: "Drop Pod Assault", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_drop_pod_assault.jpg", },
    { id: "Drop Pod Assault ", prototypes: ["Drop Pod Assault"], },
    { id: "Emperor's Glory", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_emperors_glory.jpg", },
    { id: "Emperor's Glory ", prototypes: ["Emperor's Glory"], },
    { id: "Emperor's Might", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_emperors_might.jpg", },
    { id: "Emperor's Might ", prototypes: ["Emperor's Might"], },
    { id: "Glory and Death", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_glory_and_death.jpg", },
    { id: "Glory and Death ", prototypes: ["Glory and Death"], },
    { id: "Hold the Line", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_hold_the_line.jpg", },
    { id: "Hold the Line ", prototypes: ["Hold the Line"], },
    { id: "Show no Fear", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_show_no_fear.jpg", },
    { id: "Show no Fear ", prototypes: ["Show no Fear"], },
    { id: "Veteran Scouts", prototypes: ["Armoured Advance"], front: "forbidden_stars/combat/sm_veteran_scouts.jpg", },
    { id: "Veteran Scouts ", prototypes: ["Veteran Scouts"], },

    {id: "Space Marines Reference", x: 883, y: 826, width: 70, height: 100, immobile: true, front: "forbidden_stars/sm-ref.jpg", },
    {id: "Space Marines Materiel", x: 884, y: 827, width: 32, height: 32, immobile: true, front: "forbidden_stars/sm-mat.png", hasLabel: true, label: 6, labelColor: ["#36b450"], },

    { prototypes: ["handScreen"], x: 658, y: 929, visionWhitelist: ["Space Marines"], backgroundColor: "rgba(21,102,164,alpha)", labelPlayerName: "Space Marines", },

    { id: "Ambush", prototypes: ["card"], x: 1113, y: 929, front: "forbidden_stars/combat/sm_ambush.jpg", back: "forbidden_stars/combat/sm_back.jpg", },
    { id: "Ambush ", prototypes: ["Ambush"], },
    { id: "Blessed Power Armour", prototypes: ["Ambush"], front: "forbidden_stars/combat/sm_blessed_power_armour.jpg", },
    { id: "Blessed Power Armour ", prototypes: ["Blessed Power Armour"], },
    { id: "Faith in the Emperor", prototypes: ["Ambush"], front: "forbidden_stars/combat/sm_faith_in_the_emperor.jpg", },
    { id: "Faith in the Emperor ", prototypes: ["Faith in the Emperor"], },
    { id: "Fury of the Ultramar", prototypes: ["Ambush"], front: "forbidden_stars/combat/sm_fury_of_the_ultramar.jpg", },
    { id: "Fury of the Ultramar ", prototypes: ["Fury of the Ultramar"], },
    { id: "Reconnaissance", prototypes: ["Ambush"], front: "forbidden_stars/combat/sm_reconnaissance.jpg", },
    { id: "Reconnaissance ", prototypes: ["Reconnaissance"], },

    {id: "Scout 1", x: 958, y: 826, width: 14, height: 14, front: "forbidden_stars/unit/sm-1.png", back: "forbidden_stars/unit/sm-1r.png", },
    {id: "Scout 2", prototypes: ["Scout 1"], x: 961, },
    {id: "Scout 3", prototypes: ["Scout 1"], x: 1226, },
    {id: "Scout 4", prototypes: ["Scout 1"], x: 1229, },
    {id: "Scout 5", prototypes: ["Scout 1"], x: 1232, },
    {id: "Scout 6", prototypes: ["Scout 1"], x: 1235, },
    {id: "Strike Cruiser 1", x: 958, y: 845, width: 24, height: 20, front: "forbidden_stars/unit/sm-2.png", back: "forbidden_stars/unit/sm-2r.png", },
    {id: "Strike Cruiser 2", prototypes: ["Strike Cruiser 1"], x: 961, },
    {id: "Strike Cruiser 3", prototypes: ["Strike Cruiser 1"], x: 1225, },
    {id: "Space Marine 1", x: 958, y: 870, width: 21, height: 21, front: "forbidden_stars/unit/sm-3.png", back: "forbidden_stars/unit/sm-3r.png", },
    {id: "Space Marine 2", prototypes: ["Space Marine 1"], x: 961, },
    {id: "Space Marine 3", prototypes: ["Space Marine 1"], x: 964, },
    {id: "Space Marine 4", prototypes: ["Space Marine 1"], x: 967, },
    {id: "Space Marine 5", prototypes: ["Space Marine 1"], x: 970, },
    {id: "Space Marine 6", prototypes: ["Space Marine 1"], x: 1228, },
    {id: "Land Raider 1", x: 958, y: 896, width: 29, height: 29, front: "forbidden_stars/unit/sm-4.png", back: "forbidden_stars/unit/sm-4r.png", },
    {id: "Land Raider 2", prototypes: ["Land Raider 1"], x: 961, },
    {id: "Land Raider 3", prototypes: ["Land Raider 1"], x: 964, },
    {id: "Land Raider 4", prototypes: ["Land Raider 1"], x: 967, },
    {id: "Land Raider 5", prototypes: ["Land Raider 1"], x: 970, },
    {id: "Land Raider 6", prototypes: ["Land Raider 1"], x: 973, },
    {id: "Battle Barge 1", x: 993, y: 826, width: 40, height: 32, front: "forbidden_stars/unit/sm-5.png", back: "forbidden_stars/unit/sm-5r.png", },
    {id: "Battle Barge 2", prototypes: ["Battle Barge 1"], x: 996, },
    {id: "Battle Barge 3", prototypes: ["Battle Barge 1"], x: 999, },
    {id: "Warlord Titan 1", x: 993, y: 863, width: 38, height: 38, front: "forbidden_stars/unit/sm-6.png", back: "forbidden_stars/unit/sm-6r.png", },
    {id: "Warlord Titan 2", prototypes: ["Warlord Titan 1"], x: 996, },
    {id: "Warlord Titan 3", prototypes: ["Warlord Titan 1"], x: 999, },

    {id: "Space Marines Advance", x: 1050, y: 929, width: 38, height: 33, front: "forbidden_stars/order/advance.png", back: "forbidden_stars/order/sm.png", },
    {id: "Space Marines Advance ", prototypes: ["Space Marines Advance"], x: 1070, },
    {id: "Space Marines Deploy", x: 1050, y: 950, width: 38, height: 33, front: "forbidden_stars/order/deploy.png", back: "forbidden_stars/order/sm.png", },
    {id: "Space Marines Deploy ", prototypes: ["Space Marines Deploy"], x: 1070, },
    {id: "Space Marines Dominate", x: 1050, y: 971, width: 38, height: 33, front: "forbidden_stars/order/dominate.png", back: "forbidden_stars/order/sm.png", },
    {id: "Space Marines Dominate ", prototypes: ["Space Marines Dominate"], x: 1070, },
    {id: "Space Marines Strategize", x: 1050, y: 992, width: 38, height: 33, front: "forbidden_stars/order/strategize.png", back: "forbidden_stars/order/sm.png", },
    {id: "Space Marines Strategize ", prototypes: ["Space Marines Strategize"], x: 1070, },

    {id: "Chaos Objective 5", prototypes: ["obj-chaos"], x: 1150, y: 830, },
    {id: "Chaos Objective 6", prototypes: ["obj-chaos"], x: 1183, y: 830, },

    {id: "Eldar Objective 5", prototypes: ["obj-eldar"], x: 1150, y: 864, },
    {id: "Eldar Objective 6", prototypes: ["obj-eldar"], x: 1183, y: 864, },

    {id: "Orks Objective 5", prototypes: ["obj-orks"], x: 1150, y: 898, },
    {id: "Orks Objective 6", prototypes: ["obj-orks"], x: 1183, y: 898, },

    // Misc

    { id: "tile", prototype: true, x: 8, y: 214, width: 200, height: 200, },
    { id: "Tile 1", prototypes: ["tile"], front: "forbidden_stars/tile/01a.jpg", back: "forbidden_stars/tile/01b.jpg", },
    { id: "Tile 2", prototypes: ["tile"], front: "forbidden_stars/tile/02a.jpg", back: "forbidden_stars/tile/02b.jpg", },
    { id: "Tile 3", prototypes: ["tile"], front: "forbidden_stars/tile/03a.jpg", back: "forbidden_stars/tile/03b.jpg", },
    { id: "Tile 4", prototypes: ["tile"], front: "forbidden_stars/tile/04a.jpg", back: "forbidden_stars/tile/04b.jpg", },
    { id: "Tile 5", prototypes: ["tile"], front: "forbidden_stars/tile/05a.jpg", back: "forbidden_stars/tile/05b.jpg", },
    { id: "Tile 6", prototypes: ["tile"], front: "forbidden_stars/tile/06a.jpg", back: "forbidden_stars/tile/06b.jpg", },
    { id: "Tile 7", prototypes: ["tile"], front: "forbidden_stars/tile/07a.jpg", back: "forbidden_stars/tile/07b.jpg", },
    { id: "Tile 8", prototypes: ["tile"], front: "forbidden_stars/tile/08a.jpg", back: "forbidden_stars/tile/08b.jpg", },
    { id: "Tile 9", prototypes: ["tile"], front: "forbidden_stars/tile/09a.jpg", back: "forbidden_stars/tile/09b.jpg", },
    { id: "Tile 10", prototypes: ["tile"], front: "forbidden_stars/tile/10a.jpg", back: "forbidden_stars/tile/10b.jpg", },
    { id: "Tile 11", prototypes: ["tile"], front: "forbidden_stars/tile/11a.jpg", back: "forbidden_stars/tile/11b.jpg", },
    { id: "Tile 12", prototypes: ["tile"], front: "forbidden_stars/tile/12a.jpg", back: "forbidden_stars/tile/12b.jpg", },

    { id: "Warp Storm 1", x: 7, y: 419, width: 201, height: 14, front: "forbidden_stars/tile/warpstorm.png", back: "forbidden_stars/tile/warpstorm-moved.png"},
    { id: "Warp Storm 2", prototypes: ["Warp Storm 1"], },
    { id: "Warp Storm 3", prototypes: ["Warp Storm 1"], },
    { id: "Warp Storm 4", prototypes: ["Warp Storm 1"], },

    { id: "Die 1", x: 5, y: 447, width: 32, height: 32, faces: ["forbidden_stars/dice/offense.png", "forbidden_stars/dice/offense.png", "forbidden_stars/dice/offense.png", "forbidden_stars/dice/defense.png", "forbidden_stars/dice/defense.png", "forbidden_stars/dice/morale.png"], },
    { id: "Die 2", prototypes: ["Die 1"], x: 39, y: 447},
    { id: "Die 3", prototypes: ["Die 1"], x: 73, y: 447},
    { id: "Die 4", prototypes: ["Die 1"], x: 107, y: 447},
    { id: "Die 5", prototypes: ["Die 1"], x: 5, y: 481},
    { id: "Die 6", prototypes: ["Die 1"], x: 39, y: 481},
    { id: "Die 7", prototypes: ["Die 1"], x: 73, y: 481},
    { id: "Die 8", prototypes: ["Die 1"], x: 107, y: 481},
    { id: "Die 9", prototypes: ["Die 1"], x: 5, y: 515},
    { id: "Die 10", prototypes: ["Die 1"], x: 39, y: 515},
    { id: "Die 11", prototypes: ["Die 1"], x: 73, y: 515},
    { id: "Die 12", prototypes: ["Die 1"], x: 107, y: 515},
    { id: "Die 13", prototypes: ["Die 1"], x: 5, y: 549},
    { id: "Die 14", prototypes: ["Die 1"], x: 39, y: 549},
    { id: "Die 15", prototypes: ["Die 1"], x: 73, y: 549},
    { id: "Die 16", prototypes: ["Die 1"], x: 107, y: 549},

    { id: "Combat 1", x: 141, y: 448, width: 32, height: 32, front: "forbidden_stars/token/offense.png", back: "forbidden_stars/token/defense.png", },
    { id: "Combat 2", prototypes: ["Combat 1"], y: 468},
    { id: "Combat 3", prototypes: ["Combat 1"], y: 488},
    { id: "Combat 4", prototypes: ["Combat 1"], y: 508},
    { id: "Combat 5", prototypes: ["Combat 1"], y: 528},
    { id: "Combat 6", prototypes: ["Combat 1"], y: 548},
    { id: "Combat 7", prototypes: ["Combat 1"], x: 175, faceIndex: 1, },
    { id: "Combat 8", prototypes: ["Combat 2"], x: 175, faceIndex: 1, },
    { id: "Combat 9", prototypes: ["Combat 3"], x: 175, faceIndex: 1, },
    { id: "Combat 10", prototypes: ["Combat 4"], x: 175, faceIndex: 1, },
    { id: "Combat 11", prototypes: ["Combat 5"], x: 175, faceIndex: 1, },
    { id: "Combat 12", prototypes: ["Combat 6"], x: 175, faceIndex: 1, },

    { id: "Reinforcement 1", x: 1018, y: 394, width: 32, height: 32, front: "forbidden_stars/token/reinforcement.png", back: "forbidden_stars/token/reinforcement-r.png", },
    { id: "Reinforcement 2", prototypes: ["Reinforcement 1"], x: 1023},
    { id: "Reinforcement 3", prototypes: ["Reinforcement 1"], x: 1028},
    { id: "Reinforcement 4", prototypes: ["Reinforcement 1"], x: 1033},
    { id: "Reinforcement 5", prototypes: ["Reinforcement 1"], x: 1038},
    { id: "Reinforcement 6", prototypes: ["Reinforcement 1"], x: 1043},
    { id: "Reinforcement 7", prototypes: ["Reinforcement 1"], x: 1048},
    { id: "Reinforcement 8", prototypes: ["Reinforcement 1"], x: 1053},
    { id: "Reinforcement 9", prototypes: ["Reinforcement 1"], x: 1058},
    { id: "Reinforcement 10", prototypes: ["Reinforcement 1"], x: 1063},
    { id: "Reinforcement 11", prototypes: ["Reinforcement 1"], x: 1068},
    { id: "Reinforcement 12", prototypes: ["Reinforcement 1"], x: 394, y: 826},

    { id: "Cache 1", x: 1018, y: 434, width: 32, height: 32, front: "forbidden_stars/token/cache.png", },
    { id: "Cache 2", prototypes: ["Cache 1"], x: 1023},
    { id: "Cache 3", prototypes: ["Cache 1"], x: 1028},
    { id: "Cache 4", prototypes: ["Cache 1"], x: 1033},
    { id: "Cache 5", prototypes: ["Cache 1"], x: 1038},
    { id: "Cache 6", prototypes: ["Cache 1"], x: 1043},
    { id: "Cache 7", prototypes: ["Cache 1"], x: 1048},
    { id: "Cache 8", prototypes: ["Cache 1"], x: 1053},
    { id: "Cache 9", prototypes: ["Cache 1"], x: 1058},
    { id: "Cache 10", prototypes: ["Cache 1"], x: 1063},
    { id: "Cache 11", prototypes: ["Cache 1"], x: 1068},
    { id: "Cache 12", prototypes: ["Cache 1"], x: 1073},

    { id: "Forge 1", x: 1018, y: 474, width: 32, height: 32, front: "forbidden_stars/token/forge.png", },
    { id: "Forge 2", prototypes: ["Forge 1"], x: 1023},
    { id: "Forge 3", prototypes: ["Forge 1"], x: 1028},
    { id: "Forge 4", prototypes: ["Forge 1"], x: 1033},
    { id: "Forge 5", prototypes: ["Forge 1"], x: 1038},
    { id: "Forge 6", prototypes: ["Forge 1"], x: 1043},
    { id: "Forge 7", prototypes: ["Forge 1"], x: 1048},
    { id: "Forge 8", prototypes: ["Forge 1"], x: 1053},
    { id: "Forge 9", prototypes: ["Forge 1"], x: 1058},
    { id: "Forge 10", prototypes: ["Forge 1"], x: 1063},
    { id: "Forge 11", prototypes: ["Forge 1"], x: 1068},
    { id: "Forge 12", prototypes: ["Forge 1"], x: 1073},

    {id: "Factory 1", x: 1018, y: 514, width: 33, height: 33, faces: ["forbidden_stars/unit/chaos-factory.png", "forbidden_stars/unit/eldar-factory.png", "forbidden_stars/unit/orks-factory.png", "forbidden_stars/unit/sm-factory.png"], faceIndex: 1},
    {id: "Factory 2", prototypes: ["Factory 1"], x: 1023, faceIndex: 0},
    {id: "Factory 3", prototypes: ["Factory 1"], x: 1028, faceIndex: 3},
    {id: "Factory 4", prototypes: ["Factory 1"], x: 1033, faceIndex: 2},
    {id: "Factory 5", prototypes: ["Factory 1"], x: 1038, faceIndex: 1},
    {id: "Factory 6", prototypes: ["Factory 1"], x: 1043, faceIndex: 0},
    {id: "Factory 7", prototypes: ["Factory 1"], x: 1216, y: 896, faceIndex: 3},
    {id: "Factory 8", prototypes: ["Factory 1"], x: 566, y: 896, faceIndex: 2},
    {id: "Factory 9", prototypes: ["Factory 1"], x: 1216, y: 78, faceIndex: 1},
    {id: "Factory 10", prototypes: ["Factory 1"], x: 566, y: 78, faceIndex: 0},

    {id: "City 1", x: 1018, y: 554, width: 33, height: 33, faces: ["forbidden_stars/unit/chaos-city.png", "forbidden_stars/unit/eldar-city.png", "forbidden_stars/unit/orks-city.png", "forbidden_stars/unit/sm-city.png"], faceIndex: 3},
    {id: "City 2", prototypes: ["City 1"], x: 1023, faceIndex: 2},
    {id: "City 3", prototypes: ["City 1"], x: 1028, faceIndex: 1},
    {id: "City 4", prototypes: ["City 1"], x: 1033, faceIndex: 0},
    {id: "City 5", prototypes: ["City 1"], x: 1038, faceIndex: 3},
    {id: "City 6", prototypes: ["City 1"], x: 1043, faceIndex: 2},
    {id: "City 7", prototypes: ["City 1"], x: 1048, faceIndex: 1},
    {id: "City 8", prototypes: ["City 1"], x: 1053, faceIndex: 0},
    {id: "City 9", prototypes: ["City 1"], x: 1058, faceIndex: 3},
    {id: "City 10", prototypes: ["City 1"], x: 1063, faceIndex: 2},
    {id: "City 11", prototypes: ["City 1"], x: 1068, faceIndex: 1},
    {id: "City 12", prototypes: ["City 1"], x: 1073, faceIndex: 0},
    {id: "City 13", prototypes: ["City 1"], x: 1078, faceIndex: 3},
    {id: "City 14", prototypes: ["City 1"], x: 1083, faceIndex: 2},
    {id: "City 15", prototypes: ["City 1"], x: 1088, faceIndex: 1},

    {id: "Bastion 1", x: 1018, y: 594, width: 33, height: 33, faces: ["forbidden_stars/unit/chaos-bastion.png", "forbidden_stars/unit/eldar-bastion.png", "forbidden_stars/unit/orks-bastion.png", "forbidden_stars/unit/sm-bastion.png"], faceIndex: 3},
    {id: "Bastion 2", prototypes: ["Bastion 1"], x: 1023, faceIndex: 2},
    {id: "Bastion 3", prototypes: ["Bastion 1"], x: 1028, faceIndex: 1},
    {id: "Bastion 4", prototypes: ["Bastion 1"], x: 1033, faceIndex: 0},
    {id: "Bastion 5", prototypes: ["Bastion 1"], x: 1038, faceIndex: 3},
    {id: "Bastion 6", prototypes: ["Bastion 1"], x: 1043, faceIndex: 2},
    {id: "Bastion 7", prototypes: ["Bastion 1"], x: 1048, faceIndex: 1},
    {id: "Bastion 8", prototypes: ["Bastion 1"], x: 1053, faceIndex: 0},
    {id: "Bastion 9", prototypes: ["Bastion 1"], x: 1058, faceIndex: 3},
    {id: "Bastion 10", prototypes: ["Bastion 1"], x: 1063, faceIndex: 2},

    {id: "Turn Track", immobile: true, x: 1140, y: 394, width: 32, height: 232, front: "forbidden_stars/token/turn_track.jpg", },
    {id: "Turn Marker", x: 1146, y: 588, width: 20, height: 20, front: "forbidden_stars/token/turn_marker.png", },
    {id: "First Player", x: 1069, y: 221, width: 100, height: 41, front: "forbidden_stars/token/first_player.png", },
  ],
};
