module.exports = {
  name: "Scrabble",

  roles: [
    { id: "red",    name: "Red",   },
    { id: "yellow", name: "Yellow", },
    { id: "green",  name: "Green", },
    { id: "blue",   name: "Blue", },
  ],
  objects: [
    { id: "board",
      width:754,
      height: 754,
      x:173,
      y:150,
      front: "scrabble/board.png",
      locked: true,
      snapZones: [{x:2, y:2, width:750, height:750, cellWidth:50, cellHeight:50}]
    },
    { id: "chart",
      width: 166,
      height: 447,
      x: 977,
      y: 303,
      front: "scrabble/chart.png",
      locked: true
    },
    {
      id: "tile",
      prototype: true,
      width: 50,
      height: 50,
      x: 64,
      y: 502,
      back: "scrabble/tile_back.png",
      snapZones: [{x:0, y:0, width:50, height:50, cellWidth:50, cellHeight:50}]  
    },
    {id:"Blank", prototypes:["tile"], front:"scrabble/tile_blank.png", hasLabel: true, labelColor:["#800000"]},
    {id:"Blank", prototypes:["tile"], front:"scrabble/tile_blank.png", hasLabel: true, labelColor:["#800000"]},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"A", prototypes:["tile"], front:"scrabble/tile_A.png"},
    {id:"B", prototypes:["tile"], front:"scrabble/tile_B.png"},
    {id:"B", prototypes:["tile"], front:"scrabble/tile_B.png"},
    {id:"C", prototypes:["tile"], front:"scrabble/tile_C.png"},
    {id:"C", prototypes:["tile"], front:"scrabble/tile_C.png"},
    {id:"D", prototypes:["tile"], front:"scrabble/tile_D.png"},
    {id:"D", prototypes:["tile"], front:"scrabble/tile_D.png"},
    {id:"D", prototypes:["tile"], front:"scrabble/tile_D.png"},
    {id:"D", prototypes:["tile"], front:"scrabble/tile_D.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"E", prototypes:["tile"], front:"scrabble/tile_E.png"},
    {id:"F", prototypes:["tile"], front:"scrabble/tile_F.png"},
    {id:"F", prototypes:["tile"], front:"scrabble/tile_F.png"},
    {id:"G", prototypes:["tile"], front:"scrabble/tile_G.png"},
    {id:"G", prototypes:["tile"], front:"scrabble/tile_G.png"},
    {id:"G", prototypes:["tile"], front:"scrabble/tile_G.png"},
    {id:"H", prototypes:["tile"], front:"scrabble/tile_H.png"},
    {id:"H", prototypes:["tile"], front:"scrabble/tile_H.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"I", prototypes:["tile"], front:"scrabble/tile_I.png"},
    {id:"J", prototypes:["tile"], front:"scrabble/tile_J.png"},
    {id:"K", prototypes:["tile"], front:"scrabble/tile_K.png"},
    {id:"L", prototypes:["tile"], front:"scrabble/tile_L.png"},
    {id:"L", prototypes:["tile"], front:"scrabble/tile_L.png"},
    {id:"L", prototypes:["tile"], front:"scrabble/tile_L.png"},
    {id:"L", prototypes:["tile"], front:"scrabble/tile_L.png"},
    {id:"M", prototypes:["tile"], front:"scrabble/tile_M.png"},
    {id:"M", prototypes:["tile"], front:"scrabble/tile_M.png"},
    {id:"N", prototypes:["tile"], front:"scrabble/tile_N.png"},
    {id:"N", prototypes:["tile"], front:"scrabble/tile_N.png"},
    {id:"N", prototypes:["tile"], front:"scrabble/tile_N.png"},
    {id:"N", prototypes:["tile"], front:"scrabble/tile_N.png"},
    {id:"N", prototypes:["tile"], front:"scrabble/tile_N.png"},
    {id:"N", prototypes:["tile"], front:"scrabble/tile_N.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"O", prototypes:["tile"], front:"scrabble/tile_O.png"},
    {id:"P", prototypes:["tile"], front:"scrabble/tile_P.png"},
    {id:"P", prototypes:["tile"], front:"scrabble/tile_P.png"},
    {id:"Q", prototypes:["tile"], front:"scrabble/tile_Q.png"},
    {id:"R", prototypes:["tile"], front:"scrabble/tile_R.png"},
    {id:"R", prototypes:["tile"], front:"scrabble/tile_R.png"},
    {id:"R", prototypes:["tile"], front:"scrabble/tile_R.png"},
    {id:"R", prototypes:["tile"], front:"scrabble/tile_R.png"},
    {id:"R", prototypes:["tile"], front:"scrabble/tile_R.png"},
    {id:"R", prototypes:["tile"], front:"scrabble/tile_R.png"},
    {id:"S", prototypes:["tile"], front:"scrabble/tile_S.png"},
    {id:"S", prototypes:["tile"], front:"scrabble/tile_S.png"},
    {id:"S", prototypes:["tile"], front:"scrabble/tile_S.png"},
    {id:"S", prototypes:["tile"], front:"scrabble/tile_S.png"},
    {id:"T", prototypes:["tile"], front:"scrabble/tile_T.png"},
    {id:"T", prototypes:["tile"], front:"scrabble/tile_T.png"},
    {id:"T", prototypes:["tile"], front:"scrabble/tile_T.png"},
    {id:"T", prototypes:["tile"], front:"scrabble/tile_T.png"},
    {id:"T", prototypes:["tile"], front:"scrabble/tile_T.png"},
    {id:"T", prototypes:["tile"], front:"scrabble/tile_T.png"},
    {id:"U", prototypes:["tile"], front:"scrabble/tile_U.png"},
    {id:"U", prototypes:["tile"], front:"scrabble/tile_U.png"},
    {id:"U", prototypes:["tile"], front:"scrabble/tile_U.png"},
    {id:"U", prototypes:["tile"], front:"scrabble/tile_U.png"},
    {id:"V", prototypes:["tile"], front:"scrabble/tile_V.png"},
    {id:"V", prototypes:["tile"], front:"scrabble/tile_V.png"},
    {id:"W", prototypes:["tile"], front:"scrabble/tile_W.png"},
    {id:"W", prototypes:["tile"], front:"scrabble/tile_W.png"},
    {id:"X", prototypes:["tile"], front:"scrabble/tile_X.png"},
    {id:"Y", prototypes:["tile"], front:"scrabble/tile_Y.png"},
    {id:"Y", prototypes:["tile"], front:"scrabble/tile_Y.png"},
    {id:"Z", prototypes:["tile"], front:"scrabble/tile_Z.png"},
    {
      id: "handScreen",
      prototype: true,
      locked: true,
      width:  500,
      height: 100,
      hideFaces: ["front"],
      snapZones: [{}]
    },
    { prototypes: ["handScreen"], x: 25, y: 25, visionWhitelist: ["red"], backgroundColor: "rgba(255,0,0,alpha)", labelPlayerName: "red"},
    { prototypes: ["handScreen"], x: 575, y: 25, visionWhitelist: ["yellow"], backgroundColor: "rgba(255,255,0,alpha)", labelPlayerName: "yellow"},
    { prototypes: ["handScreen"], x: 25, y: 929, visionWhitelist: ["green"], backgroundColor: "rgba(0,255,0,alpha)", labelPlayerName: "green"},
    { prototypes: ["handScreen"], x: 575, y: 929, visionWhitelist: ["blue"], backgroundColor: "rgba(0,0,255,alpha)", labelPlayerName: "blue"},
    { id: "Red Score",
      width: 100,
      height: 33,
      x: 49,
      y: 150,
      front: "scrabble/score.png",
      backgroundColor: "rgba(255,0,0,1)",
      hasLabel: true,
      label: "0",
      labelColor:["#000000"],
      immobile: true
    },
    { id: "Yellow Score",
      prototypes: ["Red Score"],
      x: 951,
      backgroundColor: "rgba(255,255,0,1)",
    },
    { id: "Green Score",
      prototypes: ["Red Score"],
      y: 871,
      backgroundColor: "rgba(0,255,0,1)",
    },
    { id: "Blue Score",
      prototypes: ["Red Score"],
      x: 951,
      y: 871,
      backgroundColor: "rgba(0,0,255,1)",
    }
  ]
};
