module.exports = {
  name: "Star Wars: Rebellion",

  roles: [
    { id: "Rebels", name: "Rebels", },
    { id: "Empire", name: "Empire", },
  ],
  objects: [
    {
      faces: ["swr/Map.jpg"],
      locked: true,
      x: 8,
      y: 170,
      width: 1280,
      height: 640,
    },
    {
      faces: ["swr/ReferenceRebel.jpg"],
      immobile: true,
      x: 78,
      y: 8,
      width: 320,
      height: 160,
    },
    {
      faces: ["swr/ReferenceEmpire.jpg"],
      immobile: true,
      x: 78,
      y: 812,
      width: 320,
      height: 160,
    },

    // cards

    {id: "mr", prototype: true, x: 8, y: 39, width: 67, height: 100, back: "swr/mission/MissionRebelCardBack.jpg"},
    {id: "me", prototype: true, x: 8, y: 845, width: 67, height: 100, back: "swr/mission/MissionEmpireCardBack.jpg"},
    {id: "ar", prototype: true, x: 401, y: 62, width: 47, height: 70, back: "swr/action/ActionCardRebelCardBack.jpg"},
    {id: "ae", prototype: true, x: 401, y: 866, width: 47, height: 70, back: "swr/action/ActionCardEmpireCardBack.jpg"},
    {id: "o3", prototype: true, x: 13, y: 181, width: 67, height: 100, back: "swr/objective/ObjectiveCardBack3.jpg"},
    {id: "o2", prototype: true, x: 83, y: 181, width: 67, height: 100, back: "swr/objective/ObjectiveCardBack2.jpg"},
    {id: "o1", prototype: true, x: 153, y: 181, width: 67, height: 100, back: "swr/objective/ObjectiveCardBack1.jpg"},
    {id: "proj", prototype: true, x: 12, y: 699, width: 67, height: 100, back: "swr/mission/MissionEmpireCardBack.jpg"},
    {id: "probe", prototype: true, x: 83, y: 729, width: 47, height: 70, back: "swr/probe/SystemCardBack.jpg"},
    {id: "ts", prototype: true, x: 1298, y: 415, width: 47, height: 70, back: "swr/tactics/TacticSpaceCardBack.jpg"},
    {id: "tg", prototype: true, x: 1298, y: 495, width: 47, height: 70, back: "swr/tactics/TacticGroundCardBack.jpg"},

    {id: "loy", prototype: true, width: 33, height: 28, immobile: true, faces: ["swr/marker/transparent.png", "swr/marker/MarkerLoyaltyRebel.png", "swr/marker/MarkerLoyaltyEmpire.png"],},
    {id: "sab", prototype: true, width: 36, height: 21, immobile: true, faces: ["swr/marker/transparent.png", "swr/marker/MarkerSabotage.png"],},

    {id: "Base Defenses", prototypes: ["mr"], front: "swr/mission/MissionRebelBaseDefenses.jpg", },
    {id: "Contingency Plan", prototypes: ["mr"], front: "swr/mission/MissionRebelContingencyPlan.jpg", },
    {id: "Covert Operation", prototypes: ["mr"], front: "swr/mission/MissionRebelCovertOperation.jpg", },
    {id: "Daring Rescue", prototypes: ["mr"], front: "swr/mission/MissionRebelDaringRescue.jpg", },
    {id: "Daring Rescue ", prototypes: ["Daring Rescue"], },
    {id: "Demolition", prototypes: ["mr"], front: "swr/mission/MissionRebelDemolition.jpg", },
    {id: "Establish Trade Relations", prototypes: ["mr"], front: "swr/mission/MissionRebelEstablishTradeRelations.jpg", },
    {id: "For The Greater Good", prototypes: ["mr"], front: "swr/mission/MissionRebelForTheGreaterGood.jpg", },
    {id: "Hidden Fleet", prototypes: ["mr"], front: "swr/mission/MissionRebelHiddenFleet.jpg", },
    {id: "Hidden Fleet ", prototypes: ["Hidden Fleet"], },
    {id: "Hidden Fleet  ", prototypes: ["Hidden Fleet"], },
    {id: "Hit And Run", prototypes: ["mr"], front: "swr/mission/MissionRebelHitAndRun.jpg", },
    {id: "Hit And Run ", prototypes: ["Hit And Run"], },
    {id: "Incite Rebellion", prototypes: ["mr"], front: "swr/mission/MissionRebelInciteRebellion.jpg", },
    {id: "Incite Rebellion ", prototypes: ["Incite Rebellion"], },
    {id: "Lead The Strike Team", prototypes: ["mr"], front: "swr/mission/MissionRebelLeadTheStrikeTeam.jpg", },
    {id: "Misdirection", prototypes: ["mr"], front: "swr/mission/MissionRebelMisdirection.jpg", },
    {id: "Plant False Lead", prototypes: ["mr"], front: "swr/mission/MissionRebelPlantFalseLead.jpg", },
    {id: "Plan The Assault", prototypes: ["mr"], front: "swr/mission/MissionRebelPlanTheAssault.jpg", },
    {id: "Public Uprising", prototypes: ["mr"], front: "swr/mission/MissionRebelPublicUprising.jpg", },
    {id: "Rogue Squadron Raid", prototypes: ["mr"], front: "swr/mission/MissionRebelRogueSquadronRaid.jpg", },
    {id: "Seek Yoda", prototypes: ["mr"], front: "swr/mission/MissionRebelSeekYoda.jpg", },
    {id: "Stolen Plans", prototypes: ["mr"], front: "swr/mission/MissionRebelStolenPlans.jpg", },
    {id: "Support Of Mon Calamari", prototypes: ["mr"], front: "swr/mission/MissionRebelSupportOfMonCalamari.jpg", },
    {id: "Wookie Uprising", prototypes: ["mr"], front: "swr/mission/MissionRebelWookieUprising.jpg", },
    {id: "Build Alliance", prototypes: ["mr"], x: 455, y: 0, front: "swr/mission/MissionRebelBuildAlliance.jpg", },
    {id: "Infiltration", prototypes: ["mr"], x: 531, y: 0, front: "swr/mission/MissionRebelInfiltration.jpg", },
    {id: "Rapid Mobilization", prototypes: ["mr"], x: 607, y: 0, front: "swr/mission/MissionRebelRapidMobilization.jpg", },
    {id: "Sabotage", prototypes: ["mr"], x: 683, y: 0, front: "swr/mission/MissionRebelSabotage.jpg", },

    {id: "Address Delays", prototypes: ["me"], front: "swr/mission/MissionEmpireAddressDelays.jpg", },
    {id: "Address Delays ", prototypes: ["Address Delays"], },
    {id: "Carbon Freezing", prototypes: ["me"], front: "swr/mission/MissionEmpireCarbonFreezing.jpg", },
    {id: "Collect Bounty", prototypes: ["me"], front: "swr/mission/MissionEmpireCollectBounty.jpg", },
    {id: "Detained", prototypes: ["me"], front: "swr/mission/MissionEmpireDetained.jpg", },
    {id: "Display Of Power", prototypes: ["me"], front: "swr/mission/MissionEmpireDisplayOfPower.jpg", },
    {id: "Double Our Efforts", prototypes: ["me"], front: "swr/mission/MissionEmpireDoubleOurEfforts.jpg", },
    {id: "Fear Will Keep Them In Line", prototypes: ["me"], front: "swr/mission/MissionEmpireFearWillKeepThemInLine.jpg", },
    {id: "Homing Beacon", prototypes: ["me"], front: "swr/mission/MissionEmpireHomingBeacon.jpg", },
    {id: "Hunt Them Down", prototypes: ["me"], front: "swr/mission/MissionEmpireHuntThemDown.jpg", },
    {id: "Imperial Propaganda", prototypes: ["me"], front: "swr/mission/MissionEmpireImperialPropaganda.jpg", },
    {id: "Intercept Transmission", prototypes: ["me"], front: "swr/mission/MissionEmpireInterceptTransmission.jpg", },
    {id: "Intercept Transmission ", prototypes: ["Intercept Transmission"], },
    {id: "Interrogation Droid", prototypes: ["me"], front: "swr/mission/MissionEmpireInterrogationDroid.jpg", },
    {id: "Interrogation", prototypes: ["me"], front: "swr/mission/MissionEmpireInterrogation.jpg", },
    {id: "Interrogation ", prototypes: ["Intercept Transmission"], },
    {id: "Long Range Probe", prototypes: ["me"], front: "swr/mission/MissionEmpireLongRangeProbe.jpg", },
    {id: "Lure Of The Dark Side", prototypes: ["me"], front: "swr/mission/MissionEmpireLureOfTheDarkSide.jpg", },
    {id: "Planetary Conquest", prototypes: ["me"], front: "swr/mission/MissionEmpirePlanetaryConquest.jpg", },
    {id: "Probe Droid Initiative", prototypes: ["me"], front: "swr/mission/MissionEmpireProbeDroidInitiative.jpg", },
    {id: "Retrieve The Plans", prototypes: ["me"], front: "swr/mission/MissionEmpireRetrieveThePlans.jpg", },
    {id: "Secret Weapons Research", prototypes: ["me"], front: "swr/mission/MissionEmpireSecretWeaponsResearch.jpg", },
    {id: "Secret Weapons Research ", prototypes: ["Secret Weapons Research"], },
    {id: "Trade Negotiations", prototypes: ["me"], front: "swr/mission/MissionEmpireTradeNegotiations.jpg", },
    {id: "Trade Negotiations ", prototypes: ["Trade Negotiations"], },
    {id: "Capture Rebel Operative", prototypes: ["me"], x: 455, y: 880, front: "swr/mission/MissionEmpireCaptureRebelOperative.jpg", },
    {id: "Gather Intel", prototypes: ["me"], x: 531, y: 880, front: "swr/mission/MissionEmpireGatherIntel.jpg", },
    {id: "Research And Development", prototypes: ["me"], x: 607, y: 880, front: "swr/mission/MissionEmpireResearchAndDevelopment.jpg", },
    {id: "Rule By Fear", prototypes: ["me"], x: 683, y: 880, front: "swr/mission/MissionEmpireRuleByFear.jpg", },

    {id: "Ambush", prototypes: ["ar"], front: "swr/action/ActionCardRebelAmbush.jpg", },
    {id: "AnOldFriend", prototypes: ["ar"], front: "swr/action/ActionCardRebelAnOldFriend.jpg", },
    {id: "IndependentOperation", prototypes: ["ar"], front: "swr/action/ActionCardRebelIndependentOperation.jpg", },
    {id: "ItsATrap", prototypes: ["ar"], front: "swr/action/ActionCardRebelItsATrap.jpg", },
    {id: "NobleSacrifice", prototypes: ["ar"], front: "swr/action/ActionCardRebelNobleSacrifice.jpg", },
    {id: "OneInAMillion", prototypes: ["ar"], front: "swr/action/ActionCardRebelOneInAMillion.jpg", },
    {id: "PointBlankAssault", prototypes: ["ar"], front: "swr/action/ActionCardRebelPointBlankAssault.jpg", },
    {id: "SonOfSkywalker", prototypes: ["ar"], front: "swr/action/ActionCardRebelSonOfSkywalker.jpg", },
    {id: "TargetTheStarDestroyers", prototypes: ["ar"], front: "swr/action/ActionCardRebelTargetTheStarDestroyers.jpg", },
    {id: "TheMilleniniumFalcon", prototypes: ["ar"], front: "swr/action/ActionCardRebelTheMilleniniumFalcon.jpg", },
    {id: "Undercover", prototypes: ["ar"], front: "swr/action/ActionCardRebelUndercover.jpg", },
    {id: "WookieGuardian", prototypes: ["ar"], front: "swr/action/ActionCardRebelWookieGuardian.jpg", },
    {id: "HumanCyborgRelations", prototypes: ["ar"], y: 137, front: "swr/action/ActionCardRebelStartingHumanCyborgRelations.jpg", },
    {id: "OurMostDesperateHour", prototypes: ["ar"], y: 137, front: "swr/action/ActionCardRebelStartingOurMostDesperateHour.jpg", },
    {id: "RebelPlanning", prototypes: ["ar"], y: 137, front: "swr/action/ActionCardRebelStartingRebelPlanning.jpg", },
    {id: "ResourcefulAstromech", prototypes: ["ar"], y: 137, front: "swr/action/ActionCardRebelStartingResourcefulAstromech.jpg", },
    {id: "StartTheEvacuation", prototypes: ["ar"], y: 137, front: "swr/action/ActionCardRebelStartingStartTheEvacuation.jpg", },
    {id: "TemporaryAlliance", prototypes: ["ar"], y: 137, front: "swr/action/ActionCardRebelStartingTemporaryAlliance.jpg", },

    {id: "Blindside", prototypes: ["ae"], front: "swr/action/ActionCardEmpireBlindside.jpg", },
    {id: "BobaFettWhere", prototypes: ["ae"], front: "swr/action/ActionCardEmpireBobaFettWhere.jpg", },
    {id: "CatchThemBySurprise", prototypes: ["ae"], front: "swr/action/ActionCardEmpireCatchThemBySurprise.jpg", },
    {id: "FullyOperational", prototypes: ["ae"], front: "swr/action/ActionCardEmpireFullyOperational.jpg", },
    {id: "GoodIntel", prototypes: ["ae"], front: "swr/action/ActionCardEmpireGoodIntel.jpg", },
    {id: "KeepThemFromEscaping", prototypes: ["ae"], front: "swr/action/ActionCardEmpireKeepThemFromEscaping.jpg", },
    {id: "LocalRumors", prototypes: ["ae"], front: "swr/action/ActionCardEmpireLocalRumors.jpg", },
    {id: "ProceedingAsPlanned", prototypes: ["ae"], front: "swr/action/ActionCardEmpireProceedingAsPlanned.jpg", },
    {id: "PublicSupport", prototypes: ["ae"], front: "swr/action/ActionCardEmpirePublicSupport.jpg", },
    {id: "ReadyForAction", prototypes: ["ae"], front: "swr/action/ActionCardEmpireReadyForAction.jpg", },
    {id: "ScoutingMission", prototypes: ["ae"], front: "swr/action/ActionCardEmpireScoutingMission.jpg", },
    {id: "TargetTheGenerator", prototypes: ["ae"], front: "swr/action/ActionCardEmpireTargetTheGenerator.jpg", },
    {id: "AccordingToMyDesign", prototypes: ["ae"], y: 791, front: "swr/action/ActionCardEmpireStartingAccordingToMyDesign.jpg", },
    {id: "BrilliantAdministrator", prototypes: ["ae"], y: 791, front: "swr/action/ActionCardEmpireStartingBrilliantAdministrator.jpg", },
    {id: "ItIsYourDestiny", prototypes: ["ae"], y: 791, front: "swr/action/ActionCardEmpireStartingItIsYourDestiny.jpg", },
    {id: "MoreDangerousThanYouRealize", prototypes: ["ae"], y: 791, front: "swr/action/ActionCardEmpireStartingMoreDangerousThanYouRealize.jpg", },

    {id: "Construct Death Star", prototypes: ["proj"], front: "swr/mission/MissionEmpireProjectConstructDeathStar.jpg", },
    {id: "Construct Factory", prototypes: ["proj"], front: "swr/mission/MissionEmpireProjectConstructFactory.jpg", },
    {id: "Construct Factory ", prototypes: ["Construct Factory"], },
    {id: "Construct Super Star Destroyer", prototypes: ["proj"], front: "swr/mission/MissionEmpireProjectConstructSuperStarDestroyer.jpg", },
    {id: "Construct Super Star Destroyer ", prototypes: ["Construct Super Star Destroyer"], },
    {id: "Oversee Project", prototypes: ["proj"], front: "swr/mission/MissionEmpireProjectOverseeProject.jpg", },
    {id: "Oversee Project ", prototypes: ["Oversee Project"], },
    {id: "Superlaser Online", prototypes: ["proj"], front: "swr/mission/MissionEmpireProjectSuperlaserOnline.jpg", },
    {id: "Superlaser Online ", prototypes: ["Superlaser Online"], },
    {id: "Superlaser Online  ", prototypes: ["Superlaser Online"], },

    {id: "Death Star Plans ", prototypes: ["o3"], front: "swr/objective/ObjectiveLvl3DeathStarPlans.jpg", },
    {id: "Establish Outposts", prototypes: ["o3"], front: "swr/objective/ObjectiveLvl3EstablishOutposts.jpg", },
    {id: "Inspire Sympathy", prototypes: ["o3"], front: "swr/objective/ObjectiveLvl3InspireSympathy.jpg", },
    {id: "Major Victory", prototypes: ["o3"], front: "swr/objective/ObjectiveLvl3MajorVictory.jpg", },
    {id: "Return Of The Jedi", prototypes: ["o3"], front: "swr/objective/ObjectiveLvl3ReturnOfTheJedi.jpg", },
    {id: "Death Star Plans", prototypes: ["o2"], front: "swr/objective/ObjectiveLvl2DeathStarPlans.jpg", },
    {id: "Heart Of The Empire", prototypes: ["o2"], front: "swr/objective/ObjectiveLvl2HeartOfTheEmpire.jpg", },
    {id: "Leave No One Behind", prototypes: ["o2"], front: "swr/objective/ObjectiveLvl2LeaveNoOneBehind.jpg", },
    {id: "Liberation", prototypes: ["o2"], front: "swr/objective/ObjectiveLvl2Liberation.jpg", },
    {id: "Popular Support", prototypes: ["o2"], front: "swr/objective/ObjectiveLvl2PopularSupport.jpg", },
    {id: "Crippling Blow", prototypes: ["o1"], front: "swr/objective/ObjectiveLvl1CripplingBlow.jpg", },
    {id: "Cut Supply Lines", prototypes: ["o1"], front: "swr/objective/ObjectiveLvl1CutSupplyLines.jpg", },
    {id: "Defend The People", prototypes: ["o1"], front: "swr/objective/ObjectiveLvl1DefendThePeople.jpg", },
    {id: "Rebel Assault", prototypes: ["o1"], front: "swr/objective/ObjectiveLvl1RebelAssault.jpg", },
    {id: "Regional Support", prototypes: ["o1"], front: "swr/objective/ObjectiveLvl1RegionalSupport.jpg", },

    {id: "Alderaan Card", prototypes: ["probe"], front: "swr/probe/SystemAlderaan.jpg", },
    {id: "Bespin Card", prototypes: ["probe"], front: "swr/probe/SystemBespin.jpg", },
    {id: "Bothawui Card", prototypes: ["probe"], x: 183, front: "swr/probe/SystemBothawui.jpg", },
    {id: "Cato Neimoidia Card", prototypes: ["probe"], front: "swr/probe/SystemCatoNeimoidia.jpg", },
    {id: "Corellia Card", prototypes: ["probe"], x: 133, front: "swr/probe/SystemCorellia.jpg", },
    {id: "Dagobah Card", prototypes: ["probe"], front: "swr/probe/SystemDagobah.jpg", },
    {id: "Dantooine Card", prototypes: ["probe"], front: "swr/probe/SystemDantooine.jpg", },
    {id: "Dathomir Card", prototypes: ["probe"], front: "swr/probe/SystemDathomir.jpg", },
    {id: "Endor Card", prototypes: ["probe"], front: "swr/probe/SystemEndor.jpg", },
    {id: "Felucia Card", prototypes: ["probe"], front: "swr/probe/SystemFelucia.jpg", },
    {id: "Geonosis Card", prototypes: ["probe"], front: "swr/probe/SystemGeonosis.jpg", },
    {id: "Hoth Card", prototypes: ["probe"], front: "swr/probe/SystemHoth.jpg", },
    {id: "Ilum Card", prototypes: ["probe"], front: "swr/probe/SystemIlum.jpg", },
    {id: "Kashyyyk Card", prototypes: ["probe"], x: 183, front: "swr/probe/SystemKashyyyk.jpg", },
    {id: "Kessel Card", prototypes: ["probe"], front: "swr/probe/SystemKessel.jpg", },
    {id: "Malastare Card", prototypes: ["probe"], front: "swr/probe/SystemMalastare.jpg", },
    {id: "Mandalore Card", prototypes: ["probe"], x: 133, front: "swr/probe/SystemMandalore.jpg", },
    {id: "Mon Calamari Card", prototypes: ["probe"], x: 183, front: "swr/probe/SystemMonCalamari.jpg", },
    {id: "Mustafar Card", prototypes: ["probe"], x: 133, front: "swr/probe/SystemMustafar.jpg", },
    {id: "Mygeeto Card", prototypes: ["probe"], x: 133, front: "swr/probe/SystemMygeeto.jpg", },
    {id: "Naboo Card", prototypes: ["probe"], x: 183, front: "swr/probe/SystemNaboo.jpg", },
    {id: "Nal Hutta Card", prototypes: ["probe"], front: "swr/probe/SystemNalHutta.jpg", },
    {id: "Ord Mantell Card", prototypes: ["probe"], front: "swr/probe/SystemOrdMantell.jpg", },
    {id: "Rodia Card", prototypes: ["probe"], x: 133, front: "swr/probe/SystemRodia.jpg", },
    {id: "Ryloth Card", prototypes: ["probe"], x: 183, front: "swr/probe/SystemRyloth.jpg", },
    {id: "Saleucami Card", prototypes: ["probe"], x: 133, front: "swr/probe/SystemSaleucami.jpg", },
    {id: "Sullust Card", prototypes: ["probe"], x: 133, front: "swr/probe/SystemSullust.jpg", },
    {id: "Tatooine Card", prototypes: ["probe"], front: "swr/probe/SystemTatooine.jpg", },
    {id: "Toydaria Card", prototypes: ["probe"], front: "swr/probe/SystemToydaria.jpg", },
    {id: "Utapau Card", prototypes: ["probe"], front: "swr/probe/SystemUtapau.jpg", },
    {id: "Yavin Card", prototypes: ["probe"], front: "swr/probe/SystemYavin.jpg", },

    {id: "Brilliant Strategy (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceBrilliantStrategy.jpg", },
    {id: "Concentrate Fire (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceConcentrateFire.jpg", },
    {id: "Concentrate Fire (Space) ", prototypes: ["Concentrate Fire (Space)"], },
    {id: "Critical Hit (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceCriticalHit.jpg", },
    {id: "Critical Hit (Space) ", prototypes: ["Critical Hit (Space)"], },
    {id: "Defensive Formation (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceDefensiveFormation.jpg", },
    {id: "Defensive Formation (Space) ", prototypes: ["Defensive Formation (Space)"], },
    {id: "Defensive Formation (Space)  ", prototypes: ["Defensive Formation (Space)"], },
    {id: "No Escape (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceNoEscape.jpg", },
    {id: "Onslaught (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceOnslaught.jpg", },
    {id: "Outmaneuver (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceOutmaneuver.jpg", },
    {id: "Outmaneuver (Space) ", prototypes: ["Outmaneuver (Space)"], },
    {id: "Take It Down (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceTakeItDown.jpg", },
    {id: "Take It Down (Space) ", prototypes: ["Take It Down (Space)"], },
    {id: "Unstoppable Assault (Space)", prototypes: ["ts"], front: "swr/tactics/TacticSpaceUnstoppableAssault.jpg", },

    {id: "Bombardment (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundBombardment.jpg", },
    {id: "Brilliant Strategy (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundBrilliantStrategy.jpg", },
    {id: "Concentrate Fire (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundConcentrateFire.jpg", },
    {id: "Concentrate Fire (Ground) ", prototypes: ["Concentrate Fire (Ground)"], },
    {id: "Critical Hit (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundCriticalHit.jpg", },
    {id: "Critical Hit (Ground) ", prototypes: ["Critical Hit (Ground)"], },
    {id: "Defensive Formation (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundDefensiveFormation.jpg", },
    {id: "Defensive Formation (Ground) ", prototypes: ["Defensive Formation (Ground)"], },
    {id: "Defensive Formation (Ground)  ", prototypes: ["Defensive Formation (Ground)"], },
    {id: "Dig In (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundDigIn.jpg", },
    {id: "Dig In (Ground) ", prototypes: ["Dig In (Ground)"], },
    {id: "Escape Plan (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundEscapePlan.jpg", },
    {id: "Onslaught (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundOnslaught.jpg", },
    {id: "Take It Down (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundTakeItDown.jpg", },
    {id: "Unstoppable Assault (Ground)", prototypes: ["tg"], front: "swr/tactics/TacticGroundUnstoppableAssault.jpg", },

    {id: "Alderaan Loyalty", prototypes: ["loy"], x: 543, y: 675, },
    {id: "Bespin Loyalty", prototypes: ["loy"], x: 1071, y: 651, },
    {id: "Bothawui Loyalty", prototypes: ["loy"], x: 704, y: 300, },
    {id: "Cato Neimoidia Loyalty", prototypes: ["loy"], x: 751, y: 605, },
    {id: "Corellia Loyalty", prototypes: ["loy"], x: 863, y: 734, },
    {id: "Felucia Loyalty", prototypes: ["loy"], x: 271, y: 373, },
    {id: "Geonosis Loyalty", prototypes: ["loy"], x: 1020, y: 313, },
    {id: "Kashyyyk Loyalty", prototypes: ["loy"], x: 561, y: 532, },
    {id: "Kessel Loyalty", prototypes: ["loy"], x: 425, y: 241, },
    {id: "Malastare Loyalty", prototypes: ["loy"], x: 717, y: 504, },
    {id: "Mandalore Loyalty", prototypes: ["loy"], x: 451, y: 592, },
    {id: "Mon Calamari Loyalty", prototypes: ["loy"], x: 210, y: 244, },
    {id: "Mustafar Loyalty", prototypes: ["loy"], x: 1148, y: 529, },
    {id: "Mygeeto Loyalty", prototypes: ["loy"], x: 225, y: 670, },
    {id: "Naboo Loyalty", prototypes: ["loy"], x: 909, y: 440, },
    {id: "Nal Hutta Loyalty", prototypes: ["loy"], x: 561, y: 254, },
    {id: "Ord Mantell Loyalty", prototypes: ["loy"], x: 412, y: 698, },
    {id: "Rodia Loyalty", prototypes: ["loy"], x: 812, y: 352, },
    {id: "Ryloth Loyalty", prototypes: ["loy"], x: 1113, y: 215, },
    {id: "Saleucami Loyalty", prototypes: ["loy"], x: 395, y: 365, },
    {id: "Sullust Loyalty", prototypes: ["loy"], x: 914, y: 600, },
    {id: "Toydaria Loyalty", prototypes: ["loy"], x: 523, y: 386, },
    {id: "Utapau Loyalty", prototypes: ["loy"], x: 1163, y: 386, },

    {id: "Alderaan Sabotage", prototypes: ["sab"], x: 506, y: 682, },
    {id: "Bespin Sabotage", prototypes: ["sab"], x: 1034, y: 658, },
    {id: "Bothawui Sabotage", prototypes: ["sab"], x: 667, y: 307, },
    {id: "Cato Neimoidia Sabotage", prototypes: ["sab"], x: 714, y: 612, },
    {id: "Corellia Sabotage", prototypes: ["sab"], x: 826, y: 741, },
    {id: "Felucia Sabotage", prototypes: ["sab"], x: 234, y: 380, },
    {id: "Geonosis Sabotage", prototypes: ["sab"], x: 983, y: 320, },
    {id: "Kashyyyk Sabotage", prototypes: ["sab"], x: 524, y: 539, },
    {id: "Kessel Sabotage", prototypes: ["sab"], x: 388, y: 248, },
    {id: "Malastare Sabotage", prototypes: ["sab"], x: 680, y: 511, },
    {id: "Mandalore Sabotage", prototypes: ["sab"], x: 414, y: 599, },
    {id: "Mon Calamari Sabotage", prototypes: ["sab"], x: 173, y: 251, },
    {id: "Mustafar Sabotage", prototypes: ["sab"], x: 1111, y: 536, },
    {id: "Mygeeto Sabotage", prototypes: ["sab"], x: 188, y: 677, },
    {id: "Naboo Sabotage", prototypes: ["sab"], x: 872, y: 447, },
    {id: "Nal Hutta Sabotage", prototypes: ["sab"], x: 524, y: 261, },
    {id: "Ord Mantell Sabotage", prototypes: ["sab"], x: 375, y: 705, },
    {id: "Rodia Sabotage", prototypes: ["sab"], x: 775, y: 359, },
    {id: "Ryloth Sabotage", prototypes: ["sab"], x: 1076, y: 222, },
    {id: "Saleucami Sabotage", prototypes: ["sab"], x: 358, y: 372, },
    {id: "Sullust Sabotage", prototypes: ["sab"], x: 877, y: 607, },
    {id: "Toydaria Sabotage", prototypes: ["sab"], x: 486, y: 393, },
    {id: "Utapau Sabotage", prototypes: ["sab"], x: 1126, y: 393, },

    // leaders

    {id: "leader", prototype: true, width: 35, height: 50, hasLabel: true, labelColor: ["#ab1804"], },

    {id: "GeneralRieekan", x: 305, y: 22, prototypes: ["leader"], front: "swr/leader/LeaderRebelGeneralRieekan.png", },
    {id: "JanDodonna", x: 343, y: 22, prototypes: ["leader"], front: "swr/leader/LeaderRebelJanDodonna.png", },
    {id: "MonMothma", x: 305, y: 75, prototypes: ["leader"], front: "swr/leader/LeaderRebelMonMothma.png", },
    {id: "PrincessLeia", x: 343, y: 75, prototypes: ["leader"], front: "swr/leader/LeaderRebelPrincessLeia.png", },

    {id: "AdmiralAckbar", x: 1303, y: 60, prototypes: ["leader"], front: "swr/leader/LeaderRebelAdmiralAckbar.png", },
    {id: "Chewbacca", x: 1343, y: 60, prototypes: ["leader"], front: "swr/leader/LeaderRebelChewbacca.png", },
    {id: "GeneralMadine", x: 1383, y: 60, prototypes: ["leader"], front: "swr/leader/LeaderRebelGeneralMadine.png", },
    {id: "HanSolo", x: 1423, y: 60, prototypes: ["leader"], front: "swr/leader/LeaderRebelHanSolo.png", },
    {id: "LandoCalrissian", x: 1303, y: 115, prototypes: ["leader"], front: "swr/leader/LeaderRebelLandoCalrissian.png", },
    {id: "LukeSkywalkerJedi", x: 1343, y: 115, prototypes: ["leader"], front: "swr/leader/LeaderRebelLukeSkywalkerJedi.png", },
    {id: "LukeSkywalker", x: 1344, y: 115, prototypes: ["leader"], front: "swr/leader/LeaderRebelLukeSkywalker.png", },
    {id: "ObiWanKenobi", x: 1383, y: 115, prototypes: ["leader"], front: "swr/leader/LeaderRebelObiWanKenobi.png", },
    {id: "WedgeAntilles", x: 1423, y: 115, prototypes: ["leader"], front: "swr/leader/LeaderRebelWedgeAntilles.png", },

    {id: "DarthVader", x: 305, y: 827, prototypes: ["leader"], front: "swr/leader/LeaderEmpireDarthVader.png", },
    {id: "EmperorPalpatine", x: 343, y: 827, prototypes: ["leader"], front: "swr/leader/LeaderEmpireEmperorPalpatine.png", },
    {id: "GeneralTagge", x: 305, y: 880, prototypes: ["leader"], front: "swr/leader/LeaderEmpireGeneralTagge.png", },
    {id: "GrandMoffTarkin", x: 343, y: 880, prototypes: ["leader"], front: "swr/leader/LeaderEmpireGrandMoffTarkin.png", },

    {id: "AdmiralOzzel", x: 1303, y: 855, prototypes: ["leader"], front: "swr/leader/LeaderEmpireAdmiralOzzel.png", },
    {id: "AdmiralPiett", x: 1343, y: 855, prototypes: ["leader"], front: "swr/leader/LeaderEmpireAdmiralPiett.png", },
    {id: "BobaFett", x: 1383, y: 855, prototypes: ["leader"], front: "swr/leader/LeaderEmpireBobaFett.png", },
    {id: "ColonelYularen", x: 1423, y: 855, prototypes: ["leader"], front: "swr/leader/LeaderEmpireColonelYularen.png", },
    {id: "GeneralVeers", x: 1303, y: 910, prototypes: ["leader"], front: "swr/leader/LeaderEmpireGeneralVeers.png", },
    {id: "JanusGreejatus", x: 1343, y: 910, prototypes: ["leader"], front: "swr/leader/LeaderEmpireJanusGreejatus.png", },
    {id: "MoffJerjerrod", x: 1383, y: 910, prototypes: ["leader"], front: "swr/leader/LeaderEmpireMoffJerjerrod.png", },
    {id: "SoontirFel", x: 1423, y: 910, prototypes: ["leader"], front: "swr/leader/LeaderEmpireSoontirFel.png", },

    //{id: "Captured Ring", x: 965, y: 118, width: 58, height: 28, front: "swr/marker/RingCaptured.png", },

    // unit prototypes

    {id: "unit", prototype: true, width: 20, height: 20, hasLabel: true, labelColor: ["#ffffff"], },

    {id: "xwing", prototype: true, prototypes: ["unit"], front: "swr/units/x-wing.png"},
    {id: "ywing", prototype: true, prototypes: ["unit"], front: "swr/units/y-wing.png"},
    {id: "transport", prototype: true, prototypes: ["unit"], front: "swr/units/transport.png"},
    {id: "corvette", prototype: true, prototypes: ["unit"], width: 25, height: 25, front: "swr/units/corvette.png"},
    {id: "cruiser", prototype: true, prototypes: ["unit"], width: 30, height: 30, front: "swr/units/cruiser.png"},
    {id: "trooper", prototype: true, prototypes: ["unit"], front: "swr/units/trooper.png"},
    {id: "speeder", prototype: true, prototypes: ["unit"], width: 25, height: 25, front: "swr/units/speeder.png"},
    {id: "ion", prototype: true, prototypes: ["unit"], width: 30, height: 30, front: "swr/units/ion.png"},
    {id: "shield", prototype: true, prototypes: ["unit"], width: 30, height: 30, front: "swr/units/shield.png"},

    {id: "tie", prototype: true, prototypes: ["unit"], front: "swr/units/tie.png"},
    {id: "carrier", prototype: true, prototypes: ["unit"], width: 25, height: 25, front: "swr/units/carrier.png"},
    {id: "sd", prototype: true, prototypes: ["unit"], width: 30, height: 30, front: "swr/units/stardestroyer.png"},
    {id: "stormtrooper", prototype: true, prototypes: ["unit"], front: "swr/units/stormtrooper.png"},
    {id: "atst", prototype: true, prototypes: ["unit"], width: 25, height: 25, front: "swr/units/at-st.png"},
    {id: "atat", prototype: true, prototypes: ["unit"], width: 30, height: 30, front: "swr/units/at-at.png"},
    {id: "ssd", prototype: true, prototypes: ["unit"], width: 40, height: 40, front: "swr/units/superstardestroyer.png"},
    {id: "ds", prototype: true, prototypes: ["unit"], width: 40, height: 40, hasLabel: false, front: "swr/units/deathstar.png"},
    {id: "dsuc", prototype: true, prototypes: ["unit"], width: 40, height: 40, front: "swr/units/deathstarunderconstruction.png"},

    // Starting units

    {id: "X-Wing 1", prototypes: ["xwing"], x: 478, y: 123, },
    {id: "X-Wing 2", prototypes: ["xwing"], x: 481, y: 123, },

    {id: "Y-Wing 1", prototypes: ["ywing"], x: 506, y: 123, },
    {id: "Y-Wing 2", prototypes: ["ywing"], x: 509, y: 123, },

    {id: "Rebel Transport 1", prototypes: ["transport"], x: 534, y: 123, },

    {id: "Corellian Corvette 1", prototypes: ["corvette"], x: 564, y: 121, },

    {id: "Rebel Trooper 1", prototypes: ["trooper"], x: 599, y: 123, },
    {id: "Rebel Trooper 2", prototypes: ["trooper"], x: 602, y: 123, },
    {id: "Rebel Trooper 3", prototypes: ["trooper"], x: 605, y: 123, },
    {id: "Rebel Trooper 4", prototypes: ["trooper"], x: 608, y: 123, },
    {id: "Rebel Trooper 5", prototypes: ["trooper"], x: 611, y: 123, },
    {id: "Rebel Trooper 6", prototypes: ["trooper"], x: 614, y: 123, },

    {id: "Airspeeder 1", prototypes: ["speeder"], x: 639, y: 121, },
    {id: "Airspeeder 2", prototypes: ["speeder"], x: 642, y: 121, },

    {id: "TIE 1", prototypes: ["tie"], x: 478, y: 833, },
    {id: "TIE 2", prototypes: ["tie"], x: 481, y: 833, },
    {id: "TIE 3", prototypes: ["tie"], x: 484, y: 833, },
    {id: "TIE 4", prototypes: ["tie"], x: 487, y: 833, },
    {id: "TIE 5", prototypes: ["tie"], x: 490, y: 833, },
    {id: "TIE 6", prototypes: ["tie"], x: 493, y: 833, },
    {id: "TIE 7", prototypes: ["tie"], x: 496, y: 833, },
    {id: "TIE 8", prototypes: ["tie"], x: 499, y: 833, },
    {id: "TIE 9", prototypes: ["tie"], x: 502, y: 833, },
    {id: "TIE 10", prototypes: ["tie"], x: 505, y: 833, },
    {id: "TIE 11", prototypes: ["tie"], x: 508, y: 833, },
    {id: "TIE 12", prototypes: ["tie"], x: 511, y: 833, },

    {id: "Assault Carrier 1", prototypes: ["carrier"], x: 536, y: 831, },
    {id: "Assault Carrier 2", prototypes: ["carrier"], x: 539, y: 831, },
    {id: "Assault Carrier 3", prototypes: ["carrier"], x: 542, y: 831, },

    {id: "Star Destroyer 1", prototypes: ["sd"], x: 572, y: 828, },
    {id: "Star Destroyer 2", prototypes: ["sd"], x: 575, y: 828, },
    {id: "Star Destroyer 3", prototypes: ["sd"], x: 578, y: 828, },

    {id: "Death Star 1", prototypes: ["ds"], x: 613, y: 823, },

    {id: "Stormtrooper 1", prototypes: ["stormtrooper"], x: 658, y: 833, },
    {id: "Stormtrooper 2", prototypes: ["stormtrooper"], x: 661, y: 833, },
    {id: "Stormtrooper 3", prototypes: ["stormtrooper"], x: 664, y: 833, },
    {id: "Stormtrooper 4", prototypes: ["stormtrooper"], x: 667, y: 833, },
    {id: "Stormtrooper 5", prototypes: ["stormtrooper"], x: 670, y: 833, },
    {id: "Stormtrooper 6", prototypes: ["stormtrooper"], x: 673, y: 833, },
    {id: "Stormtrooper 7", prototypes: ["stormtrooper"], x: 676, y: 833, },
    {id: "Stormtrooper 8", prototypes: ["stormtrooper"], x: 679, y: 833, },
    {id: "Stormtrooper 9", prototypes: ["stormtrooper"], x: 682, y: 833, },
    {id: "Stormtrooper 10", prototypes: ["stormtrooper"], x: 685, y: 833, },
    {id: "Stormtrooper 11", prototypes: ["stormtrooper"], x: 688, y: 833, },
    {id: "Stormtrooper 12", prototypes: ["stormtrooper"], x: 691, y: 833, },

    {id: "AT-ST 1", prototypes: ["atst"], x: 716, y: 831, },
    {id: "AT-ST 2", prototypes: ["atst"], x: 719, y: 831, },
    {id: "AT-ST 3", prototypes: ["atst"], x: 722, y: 831, },
    {id: "AT-ST 4", prototypes: ["atst"], x: 725, y: 831, },
    {id: "AT-ST 5", prototypes: ["atst"], x: 728, y: 831, },

    {id: "AT-AT 1", prototypes: ["atat"], x: 758, y: 828, },

    // units in reserve

    {id: "X-Wing 3", prototypes: ["xwing"], x: 1165, y: 25, },
    {id: "X-Wing 4", prototypes: ["xwing"], x: 1168, y: 25, },
    {id: "X-Wing 5", prototypes: ["xwing"], x: 1171, y: 25, },
    {id: "X-Wing 6", prototypes: ["xwing"], x: 1174, y: 25, },
    {id: "X-Wing 7", prototypes: ["xwing"], x: 1177, y: 25, },
    {id: "X-Wing 8", prototypes: ["xwing"], x: 1180, y: 25, },

    {id: "Y-Wing 3", prototypes: ["ywing"], x: 1165, y: 50, },
    {id: "Y-Wing 4", prototypes: ["ywing"], x: 1168, y: 50, },
    {id: "Y-Wing 5", prototypes: ["ywing"], x: 1171, y: 50, },
    {id: "Y-Wing 6", prototypes: ["ywing"], x: 1174, y: 50, },
    {id: "Y-Wing 7", prototypes: ["ywing"], x: 1177, y: 50, },
    {id: "Y-Wing 8", prototypes: ["ywing"], x: 1180, y: 50, },
    {id: "Y-Wing 9", prototypes: ["ywing"], x: 1183, y: 50, },
    {id: "Y-Wing 10", prototypes: ["ywing"], x: 1186, y: 50, },
    {id: "Y-Wing 11", prototypes: ["ywing"], x: 1189, y: 50, },
    {id: "Y-Wing 12", prototypes: ["ywing"], x: 1192, y: 50, },

    {id: "Rebel Transport 2", prototypes: ["transport"], x: 1165, y: 75, },
    {id: "Rebel Transport 3", prototypes: ["transport"], x: 1168, y: 75, },
    {id: "Rebel Transport 4", prototypes: ["transport"], x: 1171, y: 75, },

    {id: "Corellian Corvette 2", prototypes: ["corvette"], x: 1165, y: 100, },
    {id: "Corellian Corvette 3", prototypes: ["corvette"], x: 1168, y: 100, },
    {id: "Corellian Corvette 4", prototypes: ["corvette"], x: 1171, y: 100, },

    {id: "Mon Calamari Cruiser 1", prototypes: ["cruiser"], x: 1165, y: 130, },
    {id: "Mon Calamari Cruiser 2", prototypes: ["cruiser"], x: 1168, y: 130, },
    {id: "Mon Calamari Cruiser 3", prototypes: ["cruiser"], x: 1171, y: 130, },

    {id: "Rebel Trooper 7", prototypes: ["trooper"], x: 1217, y: 75, },
    {id: "Rebel Trooper 8", prototypes: ["trooper"], x: 1220, y: 75, },
    {id: "Rebel Trooper 9", prototypes: ["trooper"], x: 1223, y: 75, },
    {id: "Rebel Trooper 10", prototypes: ["trooper"], x: 1226, y: 75, },
    {id: "Rebel Trooper 11", prototypes: ["trooper"], x: 1229, y: 75, },
    {id: "Rebel Trooper 12", prototypes: ["trooper"], x: 1232, y: 75, },
    {id: "Rebel Trooper 13", prototypes: ["trooper"], x: 1235, y: 75, },
    {id: "Rebel Trooper 14", prototypes: ["trooper"], x: 1238, y: 75, },
    {id: "Rebel Trooper 15", prototypes: ["trooper"], x: 1241, y: 75, },
    {id: "Rebel Trooper 16", prototypes: ["trooper"], x: 1244, y: 75, },
    {id: "Rebel Trooper 17", prototypes: ["trooper"], x: 1247, y: 75, },
    {id: "Rebel Trooper 18", prototypes: ["trooper"], x: 1250, y: 75, },
    {id: "Rebel Trooper 19", prototypes: ["trooper"], x: 1253, y: 75, },
    {id: "Rebel Trooper 20", prototypes: ["trooper"], x: 1256, y: 75, },
    {id: "Rebel Trooper 21", prototypes: ["trooper"], x: 1259, y: 75, },

    {id: "Airspeeder 3", prototypes: ["speeder"], x: 1217, y: 100, },
    {id: "Airspeeder 4", prototypes: ["speeder"], x: 1220, y: 100, },
    {id: "Airspeeder 5", prototypes: ["speeder"], x: 1223, y: 100, },
    {id: "Airspeeder 6", prototypes: ["speeder"], x: 1226, y: 100, },

    {id: "Shield Generator 1", prototypes: ["shield"], x: 1217, y: 130, },
    {id: "Shield Generator 2", prototypes: ["shield"], x: 1220, y: 130, },
    {id: "Shield Generator 3", prototypes: ["shield"], x: 1223, y: 130, },

    {id: "Ion Cannon 1", prototypes: ["ion"], x: 1258, y: 130, },
    {id: "Ion Cannon 2", prototypes: ["ion"], x: 1261, y: 130, },
    {id: "Ion Cannon 3", prototypes: ["ion"], x: 1264, y: 130, },

    {id: "TIE 13", prototypes: ["tie"], x: 1165, y: 820, },
    {id: "TIE 14", prototypes: ["tie"], x: 1168, y: 820, },
    {id: "TIE 15", prototypes: ["tie"], x: 1171, y: 820, },
    {id: "TIE 16", prototypes: ["tie"], x: 1174, y: 820, },
    {id: "TIE 17", prototypes: ["tie"], x: 1177, y: 820, },
    {id: "TIE 18", prototypes: ["tie"], x: 1180, y: 820, },
    {id: "TIE 19", prototypes: ["tie"], x: 1183, y: 820, },
    {id: "TIE 20", prototypes: ["tie"], x: 1186, y: 820, },
    {id: "TIE 21", prototypes: ["tie"], x: 1189, y: 820, },
    {id: "TIE 22", prototypes: ["tie"], x: 1192, y: 820, },
    {id: "TIE 23", prototypes: ["tie"], x: 1195, y: 820, },
    {id: "TIE 24", prototypes: ["tie"], x: 1198, y: 820, },

    {id: "Assault Carrier 4", prototypes: ["carrier"], x: 1165, y: 855, },
    {id: "Assault Carrier 5", prototypes: ["carrier"], x: 1168, y: 855, },
    {id: "Assault Carrier 6", prototypes: ["carrier"], x: 1171, y: 855, },
    {id: "Assault Carrier 7", prototypes: ["carrier"], x: 1174, y: 855, },
    {id: "Assault Carrier 8", prototypes: ["carrier"], x: 1177, y: 855, },

    {id: "Star Destroyer 4", prototypes: ["sd"], x: 1165, y: 885, },
    {id: "Star Destroyer 5", prototypes: ["sd"], x: 1168, y: 885, },
    {id: "Star Destroyer 6", prototypes: ["sd"], x: 1171, y: 885, },
    {id: "Star Destroyer 7", prototypes: ["sd"], x: 1174, y: 885, },
    {id: "Star Destroyer 8", prototypes: ["sd"], x: 1177, y: 885, },

    {id: "Stormtrooper 13", prototypes: ["stormtrooper"], x: 1223, y: 820, },
    {id: "Stormtrooper 14", prototypes: ["stormtrooper"], x: 1226, y: 820, },
    {id: "Stormtrooper 15", prototypes: ["stormtrooper"], x: 1229, y: 820, },
    {id: "Stormtrooper 16", prototypes: ["stormtrooper"], x: 1232, y: 820, },
    {id: "Stormtrooper 17", prototypes: ["stormtrooper"], x: 1235, y: 820, },
    {id: "Stormtrooper 18", prototypes: ["stormtrooper"], x: 1238, y: 820, },
    {id: "Stormtrooper 19", prototypes: ["stormtrooper"], x: 1241, y: 820, },
    {id: "Stormtrooper 20", prototypes: ["stormtrooper"], x: 1244, y: 820, },
    {id: "Stormtrooper 21", prototypes: ["stormtrooper"], x: 1247, y: 820, },
    {id: "Stormtrooper 22", prototypes: ["stormtrooper"], x: 1250, y: 820, },
    {id: "Stormtrooper 23", prototypes: ["stormtrooper"], x: 1253, y: 820, },
    {id: "Stormtrooper 24", prototypes: ["stormtrooper"], x: 1256, y: 820, },

    {id: "AT-ST 6", prototypes: ["atst"], x: 1223, y: 855, },
    {id: "AT-ST 7", prototypes: ["atst"], x: 1226, y: 855, },
    {id: "AT-ST 8", prototypes: ["atst"], x: 1229, y: 855, },
    {id: "AT-ST 9", prototypes: ["atst"], x: 1232, y: 855, },
    {id: "AT-ST 10", prototypes: ["atst"], x: 1235, y: 855, },

    {id: "AT-AT 2", prototypes: ["atat"], x: 1223, y: 885, },
    {id: "AT-AT 3", prototypes: ["atat"], x: 1226, y: 885, },
    {id: "AT-AT 4", prototypes: ["atat"], x: 1229, y: 885, },

    {id: "Super Star Destroyer 1", prototypes: ["ssd"], x: 1165, y: 920, },
    {id: "Super Star Destroyer 2", prototypes: ["ssd"], x: 1168, y: 920, },

    {id: "Death Star Under Construction", prototypes: ["dsuc"], x: 1213, y: 920, },

    {id: "Death Star 2", prototypes: ["ds"], x: 1258, y: 920, },

    // Dice
    {id: "Red Die 1", x: 1303, y: 200, width: 34, height: 34, faces: ["swr/dice/DiceRedSpecial.png", "swr/dice/DiceRedBlank.png", "swr/dice/DiceRedBlank.png", "swr/dice/DiceRedHit.png", "swr/dice/DiceRedHit.png", "swr/dice/DiceRedDirect.png"], },
    {id: "Red Die 2", prototypes: ["Red Die 1"], y: 240, },
    {id: "Red Die 3", prototypes: ["Red Die 1"], y: 280, },
    {id: "Red Die 4", prototypes: ["Red Die 1"], y: 320, },
    {id: "Red Die 5", prototypes: ["Red Die 1"], y: 360, },

    {id: "Black Die 1", x: 1343, y: 200, width: 34, height: 34, faces: ["swr/dice/DiceBlackSpecial.png", "swr/dice/DiceBlackBlank.png", "swr/dice/DiceBlackBlank.png", "swr/dice/DiceBlackHit.png", "swr/dice/DiceBlackHit.png", "swr/dice/DiceBlackDirect.png"], },
    {id: "Black Die 2", prototypes: ["Black Die 1"], y: 240, },
    {id: "Black Die 3", prototypes: ["Black Die 1"], y: 280, },
    {id: "Black Die 4", prototypes: ["Black Die 1"], y: 320, },
    {id: "Black Die 5", prototypes: ["Black Die 1"], y: 360, },

    // Miscellaneous markers

    {id: "Turn", x: 39, y: 669, width: 23, height: 23, front: "swr/marker/MarkerTurn.png", },
    {id: "Reputation", x: 15, y: 454, width: 23, height: 23, front: "swr/marker/MarkerReputation.png", },

    {id: "Destroyed Planet 3", x: 1298, y: 717, width: 90, height: 90, front: "swr/marker/DestroyedSystem.png", },
    {id: "Destroyed Planet 2", prototypes: ["Destroyed Planet 3"], },
    {id: "Destroyed Planet 1", prototypes: ["Destroyed Planet 3"], },

    {id: "Subjugated 20", x: 1303, y: 817, width: 33, height: 28, front: "swr/marker/MarkerLoyaltySubjugated.png", },
    {id: "Subjugated 19", prototypes: ["Subjugated 20"], x: 1304, },
    {id: "Subjugated 18", prototypes: ["Subjugated 20"], x: 1305, },
    {id: "Subjugated 17", prototypes: ["Subjugated 20"], x: 1306, },
    {id: "Subjugated 16", prototypes: ["Subjugated 20"], x: 1303, y: 818},
    {id: "Subjugated 15", prototypes: ["Subjugated 20"], x: 1304, y: 818},
    {id: "Subjugated 14", prototypes: ["Subjugated 20"], x: 1305, y: 818},
    {id: "Subjugated 13", prototypes: ["Subjugated 20"], x: 1306, y: 818},
    {id: "Subjugated 12", prototypes: ["Subjugated 20"], x: 1303, y: 819},
    {id: "Subjugated 11", prototypes: ["Subjugated 20"], x: 1304, y: 819},
    {id: "Subjugated 10", prototypes: ["Subjugated 20"], x: 1305, y: 819},
    {id: "Subjugated 9", prototypes: ["Subjugated 20"], x: 1306, y: 819},
    {id: "Subjugated 8", prototypes: ["Subjugated 20"], x: 1303, y: 820},
    {id: "Subjugated 7", prototypes: ["Subjugated 20"], x: 1304, y: 820},
    {id: "Subjugated 6", prototypes: ["Subjugated 20"], x: 1305, y: 820},
    {id: "Subjugated 5", prototypes: ["Subjugated 20"], x: 1306, y: 820},
    {id: "Subjugated 4", prototypes: ["Subjugated 20"], x: 1303, y: 821},
    {id: "Subjugated 3", prototypes: ["Subjugated 20"], x: 1304, y: 821},
    {id: "Subjugated 2", prototypes: ["Subjugated 20"], x: 1305, y: 821},
    {id: "Subjugated 1", prototypes: ["Subjugated 20"], x: 1306, y: 821},

    {
      id: "handScreen",
      prototype: true,
      locked: true,
      x: 455,
      width:  700,
      height: 100,
      hideFaces: ["front"],
      snapZones: [{}],
    },
    { prototypes: ["handScreen"], y: 0, visionWhitelist: ["Rebels"], backgroundColor: "rgba(199,65,52,alpha)", labelPlayerName: "Rebels", },
    { prototypes: ["handScreen"], y: 880, visionWhitelist: ["Empire"], backgroundColor: "rgba(63,63,63,alpha)", labelPlayerName: "Empire", },
  ],
};
