module.exports = {
  roles: [
    { id: "Free Peoples", name: "Free Peoples", },
    { id: "Shadow",   name: "Shadow",   },
  ],
  objects: [
    {
      faces: ["wotr/board.jpg"],
      locked: true,
      x: 8,
      y: 150,
      width: 1291,
      height: 891,
    },

    {
      id: "FP Die 1",
      x: 178,
      y: 598,
      width: 32,
      height: 32,
      faces: [
        "wotr/dice/ADFParmymuster.png",
        "wotr/dice/ADFPcharacter.png",
        "wotr/dice/ADFPcharacter.png",
        "wotr/dice/ADFPevent.png",
        "wotr/dice/ADFPmuster.png",
        "wotr/dice/ADFPwill.png",
      ],
    },

    {
      id: "FP Die 2",
      prototypes: ["FP Die 1"],
      x: 228,
    },

    {
      id: "FP Die 3",
      prototypes: ["FP Die 1"],
      x: 278,
    },

    {
      id: "FP Die 4",
      prototypes: ["FP Die 1"],
      x: 328,
    },

    {
      id: "Shadow Die 1",
      x: 178,
      y: 748,
      width: 32,
      height: 32,
      faces: [
        "wotr/dice/ADSAarmymuster.png",
        "wotr/dice/ADSAarmy.png",
        "wotr/dice/ADSAcharacter.png",
        "wotr/dice/ADSAevent.png",
        "wotr/dice/ADSAeye.png",
        "wotr/dice/ADSAmuster.png",
      ],
    },

    {
      id: "Shadow Die 2",
      prototypes: ["Shadow Die 1"],
      x: 228,
    },

    {
      id: "Shadow Die 3",
      prototypes: ["Shadow Die 1"],
      x: 278,
    },

    {
      id: "Shadow Die 4",
      prototypes: ["Shadow Die 1"],
      x: 328,
    },

    {
      id: "Shadow Die 5",
      prototypes: ["Shadow Die 1"],
      x: 203,
      y: 798,
    },

    {
      id: "Shadow Die 6",
      prototypes: ["Shadow Die 1"],
      x: 253,
      y: 798,
    },

    {
      id: "Shadow Die 7",
      prototypes: ["Shadow Die 1"],
      x: 303,
      y: 798,
    },

    {
      id: "settlement",
      prototype: true,
      width: 22,
      height: 22,
      immobile: true,
      faces: [
        "wotr/settlement_fp.png",
        "wotr/settlement_sa.png",
      ],
    },

    {id: "Ered Luin", prototypes: ["settlement"], x: 302, y: 283, },
    {id: "Grey Havens", prototypes: ["settlement"], x: 281, y: 345, },
    {id: "The Shire", prototypes: ["settlement"], x: 387, y: 328, },
    {id: "Bree", prototypes: ["settlement"], x: 496, y: 278, },
    {id: "Rivendell", prototypes: ["settlement"], x: 645, y: 255, },
    {id: "Lorien", prototypes: ["settlement"], x: 710, y: 443, },
    {id: "Carrock", prototypes: ["settlement"], x: 786, y: 260, },
    {id: "Dale", prototypes: ["settlement"], x: 952, y: 305, },
    {id: "Woodland Realm", prototypes: ["settlement"], x: 877, y: 284, },
    {id: "Erebor", prototypes: ["settlement"], x: 953, y: 207, },
    {id: "Iron Hills", prototypes: ["settlement"], x: 1043, y: 217, },
    {id: "Helm's Deep", prototypes: ["settlement"], x: 638, y: 677, },
    {id: "Westemnet", prototypes: ["settlement"], x: 731, y: 635, },
    {id: "Edoras", prototypes: ["settlement"], x: 739, y: 688, },
    {id: "Folde", prototypes: ["settlement"], x: 791, y: 665, },
    {id: "Minas Tirith", prototypes: ["settlement"], x: 849, y: 746, },
    {id: "Lossarnach", prototypes: ["settlement"], x: 824, y: 800, },
    {id: "Pelargir", prototypes: ["settlement"], x: 789, y: 859, },
    {id: "Lamedon", prototypes: ["settlement"], x: 757, y: 774, },
    {id: "Dol Amroth", prototypes: ["settlement"], x: 690, y: 818, },

    {id: "Angmar", prototypes: ["settlement"], x: 497, y: 160, faceIndex: 1},
    {id: "Mount Gundabad", prototypes: ["settlement"], x: 639, y: 168, faceIndex: 1},
    {id: "Moria", prototypes: ["settlement"], x: 692, y: 379, faceIndex: 1},
    {id: "Dol Guldur", prototypes: ["settlement"], x: 859, y: 452, faceIndex: 1},
    {id: "North Rhun", prototypes: ["settlement"], x: 1108, y: 376, faceIndex: 1},
    {id: "South Rhun", prototypes: ["settlement"], x: 1143, y: 569, faceIndex: 1},
    {id: "North Dunland", prototypes: ["settlement"], x: 597, y: 482, faceIndex: 1},
    {id: "South Dunland", prototypes: ["settlement"], x: 585, y: 538, faceIndex: 1},
    {id: "Orthanc", prototypes: ["settlement"], x: 612, y: 597, faceIndex: 1},
    {id: "Morannon", prototypes: ["settlement"], x: 1026, y: 676, faceIndex: 1},
    {id: "Barad Dur", prototypes: ["settlement"], x: 1130, y: 672, faceIndex: 1},
    {id: "Minas Morgul", prototypes: ["settlement"], x: 1015, y: 751, faceIndex: 1},
    {id: "Nurn", prototypes: ["settlement"], x: 1046, y: 861, faceIndex: 1},
    {id: "Umbar", prototypes: ["settlement"], x: 755, y: 992, faceIndex: 1},
    {id: "Near Harad", prototypes: ["settlement"], x: 903, y: 1009, faceIndex: 1},
    {id: "Far Harad", prototypes: ["settlement"], x: 1064, y: 946, faceIndex: 1},

    {id: "Dwarves", x: 1215, y: 412, width: 39, height: 39, faces: ["wotr/pdwarves.png", "wotr/ndwarves.png"],},
    {id: "Elves", x: 1215, y: 452, width: 39, height: 39, faces: ["wotr/nelves.png"],},
    {id: "Gondor", x: 1236, y: 505, width: 39, height: 39, faces: ["wotr/pgondor.png", "wotr/ngondor.png"],},
    {id: "the North", x: 1255, y: 412, width: 39, height: 39, faces: ["wotr/pnorth.png", "wotr/nnorth.png"],},
    {id: "Rohan", x: 1255, y: 452, width: 39, height: 39, faces: ["wotr/prohan.png", "wotr/nrohan.png"],},

    {id: "Isengard", x: 1236, y: 603, width: 39, height: 39, faces: ["wotr/nisengard.png"],},
    {id: "Sauron", x: 1236, y: 643, width: 39, height: 39, faces: ["wotr/nsauron.png"],},
    {id: "Southrons & Easterlings", x: 1236, y: 545, width: 39, height: 39, faces: ["wotr/nsouthron.png"],},

    {
      id: "fp-char",
      prototype: true,
      x: 18,
      y: 159,
      width: 80,
      height: 148,
      back: "wotr/FPCC.jpg",
    },

    {
      id: "fp-army",
      prototype: true,
      x: 115,
      y: 159,
      width: 80,
      height: 148,
      back: "wotr/FPAC.jpg",
    },

    {
      id: "sa-char",
      prototype: true,
      x: 1118,
      y: 885,
      width: 80,
      height: 148,
      back: "wotr/SACC.jpg",
    },

    {
      id: "sa-army",
      prototype: true,
      x: 1216,
      y: 885,
      width: 80,
      height: 148,
      back: "wotr/SAAC.jpg",
    },

    {id: "A Power Too Great", prototypes: ["fp-army"], front: "wotr/cards/fp001.png", },
    {id: "Athelas", prototypes: ["fp-char"], front: "wotr/cards/fp002.png", },
    {id: "Axe and Bow", prototypes: ["fp-char"], front: "wotr/cards/fp003.png", },
    {id: "Bilbo's Song", prototypes: ["fp-char"], front: "wotr/cards/fp004.png", },
    {id: "Book of Mazarbul", prototypes: ["fp-army"], front: "wotr/cards/fp005.png", },
    {id: "Celeborn's Galadhrim", prototypes: ["fp-army"], front: "wotr/cards/fp006.png", },
    {id: "Challenge of the King", prototypes: ["fp-char"], front: "wotr/cards/fp007.png", },
    {id: "Cirdan's Ships", prototypes: ["fp-army"], front: "wotr/cards/fp008.png", },
    {id: "Dain Ironfoot's Guard", prototypes: ["fp-army"], front: "wotr/cards/fp009.png", },
    {id: "Dead Men of Dunharrow", prototypes: ["fp-char"], front: "wotr/cards/fp010.png", },
    {id: "Elven Cloaks", prototypes: ["fp-char"], front: "wotr/cards/fp011.png", },
    {id: "Elven Rope", prototypes: ["fp-char"], front: "wotr/cards/fp012.png", },
    {id: "Eomer, son of Eomund", prototypes: ["fp-army"], front: "wotr/cards/fp013.png", },
    {id: "Faramir's Rangers", prototypes: ["fp-army"], front: "wotr/cards/fp014.png", },
    {id: "Fear! Fire! Foes!", prototypes: ["fp-army"], front: "wotr/cards/fp015.png", },
    {id: "Grimbeorn the Old, Son of Beorn", prototypes: ["fp-army"], front: "wotr/cards/fp016.png", },
    {id: "Guards of the Citadel", prototypes: ["fp-army"], front: "wotr/cards/fp017.png", },
    {id: "Gwaihir the Windlord", prototypes: ["fp-char"], front: "wotr/cards/fp018.png", },
    {id: "Help Unlooked For", prototypes: ["fp-army"], front: "wotr/cards/fp019.png", },
    {id: "Horn of Gondor", prototypes: ["fp-char"], front: "wotr/cards/fp020.png", },
    {id: "House of the Stewards", prototypes: ["fp-char"], front: "wotr/cards/fp021.png", },
    {id: "The Ents Awake: Huorns", prototypes: ["fp-char"], front: "wotr/cards/fp022b2.png", },
    {id: "I Will Go Alone", prototypes: ["fp-char"], front: "wotr/cards/fp023.png", },
    {id: "Imrahil of Dol Amroth", prototypes: ["fp-army"], front: "wotr/cards/fp024.png", },
    {id: "Kindred of Glorfindel", prototypes: ["fp-army"], front: "wotr/cards/fp025.png", },
    {id: "King Brand's Men", prototypes: ["fp-army"], front: "wotr/cards/fp026.png", },
    {id: "Mirror of Galadriel", prototypes: ["fp-char"], front: "wotr/cards/fp027.png", },
    {id: "Mithril Coat and Sting", prototypes: ["fp-char"], front: "wotr/cards/fp028.png", },
    {id: "Paths of the Woses", prototypes: ["fp-army"], front: "wotr/cards/fp029b2.png", },
    {id: "Phial of Galadriel", prototypes: ["fp-char"], front: "wotr/cards/fp030.png", },
    {id: "The Ents Awake: Treebeard", prototypes: ["fp-char"], front: "wotr/cards/fp031b2.png", },
    {id: "Riders of Theoden", prototypes: ["fp-army"], front: "wotr/cards/fp033.png", },
    {id: "Smeagol Helps Nice Master", prototypes: ["fp-char"], front: "wotr/cards/fp034.png", },
    {id: "Swords in Eriador", prototypes: ["fp-army"], front: "wotr/cards/fp035.png", },
    {id: "The Eagles are Coming!", prototypes: ["fp-char"], front: "wotr/cards/fp036.png", },
    {id: "The Grey Company", prototypes: ["fp-char"], front: "wotr/cards/fp037.png", },
    {id: "The Last Battle", prototypes: ["fp-army"], front: "wotr/cards/fp038b2.png", },
    {id: "The Ents Awake: Entmoot", prototypes: ["fp-char"], front: "wotr/cards/fp039b2.png", },
    {id: "The Power of Tom Bombadil", prototypes: ["fp-army"], front: "wotr/cards/fp040.png", },
    {id: "The Red Arrow", prototypes: ["fp-army"], front: "wotr/cards/fp041.png", },
    {id: "The Spirit of Mordor", prototypes: ["fp-army"], front: "wotr/cards/fp042.png", },
    {id: "There and Back Again", prototypes: ["fp-char"], front: "wotr/cards/fp043.png", },
    {id: "There Is Another Way", prototypes: ["fp-char"], front: "wotr/cards/fp044.png", },
    {id: "Thranduil's Archers", prototypes: ["fp-army"], front: "wotr/cards/fp045.png", },
    {id: "Through a Day and a Night", prototypes: ["fp-army"], front: "wotr/cards/fp048.png", },
    {id: "We Prove the Swifter", prototypes: ["fp-char"], front: "wotr/cards/fp049.png", },
    {id: "Wisdom of Elrond", prototypes: ["fp-army"], front: "wotr/cards/fp051.png", },
    {id: "Wizard's Staff", prototypes: ["fp-char"], front: "wotr/cards/fp052.png", },

//    {id: "Balrog of Moria", prototypes: ["sa-char"], front: "wotr/cards/sa001b.png", },
    {id: "A New Power is Rising", prototypes: ["sa-army"], front: "wotr/cards/sa002.png", },
    {id: "Candles of Corpses", prototypes: ["sa-char"], front: "wotr/cards/sa003.png", },
    {id: "Cruel Weather", prototypes: ["sa-char"], front: "wotr/cards/sa005.png", },
    {id: "Denethor's Folly", prototypes: ["sa-army"], front: "wotr/cards/sa007.png", },
    {id: "Dreadful Spells", prototypes: ["sa-char"], front: "wotr/cards/sa008.png", },
    {id: "Flocks of Crebain", prototypes: ["sa-char"], front: "wotr/cards/sa009.png", },
    {id: "Foul Thing from the Deep", prototypes: ["sa-char"], front: "wotr/cards/sa010.png", },
    {id: "Give It To Uss!", prototypes: ["sa-char"], front: "wotr/cards/sa011.png", },
    {id: "Grond, Hammer of the Underworld", prototypes: ["sa-char"], front: "wotr/cards/sa012.png", },
    {id: "Half-orcs and Goblin-men", prototypes: ["sa-army"], front: "wotr/cards/sa013.png", },
    {id: "Hill Trolls", prototypes: ["sa-army"], front: "wotr/cards/sa014.png", },
    {id: "Horde from the East", prototypes: ["sa-army"], front: "wotr/cards/sa015.png", },
    {id: "Isildur's Bane", prototypes: ["sa-char"], front: "wotr/cards/sa016.png", },
    {id: "Lure of the Ring", prototypes: ["sa-char"], front: "wotr/cards/sa017.png", },
    {id: "Many Kings to the Service of Mordor", prototypes: ["sa-army"], front: "wotr/cards/sa018.png", },
    {id: "Monsters Roused", prototypes: ["sa-army"], front: "wotr/cards/sa019.png", },
    {id: "Morgul Wound", prototypes: ["sa-char"], front: "wotr/cards/sa020.png", },
    {id: "Musterings of Long-planned War", prototypes: ["sa-army"], front: "wotr/cards/sa021.png", },
    {id: "Nazgul Search", prototypes: ["sa-char"], front: "wotr/cards/sa022.png", },
    {id: "Olog-Hai", prototypes: ["sa-army"], front: "wotr/cards/sa023.png", },
    {id: "On, On They Went", prototypes: ["sa-char"], front: "wotr/cards/sa024.png", },
    {id: "Orc Patrol", prototypes: ["sa-char"], front: "wotr/cards/sa025.png", },
    {id: "Orcs Multiplying Again", prototypes: ["sa-army"], front: "wotr/cards/sa026.png", },
    {id: "Pits of Mordor", prototypes: ["sa-army"], front: "wotr/cards/sa027.png", },
    {id: "Rage of the Dunlendings", prototypes: ["sa-army"], front: "wotr/cards/sa028b.png", },
    {id: "Return of the Witch-King", prototypes: ["sa-army"], front: "wotr/cards/sa029.png", },
    {id: "Return to Valinor", prototypes: ["sa-army"], front: "wotr/cards/sa030.png", },
    {id: "Shadows Gather", prototypes: ["sa-army"], front: "wotr/cards/sa032.png", },
    {id: "Shadows on the Misty Mountains", prototypes: ["sa-army"], front: "wotr/cards/sa033.png", },
    {id: "Shelob's Lair", prototypes: ["sa-char"], front: "wotr/cards/sa034.png", },
    {id: "Stormcrow", prototypes: ["sa-army"], front: "wotr/cards/sa035.png", },
    {id: "The Black Captain Commands", prototypes: ["sa-char"], front: "wotr/cards/sa036.png", },
    {id: "The Breaking of the Fellowship", prototypes: ["sa-char"], front: "wotr/cards/sa037.png", },
    {id: "Corsairs of Umbar", prototypes: ["sa-army"], front: "wotr/cards/sa038b.png", },
    {id: "The Day Without Dawn", prototypes: ["sa-army"], front: "wotr/cards/sa039.png", },
    {id: "The Fighting Uruk-hai", prototypes: ["sa-army"], front: "wotr/cards/sa040.png", },
    {id: "The King is Revealed", prototypes: ["sa-army"], front: "wotr/cards/sa042.png", },
    {id: "The Lidless Eye", prototypes: ["sa-char"], front: "wotr/cards/sa043.png", },
    {id: "The Nazgul Strike!", prototypes: ["sa-char"], front: "wotr/cards/sa044.png", },
    {id: "The Palantir of Orthanc", prototypes: ["sa-char"], front: "wotr/cards/sa045.png", },
    {id: "The Ring is Mine!", prototypes: ["sa-char"], front: "wotr/cards/sa046.png", },
    {id: "The Ringwraiths Are Abroad", prototypes: ["sa-char"], front: "wotr/cards/sa047.png", },
    {id: "The Shadow is Moving", prototypes: ["sa-army"], front: "wotr/cards/sa048.png", },
    {id: "The Shadow Lengthens", prototypes: ["sa-army"], front: "wotr/cards/sa049.png", },
    {id: "Threats and Promises", prototypes: ["sa-army"], front: "wotr/cards/sa050.png", },
    {id: "Wormtongue", prototypes: ["sa-char"], front: "wotr/cards/sa051.png", },
    {id: "Worn with Sorrow and Toil", prototypes: ["sa-char"], front: "wotr/cards/sa052.png", },

    {id: "Aragorn Card", x: 891, y: 1, width: 80, height: 148, immobile: true, faces: ["wotr/cards/aragorn.jpg"],},
    {id: "Gandalf the White Card", x: 973, y: 1, width: 80, height: 148, immobile: true, faces: ["wotr/cards/gandalf_white.jpg"],},

    {id: "Gollum Card", x: 1219, y: 1, width: 80, height: 148, front: "wotr/cards/gollum.jpg", back: "wotr/cards/smeagol.jpg", },

    {id: "companion card", prototype: true, x: 1136, y: 167, width: 80, height: 148, },

    //{id: "Fellowship Card", prototypes: ["companion card"], front: "wotr/placeholder.png", },
    {id: "Merry Card", prototypes: ["companion card"], front: "wotr/cards/merry.jpg", back: "wotr/cards/merry2.jpg", },
    {id: "Pippin Card", prototypes: ["companion card"], front: "wotr/cards/pippin.jpg", back: "wotr/cards/pippin2.jpg", },
    {id: "Legolas Card", prototypes: ["companion card"], front: "wotr/cards/legolas.jpg", /*back: "wotr/cards/legolas2.jpg",*/ },
    {id: "Gimli Card", prototypes: ["companion card"], front: "wotr/cards/gimli.jpg", back: "wotr/cards/gimli2.jpg", },
    {id: "Boromir Card", prototypes: ["companion card"], front: "wotr/cards/boromir.jpg", back: "wotr/cards/boromir2.jpg", },
    {id: "Strider Card", prototypes: ["companion card"], front: "wotr/cards/strider.jpg", back: "wotr/cards/strider2.jpg", },
    {id: "Gandalf the Grey Card", prototypes: ["companion card"], front: "wotr/cards/gandalf.jpg", back: "wotr/cards/gandalf2.jpg", },

    {
      id: "FP Die 5",
      prototypes: ["FP Die 1"],
      x: 915,
      y: 93,
    },

    {
      id: "FP Die 6",
      prototypes: ["FP Die 5"],
      x: 997,
    },

    {id: "Mouth of Sauron Card", x: 809, y: 1042, width: 80, height: 148, immobile: true, front: "wotr/cards/mouth.jpg", back: "wotr/cards/mouth2.jpg", },
    {id: "Saruman Card", x: 891, y: 1042, width: 80, height: 148, immobile: true, front: "wotr/cards/saruman.jpg",},
    {id: "Witch King Card", x: 973, y: 1042, width: 80, height: 148, immobile: true, front: "wotr/cards/witchking.jpg", back: "wotr/cards/witchking2.jpg", },

    {
      id: "Shadow Die 8",
      prototypes: ["Shadow Die 1"],
      x: 833,
      y: 1134,
    },

    {
      id: "Shadow Die 9",
      prototypes: ["Shadow Die 8"],
      x: 915,
    },

    {
      id: "Shadow Die 10",
      prototypes: ["Shadow Die 8"],
      x: 997,
    },

    {id: "Vilya", x: 281, y: 163, width: 32, height: 32, front: "wotr/vilya.png", back: "wotr/corrupted_ring.png",},
    {id: "Nenya", x: 309, y: 163, width: 32, height: 32, front: "wotr/nenya.png", back: "wotr/corrupted_ring.png",},
    {id: "Narya", x: 338, y: 163, width: 32, height: 32, front: "wotr/narya.png", back: "wotr/corrupted_ring.png",},

    {id: "Fellowship", x: 642, y: 289, width: 22, height: 22, front: "wotr/units/Ringbearer.png",},

    {id: "Gandalf", x: 1259, y: 162, width: 22, height: 22, front: "wotr/units/GandalfGrey.png", back: "wotr/units/GandalfWhite.png"},
    {id: "Aragorn", x: 1259, y: 185, width: 22, height: 22, front: "wotr/units/Strider.png", back: "wotr/units/Aragorn.png"},
    {id: "Boromir", x: 1259, y: 208, width: 22, height: 22, front: "wotr/units/Boromir.png",},
    {id: "Gimli", x: 1259, y: 231, width: 22, height: 22, front: "wotr/units/Gimli.png",},
    {id: "Legolas", x: 1259, y: 254, width: 22, height: 22, front: "wotr/units/Legolas.png",},
    {id: "Pippin", x: 1259, y: 277, width: 22, height: 22, front: "wotr/units/Pippin.png",},
    {id: "Merry", x: 1259, y: 300, width: 22, height: 22, front: "wotr/units/Merry.png",},

    {id: "Mouth of Sauron", x: 838, y: 1084, width: 22, height: 22, front: "wotr/units/Mouth.png",},
    {id: "Saruman", x: 920, y: 1084, width: 22, height: 22, front: "wotr/units/Saruman.png",},
    {id: "Witch King", x: 1002, y: 1084, width: 22, height: 22, front: "wotr/units/WitchKing.png",},

    {id: "Elves Unit 1", x: 286, y: 329, width: 14, height: 14, front: "wotr/units/elves.png", },
    {id: "Elves Unit 2", x: 889, y: 275, prototypes: ["Elves Unit 1"], },
    {id: "Elves Unit 3", x: 698, y: 446, prototypes: ["Elves Unit 1"], },
    {id: "Elves Unit 4", x: 700, y: 2, prototypes: ["Elves Unit 1"], },
    {id: "Elves Unit 5", x: 703, y: 2, prototypes: ["Elves Unit 1"], },
    {id: "Elves Elite 1", x: 257, y: 330, width: 22, height: 22, front: "wotr/units/elves_elite.png", },
    {id: "Elves Elite 2", x: 664, y: 243, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 3", x: 681, y: 263, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 4", x: 901, y: 292, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 5", x: 693, y: 464, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 6", x: 718, y: 465, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 7", x: 700, y: 22, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 8", x: 703, y: 22, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 9", x: 706, y: 22, prototypes: ["Elves Elite 1"], },
    {id: "Elves Elite 10", x: 709, y: 22, prototypes: ["Elves Elite 1"], },
    {id: "Elves Leader 1", x: 303, y: 335, width: 22, height: 22, front: "wotr/units/elves_leader.png", },
    {id: "Elves Leader 2", x: 658, y: 267, prototypes: ["Elves Leader 1"], },
    {id: "Elves Leader 3", x: 877, y: 302, prototypes: ["Elves Leader 1"], },
    {id: "Elves Leader 4", x: 742, y: 473, prototypes: ["Elves Leader 1"], },

    {id: "Dwarves Unit 1", x: 327, y: 290, width: 14, height: 14, front: "wotr/units/dwarves.png", },
    {id: "Dwarves Unit 2", x: 1021, y: 247, prototypes: ["Dwarves Unit 1"], },
    {id: "Dwarves Unit 3", x: 974, y: 247, prototypes: ["Dwarves Unit 1"], },
    {id: "Dwarves Unit 4", x: 737, y: 2, prototypes: ["Dwarves Unit 1"], },
    {id: "Dwarves Unit 5", x: 740, y: 2, prototypes: ["Dwarves Unit 1"], },
    {id: "Dwarves Elite 1", x: 932, y: 227, width: 22, height: 22, front: "wotr/units/dwarves_elite.png", },
    {id: "Dwarves Elite 2", x: 948, y: 248, prototypes: ["Dwarves Elite 1"], },
    {id: "Dwarves Elite 3", x: 737, y: 22, prototypes: ["Dwarves Elite 1"], },
    {id: "Dwarves Elite 4", x: 740, y: 22, prototypes: ["Dwarves Elite 1"], },
    {id: "Dwarves Elite 5", x: 743, y: 22, prototypes: ["Dwarves Elite 1"], },
    {id: "Dwarves Leader 1", x: 965, y: 266, width: 22, height: 22, front: "wotr/units/dwarves_leader.png", },
    {id: "Dwarves Leader 2", x: 737, y: 50, prototypes: ["Dwarves Leader 1"], },
    {id: "Dwarves Leader 3", x: 740, y: 50, prototypes: ["Dwarves Leader 1"], },
    {id: "Dwarves Leader 4", x: 743, y: 50, prototypes: ["Dwarves Leader 1"], },

    {id: "North Unit 1", x: 520, y: 302, width: 14, height: 14, front: "wotr/units/north.png", },
    {id: "North Unit 2", x: 794, y: 286, prototypes: ["North Unit 1"], },
    {id: "North Unit 3", x: 970, y: 298, prototypes: ["North Unit 1"], },
    {id: "North Unit 4", x: 417, y: 322, prototypes: ["North Unit 1"], },
    {id: "North Unit 5", x: 771, y: 2, prototypes: ["North Unit 1"], },
    {id: "North Unit 6", x: 774, y: 2, prototypes: ["North Unit 1"], },
    {id: "North Unit 7", x: 777, y: 2, prototypes: ["North Unit 1"], },
    {id: "North Unit 8", x: 780, y: 2, prototypes: ["North Unit 1"], },
    {id: "North Unit 9", x: 783, y: 2, prototypes: ["North Unit 1"], },
    {id: "North Unit 10", x: 786, y: 2, prototypes: ["North Unit 1"], },
    {id: "North Elite 1", x: 456, y: 243, width: 22, height: 22, front: "wotr/units/north_elite.png", },
    {id: "North Elite 2", x: 771, y: 22, prototypes: ["North Elite 1"], },
    {id: "North Elite 3", x: 774, y: 22, prototypes: ["North Elite 1"], },
    {id: "North Elite 4", x: 777, y: 22, prototypes: ["North Elite 1"], },
    {id: "North Elite 5", x: 780, y: 22, prototypes: ["North Elite 1"], },
    {id: "North Leader 1", x: 986, y: 312, width: 22, height: 22, front: "wotr/units/north_leader.png", },
    {id: "North Leader 2", x: 771, y: 50, prototypes: ["North Leader 1"], },
    {id: "North Leader 3", x: 774, y: 50, prototypes: ["North Leader 1"], },
    {id: "North Leader 4", x: 777, y: 50, prototypes: ["North Leader 1"], },

    {id: "Rohan Unit 1", x: 753, y: 682, width: 14, height: 14, front: "wotr/units/rohan.png", },
    {id: "Rohan Unit 2", x: 679, y: 682, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 3", x: 651, y: 657, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 4", x: 633, y: 664, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 5", x: 700, y: 78, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 6", x: 703, y: 78, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 7", x: 706, y: 78, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 8", x: 709, y: 78, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 9", x: 712, y: 78, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Unit 10", x: 715, y: 78, prototypes: ["Rohan Unit 1"], },
    {id: "Rohan Elite 1", x: 763, y: 697, width: 22, height: 22, front: "wotr/units/rohan_elite.png", },
    {id: "Rohan Elite 2", x: 700, y: 98, prototypes: ["Rohan Elite 1"], },
    {id: "Rohan Elite 3", x: 703, y: 98, prototypes: ["Rohan Elite 1"], },
    {id: "Rohan Elite 4", x: 706, y: 98, prototypes: ["Rohan Elite 1"], },
    {id: "Rohan Elite 5", x: 709, y: 98, prototypes: ["Rohan Elite 1"], },
    {id: "Rohan Leader 1", x: 607, y: 666, width: 22, height: 22, front: "wotr/units/rohan_leader.png", },
    {id: "Rohan Leader 2", x: 700, y: 126, prototypes: ["Rohan Leader 1"], },
    {id: "Rohan Leader 3", x: 703, y: 126, prototypes: ["Rohan Leader 1"], },
    {id: "Rohan Leader 4", x: 706, y: 126, prototypes: ["Rohan Leader 1"], },

    {id: "Gondor Unit 1", x: 834, y: 871, width: 14, height: 14, front: "wotr/units/gondor.png", },
    {id: "Gondor Unit 2", x: 901, y: 809, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 3", x: 905, y: 826, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 4", x: 695, y: 797, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 5", x: 707, y: 810, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 6", x: 712, y: 795, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 7", x: 866, y: 734, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 8", x: 882, y: 739, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 9", x: 888, y: 754, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 10", x: 743, y: 78, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 11", x: 746, y: 78, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 12", x: 749, y: 78, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 13", x: 752, y: 78, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 14", x: 755, y: 78, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Unit 15", x: 758, y: 78, prototypes: ["Gondor Unit 1"], },
    {id: "Gondor Elite 1", x: 866, y: 759, width: 22, height: 22, front: "wotr/units/gondor_elite.png", },
    {id: "Gondor Elite 2", x: 743, y: 98, prototypes: ["Gondor Elite 1"], },
    {id: "Gondor Elite 3", x: 746, y: 98, prototypes: ["Gondor Elite 1"], },
    {id: "Gondor Elite 4", x: 749, y: 98, prototypes: ["Gondor Elite 1"], },
    {id: "Gondor Elite 5", x: 752, y: 98, prototypes: ["Gondor Elite 1"], },
    {id: "Gondor Leader 1", x: 842, y: 770, width: 22, height: 22, front: "wotr/units/gondor_leader.png", },
    {id: "Gondor Leader 2", x: 743, y: 126, prototypes: ["Gondor Leader 1"], },
    {id: "Gondor Leader 3", x: 746, y: 126, prototypes: ["Gondor Leader 1"], },
    {id: "Gondor Leader 4", x: 749, y: 126, prototypes: ["Gondor Leader 1"], },

    {id: "Isengard Unit 1", x: 666, y: 611, width: 14, height: 14, front: "wotr/units/isengard.png", },
    {id: "Isengard Unit 2", x: 650, y: 621, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 3", x: 639, y: 632, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 4", x: 634, y: 615, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 5", x: 569, y: 552, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 6", x: 578, y: 483, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 7", x: 700, y: 1043, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 8", x: 703, y: 1043, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 9", x: 706, y: 1043, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 10", x: 700, y: 1063, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 11", x: 703, y: 1063, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Unit 12", x: 706, y: 1063, prototypes: ["Isengard Unit 1"], },
    {id: "Isengard Elite 1", x: 645, y: 591, width: 22, height: 22, front: "wotr/units/isengard_elite.png", },
    {id: "Isengard Elite 2", x: 700, y: 1083, prototypes: ["Isengard Elite 1"], },
    {id: "Isengard Elite 3", x: 703, y: 1083, prototypes: ["Isengard Elite 1"], },
    {id: "Isengard Elite 4", x: 706, y: 1083, prototypes: ["Isengard Elite 1"], },
    {id: "Isengard Elite 5", x: 700, y: 1111, prototypes: ["Isengard Elite 1"], },
    {id: "Isengard Elite 6", x: 703, y: 1111, prototypes: ["Isengard Elite 1"], },

    {id: "Southron Unit 1", x: 779, y: 1012, width: 14, height: 14, front: "wotr/units/southron.png", },
    {id: "Southron Unit 2", x: 809, y: 999, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 3", x: 794, y: 1006, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 4", x: 986, y: 937, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 5", x: 974, y: 951, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 6", x: 959, y: 960, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 7", x: 1050, y: 974, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 8", x: 1065, y: 975, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 9", x: 1081, y: 966, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 10", x: 1094, y: 365, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 11", x: 1090, y: 385, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 12", x: 1126, y: 578, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 13", x: 1132, y: 595, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 14", x: 1139, y: 610, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 15", x: 734, y: 1043, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 16", x: 737, y: 1043, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 17", x: 740, y: 1043, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 18", x: 743, y: 1043, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 19", x: 746, y: 1043, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 20", x: 734, y: 1063, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 21", x: 737, y: 1063, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 22", x: 740, y: 1063, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 23", x: 743, y: 1063, prototypes: ["Southron Unit 1"], },
    {id: "Southron Unit 24", x: 746, y: 1063, prototypes: ["Southron Unit 1"], },
    {id: "Southron Elite 1", x: 993, y: 915, width: 22, height: 22, front: "wotr/units/southron_elite.png", },
    {id: "Southron Elite 2", x: 1023, y: 940, prototypes: ["Southron Elite 1"], },
    {id: "Southron Elite 3", x: 1122, y: 552, prototypes: ["Southron Elite 1"], },
    {id: "Southron Elite 4", x: 734, y: 1083, prototypes: ["Southron Elite 1"], },
    {id: "Southron Elite 5", x: 737, y: 1083, prototypes: ["Southron Elite 1"], },
    {id: "Southron Elite 6", x: 740, y: 1083, prototypes: ["Southron Elite 1"], },

    {id: "Sauron Unit 1", x: 1048, y: 741, width: 14, height: 14, front: "wotr/units/sauron.png", },
    {id: "Sauron Unit 2", x: 1060, y: 730, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 3", x: 1073, y: 718, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 4", x: 1102, y: 695, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 5", x: 1084, y: 689, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 6", x: 1097, y: 678, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 7", x: 1114, y: 671, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 8", x: 855, y: 437, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 9", x: 870, y: 442, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 10", x: 841, y: 447, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 11", x: 831, y: 463, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 12", x: 849, y: 462, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 13", x: 1007, y: 744, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 14", x: 992, y: 747, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 15", x: 989, y: 764, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 16", x: 1006, y: 765, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 17", x: 1000, y: 778, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 18", x: 710, y: 399, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 19", x: 700, y: 413, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 20", x: 611, y: 175, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 21", x: 610, y: 191, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 22", x: 1004, y: 860, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 23", x: 1023, y: 864, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 24", x: 1009, y: 674, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 25", x: 995, y: 664, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 26", x: 993, y: 682, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 27", x: 997, y: 698, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 28", x: 1011, y: 690, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 29", x: 764, y: 1043, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 30", x: 767, y: 1043, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 31", x: 770, y: 1043, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 32", x: 773, y: 1043, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 33", x: 764, y: 1063, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 34", x: 767, y: 1063, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 35", x: 770, y: 1063, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Unit 36", x: 773, y: 1063, prototypes: ["Sauron Unit 1"], },
    {id: "Sauron Elite 1", x: 1122, y: 691, width: 22, height: 22, front: "wotr/units/sauron_elite.png", },
    {id: "Sauron Elite 2", x: 838, y: 476, prototypes: ["Sauron Elite 1"], },
    {id: "Sauron Elite 3", x: 764, y: 1083, prototypes: ["Sauron Elite 1"], },
    {id: "Sauron Elite 4", x: 767, y: 1083, prototypes: ["Sauron Elite 1"], },
    {id: "Sauron Elite 5", x: 770, y: 1083, prototypes: ["Sauron Elite 1"], },
    {id: "Sauron Elite 6", x: 773, y: 1083, prototypes: ["Sauron Elite 1"], },
    {id: "Nazgul 1", x: 1150, y: 701, width: 22, height: 22, front: "wotr/units/sauron_leader.png", },
    {id: "Nazgul 2", x: 866, y: 473, prototypes: ["Nazgul 1"], },
    {id: "Nazgul 3", x: 1023, y: 772, prototypes: ["Nazgul 1"], },
    {id: "Nazgul 4", x: 1054, y: 674, prototypes: ["Nazgul 1"], },
    {id: "Nazgul 5", x: 764, y: 1111, prototypes: ["Nazgul 1"], },
    {id: "Nazgul 6", x: 767, y: 1111, prototypes: ["Nazgul 1"], },
    {id: "Nazgul 7", x: 770, y: 1111, prototypes: ["Nazgul 1"], },
    {id: "Nazgul 8", x: 773, y: 1111, prototypes: ["Nazgul 1"], },

    {id: "Combat Die 1", x: 668, y: 8, width: 22, height: 22, faces: ["wotr/dice/fp1.png", "wotr/dice/fp2.png", "wotr/dice/fp3.png", "wotr/dice/fp4.png", "wotr/dice/fp5.png", "wotr/dice/fp6.png"], },
    {id: "Combat Die 2", prototypes: ["Combat Die 1"], y: 36, },
    {id: "Combat Die 3", prototypes: ["Combat Die 1"], y: 64, },
    {id: "Combat Die 4", prototypes: ["Combat Die 1"], y: 92, },
    {id: "Combat Die 5", prototypes: ["Combat Die 1"], y: 120, },

    {id: "Combat Die 6", x: 668, y: 1049, width: 22, height: 22, faces: ["wotr/dice/sa1.png", "wotr/dice/sa2.png", "wotr/dice/sa3.png", "wotr/dice/sa4.png", "wotr/dice/sa5.png", "wotr/dice/sa6.png"], },
    {id: "Combat Die 7", prototypes: ["Combat Die 6"], y: 1077, },
    {id: "Combat Die 8", prototypes: ["Combat Die 6"], y: 1105, },
    {id: "Combat Die 9", prototypes: ["Combat Die 6"], y: 1133, },
    {id: "Combat Die 10", prototypes: ["Combat Die 6"], y: 1161, },

    {id: "tile", prototype: true, x: 197, y: 927, width: 40, height: 40, back: "wotr/tiles/back.png",},
/*    {id: "Hunt: 0R", prototypes: ["tile"], front: "wotr/tiles/0r.png",},
    {id: "Hunt: 0R ", prototypes: ["tile"], front: "wotr/tiles/0r.png",},
    {id: "Hunt: 1", prototypes: ["tile"], front: "wotr/tiles/1.png",},
    {id: "Hunt: 1 ", prototypes: ["tile"], front: "wotr/tiles/1.png",},
    {id: "Hunt: 1R", prototypes: ["tile"], front: "wotr/tiles/1r.png",},
    {id: "Hunt: 1R ", prototypes: ["tile"], front: "wotr/tiles/1r.png",},
    {id: "Hunt: 2", prototypes: ["tile"], front: "wotr/tiles/2.png",},
    {id: "Hunt: 2 ", prototypes: ["tile"], front: "wotr/tiles/2.png",},
    {id: "Hunt: 2R", prototypes: ["tile"], front: "wotr/tiles/2r.png",},
    {id: "Hunt: 3", prototypes: ["tile"], front: "wotr/tiles/3.png",},
    {id: "Hunt: 3 ", prototypes: ["tile"], front: "wotr/tiles/3.png",},
    {id: "Hunt: 3  ", prototypes: ["tile"], front: "wotr/tiles/3.png",},
    {id: "Hunt: Eye", prototypes: ["tile"], front: "wotr/tiles/eyer.png",},
    {id: "Hunt: Eye ", prototypes: ["tile"], front: "wotr/tiles/eyer.png",},
    {id: "Hunt: Eye  ", prototypes: ["tile"], front: "wotr/tiles/eyer.png",},
    {id: "Hunt: Eye   ", prototypes: ["tile"], front: "wotr/tiles/eyer.png",},
*/
    {id: "Hunt: 0R", prototypes: ["tile"], front: "wotr/tiles/0r.png",},
    {id: "Hunt: 0R ", prototypes: ["tile"], front: "wotr/tiles/0r.png", x: 198},
    {id: "Hunt: 1", prototypes: ["tile"], front: "wotr/tiles/1.png", x: 199},
    {id: "Hunt: 1 ", prototypes: ["tile"], front: "wotr/tiles/1.png", x: 200},
    {id: "Hunt: 1R", prototypes: ["tile"], front: "wotr/tiles/1r.png", y: 928},
    {id: "Hunt: 1R ", prototypes: ["tile"], front: "wotr/tiles/1r.png",x: 198, y: 928},
    {id: "Hunt: 2", prototypes: ["tile"], front: "wotr/tiles/2.png", x: 199, y: 928},
    {id: "Hunt: 2 ", prototypes: ["tile"], front: "wotr/tiles/2.png", x: 200, y: 928},
    {id: "Hunt: 2R", prototypes: ["tile"], front: "wotr/tiles/2r.png", y: 929},
    {id: "Hunt: 3", prototypes: ["tile"], front: "wotr/tiles/3.png", x: 198, y: 929},
    {id: "Hunt: 3 ", prototypes: ["tile"], front: "wotr/tiles/3.png", x: 199, y: 929},
    {id: "Hunt: 3  ", prototypes: ["tile"], front: "wotr/tiles/3.png", x: 200, y: 929},
    {id: "Hunt: Eye", prototypes: ["tile"], front: "wotr/tiles/eyer.png", y: 930},
    {id: "Hunt: Eye ", prototypes: ["tile"], front: "wotr/tiles/eyer.png", x: 198, y: 930},
    {id: "Hunt: Eye  ", prototypes: ["tile"], front: "wotr/tiles/eyer.png", x: 199, y: 930},
    {id: "Hunt: Eye   ", prototypes: ["tile"], front: "wotr/tiles/eyer.png", x: 200, y: 930},

    {id: "Hunt: Elven Cloaks", prototypes: ["tile"], front: "wotr/tiles/b0.png", x: 805, y: 68,},
    {id: "Hunt: Elven Rope", prototypes: ["tile"], front: "wotr/tiles/b0.png", x: 847, y: 68,},
    {id: "Hunt: Smeagol Helps Nice Master", prototypes: ["tile"], front: "wotr/tiles/b-1.png", x: 805, y: 110,},
    {id: "Hunt: Phial of Galadriel", prototypes: ["tile"], front: "wotr/tiles/b-2.png", x: 847, y: 110,},

    {id: "Hunt: Give It To Uss!", prototypes: ["tile"], front: "wotr/tiles/r1rs.png", x: 700, y: 1139,},
    {id: "Hunt: On, On They Went", prototypes: ["tile"], front: "wotr/tiles/r3s.png", x: 721, y: 1139,},
    {id: "Hunt: Shelob's Lair", prototypes: ["tile"], front: "wotr/tiles/rds.png", x: 742, y: 1139,},
    {id: "Hunt: The Ring is Mine!", prototypes: ["tile"], front: "wotr/tiles/reyers.png", x: 763, y: 1139,},

    {id: "FP Victory", x: 257, y: 992, width: 18, height: 18, front: "wotr/vp_free.png", },
    {id: "Shadow Victory", x: 257, y: 1013, width: 18, height: 18, front: "wotr/vp_shadow.png", },

    {id: "Fellowship Movement", x: 745, y: 159, width: 19, height: 19, front: "wotr/FSP.png", back: "wotr/FSPR.png"},
    {id: "Corruption", x: 741, y: 177, width: 27, height: 27, front: "wotr/corruption.png", },

    {
      id: "handScreen",
      prototype: true,
      locked: true,
      x: 108,
      width:  550,
      height: 150,
      hideFaces: ["front"],
      snapZones: [{}],
    },
    { prototypes: ["handScreen"], y:   0, visionWhitelist: ["Free Peoples"  ], backgroundColor: "rgba(153,181,195,alpha)", labelPlayerName: "Free Peoples",   },
    { prototypes: ["handScreen"], y: 1041, visionWhitelist: ["Shadow"], backgroundColor: "rgba(177,82,60,alpha)",   labelPlayerName: "Shadow", },


// Lords of Middle-Earth expansion
    {id: "Elrond Card", x: 1055, y: 1, width: 80, height: 148, immobile: true, front: "wotr/cards/elrond.jpg", },
    {id: "Galadriel Card", x: 1137, y: 1, width: 80, height: 148, immobile: true, front: "wotr/cards/galadriel.jpg", },
    {id: "Balrog Card", x: 1055, y: 1042, width: 80, height: 148, immobile: true, front: "wotr/cards/balrog-inactive.jpg", back: "wotr/cards/balrog.jpg"},
    {id: "Gothmog Card", x: 1137, y: 1042, width: 80, height: 148, immobile: true, front: "wotr/cards/gothmog.jpg", },
    {id: "We Shall Get It!", x: 1219, y: 1042, width: 80, height: 148, front: "wotr/cards/weshallgetit.jpg", },

    {
      id: "Narya Die",
      x: 253,
      y: 648,
      width: 32,
      height: 32,
      faces: ["wotr/dice/NaryaCharacter-E.png", "wotr/dice/NaryaMuster-E.png", "wotr/dice/NaryaEvent-E.png", "wotr/dice/NaryaCardDraw-E.png", "wotr/dice/NaryaArmy-E.png", "wotr/dice/NaryaEye-E.png"],
    },

    {
      id: "Vilya Die",
      x: 1079,
      y: 93,
      width: 32,
      height: 32,
      faces: ["wotr/dice/VilyaArmy-E.png", "wotr/dice/VilyaMuster-E.png", "wotr/dice/VilyaEvent-E.png", "wotr/dice/VilyaCardDraw-E.png", "wotr/dice/VilyaCardDraw-E.png", "wotr/dice/VilyaEye-E.png"],
    },

    {
      id: "Nenya Die",
      x: 1161,
      y: 93,
      width: 32,
      height: 32,
      faces: ["wotr/dice/NenyaCharacter-E.png", "wotr/dice/NenyaMuster-E.png", "wotr/dice/NenyaEvent-E.png", "wotr/dice/NenyaCardDraw-E.png", "wotr/dice/NenyaCardDraw-E.png", "wotr/dice/NenyaEye-E.png"],
    },

    {
      id: "Balrog Die",
      x: 1079,
      y: 1134,
      width: 32,
      height: 32,
      faces: ["wotr/dice/BalrogCharacter-E.png", "wotr/dice/BalrogActivate-E.png", "wotr/dice/BalrogActivate-E.png", "wotr/dice/BalrogMuster-E.png", "wotr/dice/BalrogCardDraw-E.png", "wotr/dice/BalrogEye-E.png"],
    },

    {
      id: "Gothmog Die",
      x: 1161,
      y: 1134,
      width: 32,
      height: 32,
      faces: ["wotr/dice/GothmogArmyRemove-E.png", "wotr/dice/GothmogArmy-E.png", "wotr/dice/GothmogMuster-E.png", "wotr/dice/GothmogMuster-E.png", "wotr/dice/GothmogCardDraw-E.png", "wotr/dice/GothmogEye-E.png"],
    },

    {id: "Elrond", x: 1084, y: 43, width: 22, height: 22, front: "wotr/units/Elrond.png",},
    {id: "Galadriel", x: 1166, y: 43, width: 22, height: 22, front: "wotr/units/Galadriel.png",},
    {id: "Balrog", x: 1084, y: 1084, width: 22, height: 22, front: "wotr/units/Balrog.png",},
    {id: "Gothmog", x: 1166, y: 1084, width: 22, height: 22, front: "wotr/units/Gothmog.png",},

    {id: "You Know the Way There", prototypes: ["fp-char"], front: "wotr/cards/lome-fp001.png", },
    {id: "Safe Paths in the Dark", prototypes: ["fp-char"], front: "wotr/cards/lome-fp002.png", },
    {id: "Wind from the West", prototypes: ["fp-char"], front: "wotr/cards/lome-fp003.png", },
    {id: "Three Rings for Elven-Kings", prototypes: ["fp-char"], front: "wotr/cards/lome-fp004.png", },
    {id: "Every Little Is a Gain", prototypes: ["fp-army"], front: "wotr/cards/lome-fp005.png", },
    {id: "Rangers of the North", prototypes: ["fp-army"], front: "wotr/cards/lome-fp006.png", },

    {id: "We Won't Go Back", prototypes: ["sa-char"], front: "wotr/cards/lome-sa001.png", },
    {id: "The Lore of the Elven Rings", prototypes: ["sa-char"], front: "wotr/cards/lome-sa002.png", },
    {id: "The Gates Are Closed", prototypes: ["sa-char"], front: "wotr/cards/lome-sa003.png", },
    {id: "Captain of Despair", prototypes: ["sa-char"], front: "wotr/cards/lome-sa004.png", },
    {id: "Shadow of Dol Guldur", prototypes: ["sa-army"], front: "wotr/cards/lome-sa005.png", },
    {id: "Madness and Horror", prototypes: ["sa-army"], front: "wotr/cards/lome-sa006.png", },
// remember to comment out other balrog card (line 254)
    {id: "A Balrog is Come!", prototypes: ["sa-char"], front: "wotr/cards/lome-sa007.png", },

    {id: "Hunt: Smeagol", prototypes: ["tile"], front: "wotr/tiles/s.png", x: 196, y: 929, z: -1},
    {id: "Hunt: Smeagol ", prototypes: ["tile"], front: "wotr/tiles/s.png", x: 196, y: 930, z: -2},

    {id: "Hunt: Smeagol  ", prototypes: ["tile"], front: "wotr/tiles/s.png", x: 805, y: 26},
    {id: "Hunt: Smeagol   ", prototypes: ["tile"], front: "wotr/tiles/s.png", x: 847, y: 26},

    {id: "Action Counter - Minions", x: 38, y: 1075, width: 35, height: 35, front: "wotr/Shadowaction1-E.png", },
    {id: "Action Counter - Political", x: 38, y: 1125, width: 35, height: 35, front: "wotr/Shadowaction2-E.png", },
  ],
};
